### ISSUE TITLE
How to use router.addRoute function to add a route with children?

### ISSUE THREAD

**Issue by Abandoned9** [vuejs/router#1053]
### Version
4.0.10

### Reproduction link
[https://codepen.io/DimitriYoon/pen/RwVyENQ](https://codepen.io/DimitriYoon/pen/RwVyENQ)

### Steps to reproduce
I own a router, and its format is like this
```javascript
{
    path: "/index",
    name: "Index",
    component: () => import("@/views/xxxx.vue"),
    children: [
        {
            path: "/index/login",
            name: "Login"
            component: () => import("@/views/login.vue"),
        },
        {
            path: "/index/test",
            name: "Test"
            component: () => import("@/views/Test.vue"),
        },
        {
            path: "/index/test1",
            name: "Test1"
            component: () => import("@/views/Test1.vue"),
        }
    ]
}
```
When I use router.addRoute to add a route
router.addRoute(xxx)
I used console.log(router.getRoutes) to see which routes I added, but the result was different from what I expected

### What is expected?
```javascript
{
    path: "/index",
    name: "Index",
    component: () => import("@/views/xxxx.vue"),
    children: [
        {
            path: "/index/login",
            name: "Login"
            component: () => import("@/views/login.vue"),
        },
        {
            path: "/index/test",
            name: "Test"
            component: () => import("@/views/Test.vue"),
        },
        {
            path: "/index/test1",
            name: "Test1"
            component: () => import("@/views/Test1.vue"),
        }
    ]
}
```

### What is actually happening?
```javascript
{
    path: "/index/login",
    name: "Login"
    component: () => import("@/views/login.vue"),
},
{
    path: "/index/test",
    name: "Test"
    component: () => import("@/views/Test.vue"),
},
{
    path: "/index/test1",
    name: "Test1"
    component: () => import("@/views/Test1.vue"),
},
{
    path: "/index",
    name: "Index",
    component: () => import("@/views/xxxx.vue"),
    children: [
        {
            path: "/index/login",
            name: "Login"
            component: () => import("@/views/login.vue"),
        },
        {
            path: "/index/test",
            name: "Test"
            component: () => import("@/views/Test.vue"),
        },
        {
            path: "/index/test1",
            name: "Test1"
            component: () => import("@/views/Test1.vue"),
        }
    ]
}
```

**Comment by PeterAlfredLee** [comment]
@Abandoned9 
This is an expected behavior, `addRoute` will normalizes nested routes and adds them to the record.
Related implementations can be viewed [here](https://github.com/vuejs/vue-router-next/blob/71c2360752b05e2c776b424b5f3220af3b6ee978/src/matcher/index.ts#L158).

**Comment by Abandoned9** [comment]
> @Abandoned9
> 这是预期的行为，`addRoute`将规范化嵌套路由并将它们添加到记录中。
> 相关实现可以在[这里](https://github.com/vuejs/vue-router-next/blob/71c2360752b05e2c776b424b5f3220af3b6ee978/src/matcher/index.ts#L158)查看。

But doing so, when I visit the route added by addRoute, it will prompt `No match found for location with path.` How can I add this route correctly?

**Comment by PeterAlfredLee** [comment]
> But doing so, when I visit the route added by addRoute, it will prompt No match found for location with path. How can I add this route correctly?

Can you provide a reproduction link which will shows the warning you mentioned?

**Comment by Abandoned9** [comment]
> > 但是这样做，当我访问addRoute添加的路由时，会提示No match found for location with path。如何正确添加这条路线？
> 
> 你能提供一个复制链接来显示你提到的警告吗？

just ` No match found for location with path '/xxx' ` nothing else

**Comment by Abandoned9** [comment]
`const fmtRoutes = []
routes.forEach(route => {
	if(route.children){
		route.children = formatRoutes(route.children)
	}
	let fmtRoute = {
		path: route.path,
		component: resolve => {
			require([`./views/${route.component}.vue`], resolve)
		},
		name: route.name,
		nameZh: route.nameZh
		iconCls: route.iconCls,
		meta: {
			requireAuth: true
		},
		children: route.children
	}
	fmtRoutes.push(fmtRoute)
})
return fmtRoutes

// Then I call it in other functions

router.addRoute(fmtRoutes[0])`

是否有可能是`component`的使用方法错误？

**Comment by posva** [comment]
Yeah, this is the expected format for nested routes: they create extra route records so the router can work
