### ISSUE TITLE
Document examples with new <script setup> SFC syntax

### ISSUE THREAD

**Issue by Soviut** [vuejs/router#1074]
### What problem does this feature solve?
There is an [new SFC syntax](https://v3.vuejs.org/api/sfc-script-setup.html) that uses `<script setup>` to remove a lot of boilerplate from the composition api. It would be good to show examples of this being used with vue router.

I specifically want this because I found out that `import router from 'vue-router'` seems to work without needing `useRouter()`. I'm not sure if this is intentional or has side effects I'm unaware of.

### What does the proposed API look like?
No changes, just docs.

**Comment by posva** [comment]
Not sure if this is a good idea. It depends on how the syntax is presented in the docs.

Regarding the import router from Vue-router. I doubt that worked, probably it worked because of something else

**Comment by Soviut** [comment]
@posva I looked at my code again and realized the import was `import router from '@/router'`. So that's why it worked.

**Comment by posva** [comment]
I see. You should really use useRouter inside components

**Comment by Soviut** [comment]
I normally do, I just let VSCode do the import in this case and it worked. I had blinders on because I was experimenting with the new SFC syntax and assumed it was that that allowed it; turns out it was just the direct import from the routes file.

**Comment by fullmooooon** [comment]
My past WRONG code
```
<script setup>
import {useRouter} from 'vue-router'
</script>
```
in chrome log
```
[Vue warn]: inject() can only be used inside setup() or functional components.
```

Thank you for your inspiration. 
I think this is the right way to import router in < script setup >.

It is important to teach beginners how to import 'vue-router' in the document.

Can anyone improve the document?

In addition, I would like to point out that'@ / router' is related to the configuration of vite.config.js and the location of router.js.
```
//vite.config.js   
resolve: {
    alias: {
      '@': resolve(__dirname, "./src")
    }
  },
```

**Comment by andrew-vdb** [comment]
Anyone have sample using vue-router with script setup, vite? 
No matter what I do, it does not seems to work

![image](https://user-images.githubusercontent.com/12871379/149324984-4211fd3b-1d31-444d-bc1d-c0f725171555.png)

**Comment by andrew-vdb** [comment]
when i try to import RouterView
```
import {  useRouter, createRouter, createWebHistory, createWebHashHistory, RouterView } from "vue-router";
```
![image](https://user-images.githubusercontent.com/12871379/149325747-13007bac-275d-4167-84aa-6a311ba572ba.png)
![image](https://user-images.githubusercontent.com/12871379/149325990-e672fff9-2d90-472e-b051-4a21b9d2a916.png)

**Comment by fullmooooon** [comment]
@andrew-vdb 
/src/router/index.js
```
import routes from './routes'
import { createRouter, createWebHashHistory} from 'vue-router'

const router = createRouter({
    history: createWebHashHistory(),
    routes,
})

export default router
```
/src/router/routes.js
```
export default [
    { path: '/helloworld', component: () => import('@/components/helloworld.vue') },
    { path: '/helloworld2', component: () => import('@/components/helloworld2.vue') },
]
```
/src/main.js

```
...some code
import router from '@/router'
createApp(App)
    .use(router)
    .mount('#app')

```

There are two ways to jump, one is in the template
```
<button @click="$router.push('/helloworld')"></button>
<button @click="$router.go(-1)"></button>
```
or use code
```
<template>
    <div>
        <button @click="goback">goback</button>
    </div>
</template>
<script setup>
import router from '@/router'
let goback = () => {
    router.go(-1)
}
</script>
```

vite.config.js
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
const { resolve } = require("path")

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': resolve(__dirname, "./src")
    }
  },
})

```

**Comment by andrew-vdb** [comment]
when i call this
```
import router from '@/router'
```
![image](https://user-images.githubusercontent.com/12871379/149331667-6360c7e9-923d-4cba-8250-c29e7851304c.png)

already updated vite.config.js

**Comment by fullmooooon** [comment]
@andrew-vdb 
Maybe it's the directory structure.
First try
```
import router from '@/router/index.js'
```


Or try to modify
```
'@': resolve(__dirname, "./src")
```
Or you don't have to use the fancy alias.
Replace'@Path 'with a relative path

**Comment by andrew-vdb** [comment]
@fullmooooon thanks, you save my day, i completely forgot **main.js** exists in vite
The vue-router code must be written in **main.js, not App.vue**

I don't use from '@router'
```
import { useRouter } from "vue-router";
const router = useRouter();
```
that will work too

**Comment by Lehoczky** [comment]
I think this could be a very good change now in 2023, since almost every new library uses the `<script setup>` syntax in their documentation, most notably:

- [Pinia](https://pinia.vuejs.org/introduction.html)
- [VueFire](https://vuefire.vuejs.org/guide/getting-started.html)
- [VueJS Official Docs](https://vuejs.org/guide/introduction.html), even thought there is the API switch, it is set to composition API by default
- [Nuxt](https://nuxt.com/docs/getting-started/configuration), which even uses `lang="ts"` in code blocks, something that is worth considering here as well, because of [TypeScript's popularity](https://2022.stateofjs.com/en-US/usage/#js_ts_balance).
- [VueUse](https://vueuse.org/guide/)
- [VeeValidate](https://vee-validate.logaretm.com/v4/guide/overview/)

... and many more. I just picked some of the more popular ones.

**Comment by Readpato** [comment]
I agree with @Lehoczky, but we also have to think that there might be people utilizing the CAPI without `<script setup>` or maybe even an app that's transitioning from the Options API. 

Would it make sense to have an example for each type of API? Or would it make the documentation too bloated?

**Comment by blazing234** [comment]
Think should just switch entirely over to script setup. Or if you really want do like the vuejs website and offer both.

**Comment by fullmooooon** [comment]
Another feasible and elegant way.
Caching useRouter() during setup
```
<template>
  <div @click="clickHandle">
  </div>
</template>
<script setup lang="ts">
import { useRouter } from 'vue-router';
let useRouterResult = useRouter();
let clickHandle = ()=>useRouterResult.go(-1)
</script>
```

https://github.com/vuejs/vue-router/issues/3379

**Comment by fadamakis** [comment]
I think this is long overdue.
[Data fetching](https://router.vuejs.org/guide/advanced/data-fetching.html) and [composition API](https://router.vuejs.org/guide/advanced/composition-api.html) sections should be using the script setup syntax.

**Comment by skirtles-code** [comment]
Most of the examples were updated in #2714 to use SFCs. Where relevant there are now examples of both `<script setup>` and the Options API.

As noted on the PR, the second example on the **Data Fetching** page cannot currently be updated to `<script setup>`, so that specific example is going to need further work.

I think this issue can be closed. Further discussion of the future of the docs can continue on #2068, or by opening new issues about specific problems.
