### ISSUE TITLE
In the scenario of dynamically adding a route using addRoute, no match found for location with path "/ xxx" appears before adding a route

### ISSUE THREAD

**Issue by jiankafei** [vuejs/router#1131]
### What problem does this feature solve?
It is very common to add routes asynchronously and dynamically, such as dynamically adding accessible routes to the data returned through the interface. When accessing the page initially, because the route data is added to the route asynchronously, there is no route of the current path, so an error such as "no match found for location with path /xxx" will be reported.

During router 3.x, you can get asynchronous data and inject routing data, and then display the root router view to solve this problem. The specific methods are as follows.
```html
<--launched The default is false. After data is loaded, it is set to true to load the view-->
<router-view v-if="launched"></router-view>
```
However, using router next, the above methods are no longer effective. Therefore, we hope to add a start method to the router instance. After all routing data is added to the route, start vue-router through the start method, so as to solve this problem perfectly.

### What does the proposed API look like?
```js
const router = createRouter({});
router.addRoute({
    path: '/aaa',
    name: 'aaa',
    component: () => import('@/views/Aaa.vue'),
});
// This method really starts the router
// Global can only be called once, and multiple calls are invalid
router.start();
```

Or implement the above functions in version 3. X.

**Comment by posva** [comment]
The message you see is just a warning to allow people to detect typos and can be safely ignored.

You can also make sure to add your routes before starting the app `app.use(router)` is what triggers the router to _start_. Especially the ones that are directly visited.

Also please open issues in English.

**Comment by jiankafei** [comment]
@posva I tried to start the route with "app. Use (router)" after adding the route asynchronously. Even though I also displayed "router view" after adding the route, I still reported "failed to resolve component: router view at <app> .so your solution can't solve the problem.

**Comment by posva** [comment]
That's because you are mounting before adding the router

**Comment by jiankafei** [comment]
@posva Although you understand me wrong, that's it. I can only avoid this problem in a bad way.
