### ISSUE TITLE
Documentation: Return null/undefined from redirect function to cancel redirect?

### ISSUE THREAD

**Issue by vincerubinetti** [vuejs/router#1148]
### What problem does this feature solve?
It seems like the `redirect` function you can provide in `routes` can use a return value of `null` or `undefined` to cancel the redirect. I do not see this anywhere in the V3 or V4 docs.

Use case: I'm using a "github-pages-style" 404 redirect, where I have a dedicated 404.html file that simply saves the path to sessionStorage, navigates to the app hosted at root, then vue-router when loading the homepage route reads the redirect from sessionStorage and goes there. If there is no sessionStorage (the user just went directly to the homepage), the redirect should be cancelled.

Other peculiar behavior I noticed while running `vue-test-utils` unit tests. Simply returning the `to` parameter creates an endless redirect loop. When serving the app normally in dev mode, vue-router seems to catch this and prevent it, but doesn't do so in Jest.

### What does the proposed API look like?
A little paragraph of explanation of this behavior in the docs would be appreciated.

**Comment by posva** [comment]
This is actually not intended: a redirect always redirects. For conditional redirects, use a navigation guard.
The types of the redirect forbid null and undefined

**Comment by SampsonCrowley** [comment]
Can this be reconsidered? requiring it to be handled in navigation guards means the logic has to be managed for each route. allowing to return null or undefined for a route-defined conditional redirect means it's possible to define where it should go, in the conditions specific to that route
