### ISSUE TITLE
Allow omitting `component`/`components` in a route with `children`

### ISSUE THREAD

**Issue by posva** [vuejs/router#1174]
### What problem does this feature solve?
This would allow avoiding creating empty `() => h(RouterView)` wrappers and losing any wrapping transition/suspense (https://github.com/vuejs/vue-router-next/issues/1173)

### What does the proposed API look like?
The type should allow this definition:

```js
{
  path: '/users'
  children: [
    { path: '', component: UserList },
    { path: ':id', component: UserDetails }
  ]
}
```

**Comment by skeeith** [comment]
@posva sorry I was busy I didn't notice you replied here. looks like you've been busy with this 🔥

**Comment by IlCallo** [comment]
This seem to solve the same problem [this package](https://github.com/dreamonkey/vue-routes-flattener) is about
I think it's a good idea, but I remember Evan being against this, to keep the router structure in line with router-outlets structure

**Comment by posva** [comment]
Ah yeah, [this comment](https://github.com/vuejs/vue-router/issues/745#issuecomment-263410514). The thing was in vue router <4 transitions and keep alive were transparent and they didn't require the verbose `v-slot` version that vue router requires which makes the helper way more complicated to use and very easy to mess up.

It's also worth noting there are other properties to a route record that can be inherited by the children of the route like `meta` or `beforeEnter`
