### ISSUE TITLE
addRoute in Promise/setTimeout do not get resolved on app mount

### ISSUE THREAD

**Issue by donnysim** [vuejs/router#1236]
### Version
4.0.12

### Reproduction link
[jsfiddle.net/xch3or9a/](https://jsfiddle.net/xch3or9a/)

### Steps to reproduce
Set the registerInPromise to true/false to switch when the route is registered - instantly or in a promise. (might need to press Run first in the fiddle to match the url), also noticed that children aren't necessary to reproduce, breaks with root components too.

### What is expected?
Both cases should mount the Foo component.

### What is actually happening?
Foo component is only mounted when registered synchronously, otherwise blank page is displayed.

---
If we name the routes, beforeEach guard also doesn't provide the named route as "to" argument when registered via Promise but gives a generic path route. Was sitting couple hours trying to figure out what's going on but couldn't tell exactly why this happens.

**Comment by posva** [comment]
`app.use(router)` triggers the initial navigation so you can move that inside the promise. You can also call `router.push()` after adding routes.
Maybe we could mention somewhere in the docs that `app.use(router)` is what triggers the initial navigation.

**Comment by donnysim** [comment]
Ooooooh, now it makes sense, got it all wrong when it triggers the navigation, for some reason I was certain it does it when mounted.

**Comment by jayredk** [comment]
Hi @posva can I work on this issue?

**Comment by posva** [comment]
Yes, any issue with good first issue is fine 🙂
