### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by posva** [vuejs/router#1248]
Move to github actions and add back codecov

**Comment by cnschwarz** [comment]
Hi @posva  

If you list all the necessary steps you want to cover I could start by providing a draft. Obviously the secrets and everything would need to be set by you :) 

I guess you want to mirror in a first step all the points covered in this circle config? 
https://github.com/vuejs/router/blob/main/circle.yml 

I can also start with that base and you can give feedback on additional points in a second iteration.

Let me know :)
