### ISSUE TITLE
navigating between pages makes half of the content dissappear when rendering fragments

### ISSUE THREAD

**Issue by FrankSingh** [vuejs/router#1275]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-vjrpgn?file=src/App.vue)

### Steps to reproduce
Navigate to "Hello World 2"

Navigate back to "Hello World"

### What is expected?
The component should be rendered as before

### What is actually happening?
Some root nodes are missing

---
I added vue-router to the vite-ts template and ran into this behavior when switching between my routes.

Only happens when there are multiple root nodes.

This might be an issue of vue/vite instead.

**Comment by beiifeng** [comment]
@FrankSingh  you don't add `key` props for `p` tag.
like this 
https://stackblitz.com/edit/vitejs-vite-bginmn?file=src%2Fcomponents%2FHelloWorld.vue
```
<template>
  <h1>Hello Vue 3 + TypeScript + Vite</h1>

  <p key="1">
    Recommended IDE setup:
    <a href="https://code.visualstudio.com/" target="_blank">VSCode</a>
    +
    <a href="https://github.com/johnsoncodehk/volar" target="_blank">Volar</a>
  </p>

  <p key="2">See <code>README.md</code> for more information.</p>

  <p key="3">
    <a href="https://vitejs.dev/guide/features.html" target="_blank">
      Vite Docs
    </a>
    |
    <a href="https://v3.vuejs.org/" target="_blank">Vue 3 Docs</a>
  </p>

  <button type="button" @click="count++">count is: {{ count }}</button>
  <p key="4">
    Edit
    <code>components/HelloWorld.vue</code> to test hot module replacement.
  </p>
</template>
```

**Comment by posva** [comment]
Trying out with updated deps and it seems to be fixed, so it was likely a problem with vite

**Comment by FrankSingh** [comment]
Actually upgrading vue from 3.2.25 to 3.2.29 fixed it for me. Thank you guys for your help!
