### ISSUE TITLE
Route paths not matching correctly 

### ISSUE THREAD

**Issue by nurdism** [vuejs/router#1276]
### Version
4.0.12

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/routing-issue-vue-router-4-jxb2w?file=/README.md)

### Steps to reproduce
Have the following route config:

```js
const routes = [
  {
    name: "test",
    path: "/test",
    component: Test
  },
  {
    path: "/test/:testId?",
    component: TestId,
    children: [
      {
        name: "test-testId",
        path: "",
        component: TestIdIndex
      },
      {
        name: "test-testId-test",
        path: "test",
        component: TestIdTest
      }
    ]
  }
];
```

### What is expected?
When visiting `http://localhost/test` I expect the rule `path: "/test"` to be matched and I expect `http://localhost/test/` to be matched to `path: "/test/:testId?"`

### What is actually happening?
When visiting `http://localhost/test` the rule `path: "/test/:testId?"` is taking priority over `path: "/test"` and `path: "/test"` is entirely ignored. 

---
I've tried a few combinations of matching `/test/:testId`, `/test/:testId*`, `/test/:testId+` and have unable to get `http://localhost/test` to resolve to `Test` and `http://localhost/test/` to `TestId`, it will switch to one of the other taking priority over the other.

**Comment by nurdism** [comment]
After doing some more digging, it seems something like this could be fixed with added `{ strict: true }`  to the route config. I found this out via a blogpost from 2020. It doesn't seem to be documented other than a small mention in the migrations guide https://next.router.vuejs.org/guide/migration/index.html#removal-of-pathtoregexpoptions this option should be added into the docs for https://next.router.vuejs.org/api/#routerecordraw

**Comment by posva** [comment]
Yes, you need the `strict` option for this.

Closed in favor of https://github.com/vuejs/router/issues/1277
