### ISSUE TITLE
Document wether route params are inserted in order matching the original path

### ISSUE THREAD

**Issue by LifeIsStrange** [vuejs/router#1293]
### What problem does this solve?
https://next.router.vuejs.org/guide/essentials/dynamic-matching.html
If we take the example from the documentation:
/users/:username/posts/:postId

it says route.params resolves to: { username: 'eduardo', postId: '123' }

It can be very useful to iterate over route.params keys under the assumption that the iteration will follow the order of declaration from path params in the provided path.
I think Vue router rightfully insert path params in route.params, following the original declaration order.
Contrary to Maps, JS object iteration order (via for x in y) has some minor constraints but for properties (not functions), iteration order is guaranteed to be the insertion order (except for property keys that begin with a number, that is the only edge case if I remember correctly)
Hence all I'm asking for is an official confirmation that vue router maintain the invariant that is: route params are always inserted in the order declared in the path. If so then I suppose it could be added to the documentation (with a reminder of the technicalities of JS object key iteration order constraints).
(I know that parsing the URL is an alternative but is less convenient and loose params keys)

**Comment by posva** [comment]
I wouldn't rely on the order of the properties of the params object: there is no "contract" on that invariant.

**Comment by LifeIsStrange** [comment]
I think it would be quite straightforward to make the implementation insert params in the path order, in fact that is the most intuitive way to implement the filling of route params. Could you point me where is the implementation fo the dynamic filling of route params ? Then I could understand wether the invariant is held in practice or not.
