### ISSUE TITLE
In version 4.0.12, unable to get the min file

### ISSUE THREAD

**Issue by Shankhadeep1234** [vuejs/router#1296]
### Version
4.0.12

### Reproduction link
[unpkg.com](https://unpkg.com/browse/vue-router@4.0.12/dist/vue-router.min.js)

### Steps to reproduce
I have been using "https://unpkg.com/vue-router/dist/vue-router.min" in our project and it seems like that we don't have any min file there.

Previously it was working as expected but now it's broken.

### What is expected?
Should get minified file

### What is actually happening?
Not able to get it

**Comment by jeremylowery** [comment]
This problem isn't just for the min file. <script src="https://unpkg.com/vue/dist/vue.js"></script> isn't working either.

**Comment by posva** [comment]
https://unpkg.com/browse/vue-router@4.0.12/dist/vue-router.global.prod.js

the new versions use different naming
