### ISSUE TITLE
Type issues with RouteRecordRaw and RouterOptions

### ISSUE THREAD

**Issue by ig-onoffice-de** [vuejs/router#1298]
### Version
4.0.0

### Reproduction link
[jsfiddle.net/v5srquLe/](https://jsfiddle.net/v5srquLe/)

### Steps to reproduce
- Add Routes using typescript.
- do not implement options end, sensitve and strict
- type error occurs ("Argument type {routes: RouteRecordRaw[], history: RouterHistory} is not assignable to parameter type RouterOptions")

### What is expected?
No type error when leaving end, sensitive and strict not implemented

### What is actually happening?
Type error coming up.

---
The line 
```
export declare type PathParserOptions = Pick<_PathParserOptions, 'end' | 'sensitive' | 'strict'>;
```
makes PathParserOptions' keys end, sensitive and strict required. So I have to add them to my Routes array and RouterOptions Object although I do not need them and I think they are not really required. Changing the line to
```
export declare type PathParserOptions = _PathParserOptions;
```
type error is solved, so I think the Pick is the problem here.

**Comment by posva** [comment]
I cannot reproduce with `strict: true` in tsconfig.json. Pick keeps them optional. Maybe you have something else configured differently or a global Pick? You can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to seek help by sharing your tsconfig
