### ISSUE TITLE
Impossible to match "wildcard-followed-by-pattern" routes when URL matches more than one route

### ISSUE THREAD

**Issue by zcrittendon** [vuejs/router#1300]
### Version
4.0.12

### Reproduction link
[jsfiddle.net](https://jsfiddle.net/zcrittendon/xwan32u5/40/)

### Steps to reproduce
Many websites use arbitrary URL paths for SEO purposes, and therefore require "wildcard-followed-by-pattern" routes, such as `/:seoPath(.*)?/p/:productId`:
- `seoPath` is a wildcard, and could match nothing, or `/abc`, or `/abc/123`, etc.
- `/p/productId` is a pattern meant to match a specific product ID, like `/p/005010193`

Occasionally, the "wildcard" part of the `path` may match the same URL pattern as other routes' `path`, in which case there needs to be a way for the "followed-by-pattern" to carry higher importance even though it occurs later in the path.

In Vue Router 3.x, it was possible to give priority to a "wildcard-followed-by-pattern" path by giving it a higher order in the `routes` array.
In Vue Router 4.x, it does not appear possible to give priority to a route with a "wildcard-followed-by-pattern" path.

Here's an example:
```
  routes: [
    {
      path: '/:seoPath(.*)?/p/:productId',
      name: 'ProductRoute',
      component: ProductPage
    },
    {
      path: '/shop/:landingPage(.*)?',
      name: 'LandingPageRoute',
      component: LandingPage
    },
],
```
URL `/shop/men/jeans/p/005010193` could match either route, but the match varies from 3.x to 4.x:
-  matches `ProductRoute` in vue-router 3.x
-  matches `LandingPageRoute` in vue-router 4.x

Vue Router 4 reproduction:
https://jsfiddle.net/zcrittendon/xwan32u5/40/

Vue Router 3 reproduction:
https://jsfiddle.net/zcrittendon/atb0csqr/23/

Vue Router Path Ranker example:
https://paths.esm.dev/?p=AAMeJbiAwRkeTArAMASACwEsOkBQAYAScH5yAICE4J3ABAFXUI1aEqCAnSbMeBuAAWRQ22AJOSAxinCwKhQAyA..&amp;t=/word1&t=/shop/men/jeans/p/005010193

### What is expected?
Vue Router `routes` should be configurable such that a route `path` using "wildcard-followed-by-pattern" will match a URL that also matches a different route's `path`.

### What is actually happening?
Vue Router `routes` cannot be configured such that a route `path` using "wildcard-followed-by-pattern" will match a URL that also matches a different route's `path`.

---
I understand this breaking change from 3.x to 4.x is likely occurring because 4.x uses path rank and 3.x uses `routes` array order, and I understand that path rank is a huge improvement for things like `addRoute()` (e.g. issue #1176).

However, "wildcard-followed-by-pattern" was fully supported in Vue Router 3, and is a very common URL pattern used on many high-traffic e-commerce websites such as Amazon, Nike, Macy's, etc., and it should be a pattern that can be supported in Vue Router 4.x

**Comment by posva** [comment]
In v3, there was the opposite problem: you could never match `/shop/:landingPage(.*)?`. This was a big problem and the path ranking solves it, it's considered a bugfix: with your current solution with v3, going to `{ name: 'LandingPageRoute', params: ... }` and then reloading the page would end up in ProductRoute page.

You can still explicitely refer to **any route** by using its name: `router.push({ name: 'LandingPage', params ... })`

This could be solved with custom matchers, (like custom history) which cannot yet be passed to the router but is planned.

**Comment by zcrittendon** [comment]
@posva the issue with named routes is that they only work for programmatic navigation. When a route is used to load our site with a URL like `/shop/men/jeans/p/005010193` then Vue Router deduces the route name, and in this case would (incorrectly) pick `LandingPageRoute` instead of `ProductPageRoute`.

Your advice matches the work-around I implemented. In `beforeEach` I deconstruct the URL myself and then forcing the correct route using `name`. But this feels like a kludgy solution that should be able to be handled in the individual route.

Custom matchers sounds like a good solution, I'll keep an eye out for that!
