### ISSUE TITLE
change current route path without reloading

### ISSUE THREAD

**Issue by coader** [vuejs/router#1304]
### What problem does this feature solve?
when i create new form like 'order/new', after save, it's path should be 'order/1'
they use the same component, and i use dynamic copoment and tabpage to show it,
so in this multi pages app, i have to use whole url as component key, because when i open 'order/1' and 'order/2', it will show 2 tab pages.

so after save new item, how can i keep current component but the url can changed to 'order/1' without reloading?

### What does the proposed API look like?
...

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
