### ISSUE TITLE
`isReady()` never resolves or errors if a guard prevents initial navigation

### ISSUE THREAD

**Issue by danielroe** [vuejs/router#1305]
### Version
4.0.12

### Reproduction link
[jsfiddle.net/qxt3dpom/24/](https://jsfiddle.net/qxt3dpom/24/)

### Steps to reproduce
Run - and observe that we never resolve `.isReady()`, and therefore vue never mounts. 

### What is expected?
Ideally a failure to resolve would be 'catchable' in some way.

### What is actually happening?
isReady neither resolves nor throws

**Comment by posva** [comment]
The question is what should happen in this scenario? should `isReady()` reject? Or should it resolve with the failure as the resolved value (like router.push)?

**Comment by danielroe** [comment]
It's a tricky one - and I'm persuadable either way. But the documentation describes `isReady` as:

> Returns a Promise that resolves when the router has completed the initial navigation, which means it has resolved all async enter hooks and async components that are associated with the initial route.

Given that, I think we can treat a failure to complete the initial navigation as an _error_. (Future failures to complete navigation wouldn't be errors.) What do you think?

**Comment by posva** [comment]
I agree. Let's try to still get a little more feedback on this

**Comment by posva** [comment]
final thoughts:

- `isReady()` should reject if an initial navigation returns `false`
- Pushing again after a rejection and calling `isReady()` after an initial failed navigation, should yield a new promise:
  ```js
  // arrives at /admin and navigation guard returns false (it could also redirect but this is not the case in this scenario)
  router.isReady().catch((error: Error | NavigationFailure) => {
    router.push('/home') move the user to a different safe location
    return router.isReady() // we can return a new promise (only valid after calling a new push)
  }).then(...)
  ```
