### ISSUE TITLE
Simplified Default Content for <route-view />

### ISSUE THREAD

**Issue by jaitaiwan** [vuejs/router#1307]
### What problem does this feature solve?
In the case where you have nested routes, you must specify the v-slot option to conditionally check if `Component` has been provided.

For example a Settings page that provides a list of common settings which is replaced when going to a sub route (e.g. `/settings` to `/settings/profile`) you currently have to use <router-view /> with the v-slots option so that you can conditionally display content depending on if the subroute's `Component` is available.

The equivalent in standard vue is that whatever is inside a slot `<slot><div>DEFAULT CONTENT HERE IF SLOT NOT PROVIDED</div></slot>` will be displayed unless it's provided with content.

### What does the proposed API look like?
Simply:

```
<router-view><div>Default Content Here</div></router-view>
```

Instead of:

```
<router-view v-slots="{Component}">
  <component :is="Component" />
  <div v-if="!Component">Default Content Here</div>
</router-view>
```

**Comment by posva** [comment]
This is not possible because the slot is already used. You can use the version you proposed thi
