### ISSUE TITLE
之前打包到unpkg有 vue-router.js 文件。 现在404了。 

### ISSUE THREAD

**Issue by MisterChangRay** [vuejs/router#1308]
### Version
4.0.12

### Steps to reproduce
项目之前访问的资源路径为：
https://unpkg.com/vue-router@4.0.12/dist/vue-router.js

目前404.  之前已经稳定持续使用两年了。  这样随便更换文件名有点难受额

这样项目GG了啊

### What is expected?
文件名错了

### What is actually happening?
项目404了

---
可以顺便打包一个文件叫  vue-router.js  不

**Comment by sodatea** [comment]
4.0.0-alpha.4 起就没有这个路径了。我想你需要的可能是 https://unpkg.com/vue-router@3.5.3/dist/vue-router.js （Vue 2 版本）

**Comment by sodatea** [comment]
关于路径问题，我们之前也发布过公告的 https://zhuanlan.zhihu.com/p/460055155
线上如果使用 unpkg 等服务，请务必加上版本号。

**Comment by MisterChangRay** [comment]
> 4.0.0-alpha.4 起就没有这个路径了。我想你需要的可能是 https://unpkg.com/vue-router@3.5.3/dist/vue-router.js （Vue 2 版本）

但是老哥  
https://unpkg.com/vue-router@4.0.12/dist/vue-router.js
这个路径 过年前都是好好的。 能够正常加载的。 
就年过完了就G了

**Comment by MisterChangRay** [comment]
我发的路径就是我项目里面引用路径。加版本号了的啊

**Comment by sodatea** [comment]
你项目里的路径应该是 latest 或者没加版本号然后被自动重定向到了现在这个版本吧……
npm 上已发布的包不可能被修改。所以这个 4.0.12 这个路径肯定是不存在的。
过年前到现在唯一的变化就是 latest 从 3.x 改到了 4.x。

**Comment by yyx990803** [comment]
这个路径 https://unpkg.com/vue-router@4.0.12/dist/vue-router.js **从来就没有存在过**。4.0.12 是去年 10 月发布的，你说你两年前就在用了？
