### ISSUE TITLE
router-view 能否将matchedRoute暴露出来？

### ISSUE THREAD

**Issue by 289420843** [vuejs/router#1312]
### What problem does this feature solve?
在嵌套路由中，我需要在自定义插槽中获取当前RouterView匹配到的路由节点配置信息，如果不能暴露出matchedRoute，请问我该如何获取？

### What does the proposed API look like?
`<router-view v-slot="{ Component, route, matchedRoute }">
  <custom :component="Component"  :route="matchedRoute"/>
</router-view>`

**Comment by posva** [comment]
`matchedRoute` shouldn't be necessary in userland. If you think this is worth adding, please open an RFC in the vuejs/rfcs repo. Note you can manually get it with the `route.matched` array.
