### ISSUE TITLE
Fetching before navigation with `async setup()`

### ISSUE THREAD

**Issue by ol1s** [vuejs/router#1313]
### What problem does this feature solve?
I have a route component that fetches data in the `async setup()` method. How can I navigate to this route so that the data fetching happens before the `<RouterView>` is updated?

### What does the proposed API look like?
```
async beforeRouteEnter(to, from, next) {
  await next() //fires setup() method
}
```

**Comment by posva** [comment]
At the moment you can't. This is something that still needs refinement and I'm still working on an RFC for it.
