### ISSUE TITLE
(migration build) WATCH_ARRAY in @vue/compat is triggered by RouterView

### ISSUE THREAD

**Issue by IgorLockyh** [vuejs/router#1315]
### Version
3.2.30

### Reproduction link
[github.com](https://github.com/IgorLockyh/vue-compat-watch_array-bug)

### Steps to reproduce
You can either clone repository(Link to minimal reproduction) or create app with vue-router and @vue/compat

### What is expected?
"[Vue warn]: (deprecation WATCH_ARRAY)..." should be triggered only when the user code is "watching" an array in some of his components with the "watch" option

### What is actually happening?
"[Vue warn]: (deprecation WATCH_ARRAY)" is triggered by the RouterView when user does not watch any arrays in his components with the "watch" option

---
I ran into this bug during migration from vue2 to vue3

**Comment by LinusBorg** [comment]
@posva We likely should add a `compatConfig: { MODE: 3 }` to RouterView and RouterLink to keep any such compar warnings from popping up for them - the router's own components don't need to run in compat mode, anyway.
