### ISSUE TITLE
Nested routes + `<Suspense>` triggers Vue unhandled error

### ISSUE THREAD

**Issue by danielroe** [vuejs/router#1319]
### Version
4.0.12

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-b58tid)

### Steps to reproduce
When there are nested routes in which each nested RouterView has its own Suspense, navigating again before suspense resolves triggers  a Vue internals bug.

Click the navigate button multiple times in succession. You should see the following errors:

```bash
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RouterView> 
  at <App>

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
  at parentNode (runtime-dom.esm-bundler.js:35:30)
  at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5109:17)
  at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
  at callWithErrorHandling (runtime-core.esm-bundler.js:155:36)
  at flushJobs (runtime-core.esm-bundler.js:394:17)
```

### What is expected?
I'm expecting that there would not be an error.

### What is actually happening?
There is an error.

---
I'm raising this here but please let me know if you think this isn't an issue with the router and is in fact a vue core bug.

**Comment by posva** [comment]
This reminds me of an error with Suspense in core but I couldn't find the issue. I will have to take a look see if it's specific to router. This will be necessary for `onBeforeNavigate()`

**Comment by danielroe** [comment]
**Related issue**: https://github.com/nuxt/framework/issues/3141 (which occurs if you add `<Transition>` around the component, as recommended here: https://vuejs.org/guide/built-ins/suspense.html#combining-with-other-components

**Comment by posva** [comment]
Managed to reproduce with a [smaller version without Vue Router](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgc2hhbGxvd1JlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbiAgaW1wb3J0IFBhcmVudFN5bmMgZnJvbSAnLi9QYXJlbnRTeW5jLnZ1ZSdcbiAgaW1wb3J0IFBhcmVudEFzeW5jIGZyb20gJy4vUGFyZW50QXN5bmMudnVlJ1xuICBpbXBvcnQgQ2hpbGRBc3luYyBmcm9tICcuL0NoaWxkQXN5bmMudnVlJ1xuICBpbXBvcnQgQ2hpbGRTeW5jIGZyb20gJy4vQ2hpbGRTeW5jLnZ1ZSdcbiAgaW1wb3J0IFJvdXRlclZpZXcgZnJvbSAnLi9Sb3V0ZXJWaWV3LnRzJ1xuXG5cdGNvbnN0IHJvdXRlID0gc2hhbGxvd1JlZigpXG4gIHNob3dTeW5jKClcblx0cHJvdmlkZSgncm91dGUnLCByb3V0ZSlcbiAgXG4gIGZ1bmN0aW9uIHNob3dTeW5jKCkge1xuICAgIHJvdXRlLnZhbHVlID0gW1BhcmVudFN5bmMsIENoaWxkU3luY11cbiAgfVxuICBmdW5jdGlvbiBzaG93QXN5bmMoKSB7XG4gICAgcm91dGUudmFsdWUgPSBbUGFyZW50QXN5bmMsIENoaWxkQXN5bmNdXG4gIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd1N5bmNcIj5cbiAgICBTaG93IFN5bmNcbiAgPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd0FzeW5jXCI+XG4gICAgU2hvdyBBc3luY1xuICA8L2J1dHRvbj5cbiAgPHA+XG4gICAgQ2xpY2sgb24gU2hvdyBBc3luYyBhbmQgY2hlY2sgdGhlIGNvbnNvbGUuIFRoZSBDaGlsZCBBc3luYyBpcyBtb3VudGVkIHR3aWNlOiBmaXJzdCBieSB0aGUgUGFyZW50U3luYyB3aGljaCBpcyBiZWluZyBkZXRhY2hlZCBieSB0aGUgaW5jb21pbmcgUGFyZW50QXN5bmMgYW5kIGJ5IHRoZSBQYXJlbnRBc3luYyBpdHNlbGYuXG4gIDwvcD5cbiAgPGhyPlxuICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PiAgXG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJQYXJlbnRTeW5jLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG4gIGltcG9ydCBSb3V0ZXJWaWV3IGZyb20gJy4vUm91dGVyVmlldy50cydcbiAgXG5cdGNvbnNvbGUubG9nKCdQYXJlbnQgU3luYyBsb2FkaW5nJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgUGFyZW50IFN5bmNcbiAgICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiQ2hpbGRTeW5jLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5cdGNvbnNvbGUubG9nKCdDaGlsZCBTeW5jIGxvYWRpbmcnKVxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgQ2hpbGQgU3luY1xuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiUGFyZW50QXN5bmMudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IFJvdXRlclZpZXcgZnJvbSAnLi9Sb3V0ZXJWaWV3LnRzJ1xuICBcblx0Y29uc29sZS5sb2coJ1BhcmVudCBBc3luYyDijJvvuI8gbG9hZGluZycpXG4gIGF3YWl0IG5ldyBQcm9taXNlKHJlc29sdmUgPT4gc2V0VGltZW91dChyZXNvbHZlLCAzMDApKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICBQYXJlbnQgQXN5bmNcbiAgICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiUm91dGVyVmlldy50cyI6ImltcG9ydCB7IHByb3ZpZGUsIGluamVjdCwgaCB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgUm91dGVyVmlldyA9IHtcbiAgbmFtZTogJ1JvdXRlclZpZXcnLFxuICBzZXR1cChwcm9wcywgeyBzbG90cyB9KSB7XG5cdFx0Y29uc3Qgcm91dGUgPSBpbmplY3QoJ3JvdXRlJylcbiAgICBjb25zdCBkZXB0aCA9IGluamVjdCgnZGVwdGgnLCAwKSBcbiAgICBcbiAgICBwcm92aWRlKCdkZXB0aCcsIGRlcHRoICsgMSlcbiAgICAvLyBpcyB0aGVyZSBhIHdheSB0byBmaXggdGhlIHByb3ZpZGVkIHRvIHRoZSBjdXJyZW50IHJlbmRlcmVkIHRyZWU/XG4gICAgLy8gcHJvdmlkZSgncm91dGUnLCByb3V0ZSlcbiAgICBcbiAgICByZXR1cm4gKCkgPT4ge1xuICAgICAgY29uc3QgY3VycmVudCA9IHJvdXRlLnZhbHVlW2RlcHRoXVxuICAgICAgcmV0dXJuIHNsb3RzLmRlZmF1bHQoeyBDb21wb25lbnQ6IGN1cnJlbnQgfSlbMF1cbiAgICB9XG4gIH1cbn1cblxuZXhwb3J0IGRlZmF1bHQgUm91dGVyVmlldyIsIkNoaWxkQXN5bmMudnVlIjoiPHNjcmlwdCBzZXR1cD5cblx0Y29uc29sZS5sb2coJ0NoaWxkIEFzeW5jIOKMm++4jyBsb2FkaW5nJylcbiAgYXdhaXQgbmV3IFByb21pc2UocmVzb2x2ZSA9PiBzZXRUaW1lb3V0KHJlc29sdmUsIDMwMCkpXG4gIFxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICBDaGlsZCBBc3luY1xuICA8L2Rpdj5cbjwvdGVtcGxhdGU+In0=):

- Click on Show Async and wait for it to load
- Click on Show Sync and then Show Async again
- Check the error in the console

Ideally, there should be a way to pin the provided route at the `RouterView` level so all nested routes use the correct version of the route. Something like [this](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgc2hhbGxvd1JlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbiAgaW1wb3J0IFBhcmVudFN5bmMgZnJvbSAnLi9QYXJlbnRTeW5jLnZ1ZSdcbiAgaW1wb3J0IFBhcmVudEFzeW5jIGZyb20gJy4vUGFyZW50QXN5bmMudnVlJ1xuICBpbXBvcnQgQ2hpbGRBc3luYyBmcm9tICcuL0NoaWxkQXN5bmMudnVlJ1xuICBpbXBvcnQgQ2hpbGRTeW5jIGZyb20gJy4vQ2hpbGRTeW5jLnZ1ZSdcbiAgaW1wb3J0IFJvdXRlclZpZXcgZnJvbSAnLi9Sb3V0ZXJWaWV3LnRzJ1xuXG5cdGNvbnN0IHJvdXRlID0gc2hhbGxvd1JlZigpXG4gIHNob3dTeW5jKClcblx0cHJvdmlkZSgncm91dGUnLCByb3V0ZSlcbiAgXG4gIGZ1bmN0aW9uIHNob3dTeW5jKCkge1xuICAgIHJvdXRlLnZhbHVlID0gW1BhcmVudFN5bmMsIENoaWxkU3luY11cbiAgfVxuICBmdW5jdGlvbiBzaG93QXN5bmMoKSB7XG4gICAgcm91dGUudmFsdWUgPSBbUGFyZW50QXN5bmMsIENoaWxkQXN5bmNdXG4gIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd1N5bmNcIj5cbiAgICBTaG93IFN5bmNcbiAgPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwic2hvd0FzeW5jXCI+XG4gICAgU2hvdyBBc3luY1xuICA8L2J1dHRvbj5cbiAgPHA+XG4gICAgQ2xpY2sgb24gU2hvdyBBc3luYyBhbmQgY2hlY2sgdGhlIGNvbnNvbGUuIFRoZSBDaGlsZCBBc3luYyBpcyBtb3VudGVkIHR3aWNlOiBmaXJzdCBieSB0aGUgUGFyZW50U3luYyB3aGljaCBpcyBiZWluZyBkZXRhY2hlZCBieSB0aGUgaW5jb21pbmcgUGFyZW50QXN5bmMgYW5kIGJ5IHRoZSBQYXJlbnRBc3luYyBpdHNlbGYuXG4gIDwvcD5cbiAgPGhyPlxuICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PiAgXG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJQYXJlbnRTeW5jLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG4gIGltcG9ydCBSb3V0ZXJWaWV3IGZyb20gJy4vUm91dGVyVmlldy50cydcbiAgXG5cdGNvbnNvbGUubG9nKCdQYXJlbnQgU3luYyBsb2FkaW5nJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgUGFyZW50IFN5bmNcbiAgICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiQ2hpbGRTeW5jLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5cdGNvbnNvbGUubG9nKCdDaGlsZCBTeW5jIGxvYWRpbmcnKVxuICBcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXY+XG4gICAgQ2hpbGQgU3luY1xuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiUGFyZW50QXN5bmMudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IFJvdXRlclZpZXcgZnJvbSAnLi9Sb3V0ZXJWaWV3LnRzJ1xuICBcblx0Y29uc29sZS5sb2coJ1BhcmVudCBBc3luYyDijJvvuI8gbG9hZGluZycpXG4gIGF3YWl0IG5ldyBQcm9taXNlKHJlc29sdmUgPT4gc2V0VGltZW91dChyZXNvbHZlLCAzMDApKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICBQYXJlbnQgQXN5bmNcbiAgICA8cm91dGVyLXZpZXcgdi1zbG90PVwieyBDb21wb25lbnQgfVwiPlxuICAgIDxTdXNwZW5zZT5cbiAgICAgIDxjb21wb25lbnQgOmlzPVwiQ29tcG9uZW50XCIgLz5cbiAgICA8L1N1c3BlbnNlPlxuICA8L3JvdXRlci12aWV3PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+IiwiUm91dGVyVmlldy50cyI6ImltcG9ydCB7IHByb3ZpZGUsIGluamVjdCwgaCB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgUm91dGVyVmlldyA9IHtcbiAgbmFtZTogJ1JvdXRlclZpZXcnLFxuICBzZXR1cChwcm9wcywgeyBzbG90cyB9KSB7XG5cdFx0Y29uc3Qgcm91dGUgPSBpbmplY3QoJ3JvdXRlJylcbiAgICBjb25zdCBkZXB0aCA9IGluamVjdCgnZGVwdGgnLCAwKVxuICAgIGNvbnN0IGZpeGVkID0gcm91dGUudmFsdWVcbiAgICBcbiAgICBwcm92aWRlKCdkZXB0aCcsIGRlcHRoICsgMSlcbiAgICAvLyBpcyB0aGVyZSBhIHdheSB0byBmaXggdGhlIHByb3ZpZGVkIHRvIHRoZSBjdXJyZW50IHJlbmRlcmVkIHRyZWU/XG4gICAgLy8gcHJvdmlkZSgncm91dGUnLCByb3V0ZSlcbiAgICBcbiAgICByZXR1cm4gKCkgPT4ge1xuICAgICAgY29uc3QgY3VycmVudCA9IGRlcHRoID4gMCA/IGZpeGVkW2RlcHRoXSA6IHJvdXRlLnZhbHVlW2RlcHRoXVxuICAgICAgY29uc29sZS5sb2coJ3JlbmRlcmluZycsIGN1cnJlbnQpXG4gICAgICByZXR1cm4gc2xvdHMuZGVmYXVsdCh7IENvbXBvbmVudDogY3VycmVudCB9KVswXVxuICAgIH1cbiAgfVxufVxuXG5leHBvcnQgZGVmYXVsdCBSb3V0ZXJWaWV3IiwiQ2hpbGRBc3luYy52dWUiOiI8c2NyaXB0IHNldHVwPlxuXHRjb25zb2xlLmxvZygnQ2hpbGQgQXN5bmMg4oyb77iPIGxvYWRpbmcnKVxuICBhd2FpdCBuZXcgUHJvbWlzZShyZXNvbHZlID0+IHNldFRpbWVvdXQocmVzb2x2ZSwgMzAwKSlcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIENoaWxkIEFzeW5jXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==) but that also handles nested routes correctly (I think this workaround wouldn't work when having multiple async children)

**Comment by zigomir** [comment]
We've hit this error in our app too. I tried using `vue-router` with multiple nested `RouterView`s and a `<Suspense>` in the root component.

I'm looking at your linked workaround above (`const current = depth > 0 ? fixed[depth] : route.value[depth]`) and I'm wondering if `vue-router` can be patched or we can only wait for this to be fixed in `vuejs/core`?

**Comment by m430** [comment]
I have same problem. Hope to fix it soon.

**Comment by zigomir** [comment]
Seems like this has been fixed with https://github.com/vuejs/core/pull/6736
I'll take a look and see if I can confirm.
