### ISSUE TITLE
Add ability to suppress scroll behaviour "element not found" warning, so it fails silently

### ISSUE THREAD

**Issue by adamreisnz** [vuejs/router#1326]
### What problem does this feature solve?
I want to use scroll behaviour with support for `{el: to.hash}` as documented, however, in some cases, I am using the hash to determine which tab to open on a page.

In that case, scrolling to an element with a given ID is not required, and there is no need for the warning thrown by vue-router.

I would like to be able to suppress these warnings, so that the scroll fails silently instead.

### What does the proposed API look like?
Possibly as simple as adding a flag to the `createRouter` function:

```
//Scroll behaviour for router
const scrollBehavior = (to, from, savedPosition) => {
  if (to.hash) {
    return {el: to.hash}
  }
  else if (savedPosition) {
    return savedPosition
  }
  return {top: 0}
}
//Create history and router
const history = createWebHistory(process.env.BASE_URL)
const router = createRouter({history, routes, scrollBehavior, suppressScrollError: true})
```

**Comment by posva** [comment]
Just check inside your `scrollBehavior()` function if the element exists with `document.querySelector(to.hash)` before returning a non existant position.

**Comment by adamreisnz** [comment]
Yep, I suppose that can be done, thanks for the tip
