### ISSUE TITLE
Global afterEach Hook Called Even After Cancelling the Navigation

### ISSUE THREAD

**Issue by amxmln** [vuejs/router#1328]
I have a Modal component that uses `onBeforeRouteLeave` to close the modal if its visible instead of navigating:

```js
onBeforeRouteLeave(() => {
  if (props.visible && props.dismissable) {
    emit('close');
    return false;
  }
  return true;
});
```

In the same app, I’m using a global `afterEach` to do some styling of the app depending on the current route. The issue is that when there’s a modal open and the user tries to go back, the modal closes as expected and the navigation is aborted, **but** the styles of the previous route get applied (even though it’s not loaded).

Logging `to` in `afterEach` reveals that the hook runs, despite the navigation being cancelled. This feels like a bug to me.

If it is not, how could I catch that the navigation was aborted in the `afterEach`?

Keep up the great work!

**Comment by posva** [comment]
See https://router.vuejs.org/guide/advanced/navigation-failures.html

**Comment by amxmln** [comment]
Thank you for the link to the article! I wasn’t aware that `afterEach` also received the failure as a third argument. That’s very handy.
