### ISSUE TITLE
can't match   /*

### ISSUE THREAD

**Issue by Qiaoruiwu** [vuejs/router#1331]
### Version
4.0.13

### Reproduction link
[github.com](https://github.com/Qiaoruiwu/vue3-router.git)

### Steps to reproduce
const routes = [
  {
    path: '/',
    name: 'home',
    component: HomeView
  },
  {
    path: '/about',
    name: 'about',
    // route level code-splitting
    // this generates a separate chunk (about.[hash].js) for this route
    // which is lazy-loaded when the route is visited.
    // 异步加载组件
    component: () => import(/* webpackChunkName: "about" */ '../views/AboutView.vue')
  },
  {
    path: '/*',
    redirect: '/',
  }

### What is expected?
http://localhost:8080/aboutaaa    want   redirect    to     http://localhost:8080/

### What is actually happening?
/*     cant't redirect   to  http://localhost:8080/ 
but      Specify a specific path    /aboutaaa  can  redirect to  /

---
version:   
 "vue": "^3.2.13",
    "vue-router": "^4.0.13"

**Comment by posva** [comment]
Pleas read the migration guide, this is documented there.
