### ISSUE TITLE
[vue-router lazy load] View cannot be loaded after network connection is restored

### ISSUE THREAD

**Issue by linhx** [vuejs/router#1333]
### Version
4.0.13

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-router-lazy-load-bhc2r9)

### Steps to reproduce
- Load the home page
- Disconnect internet: F12 > Tab Network > set network throttling to "offline"
- Click link "Test" on the home page
- Reconnect internet: set network throttling to "No throttling"
- Click link "Test" on the root page

### What is expected?
The "Test" page can be loaded

### What is actually happening?
The "Test" page cannot be loaded
Error:
`TypeError: Failed to fetch dynamically imported module: <js file>`

**Comment by posva** [comment]
This looks like a caching issue. Vue Router only calls the dynamic import and reports back the error.

**Comment by linhx** [comment]
For now, I'm catching the exception and then using window.location.href to redirect. The behavior is just like MPA, but I hope there is a better solution that can keep the state of the app.

**Comment by linhx** [comment]
> This looks like a caching issue, unrelated to Vue Router which only calls the dynamic import and reports back the error.

okay, I understand. But the problem is the behavior.
- Lost internet connection
- Click link > nothing happened
- Internet connection has been restored
- Click link > still nothing happened

I think this's a normal case.
I saw that react-router-dom handle this case by let user go to the url but with blank page. At least user know there is something wrong.

**Comment by abrthel** [comment]
We're running into this exact issue in one of our apps. We deal with lots of users who have flaky network connections and unfortunately we can't just hard reload the page on failure because we rely on the current page state and if we navigate at all it causes all sorts of other issues. Think education/scorm environment. 

We have other apps built with vue2 that don't have this issue but I suppose the problem could be connected with Vite. What I do know is that if you lose connection then try to load a route, that route will forever fail to load until you refresh the page and that is a pretty terrible user experience.

**Comment by linhx** [comment]
@abrthel 
Because vue2 adds link prefetching of the view's chunk to the index.html. That makes the view's chunk loaded after the page is loaded.
But Vite does not do that. The view's chunk only load when you access the route.

This is my solution:
```javascript
const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/test',
      component() {
        return import('./views/Test.vue').catch(() => {
          if(navigator.onLine) {
            return import('./views/Test.vue?v=' + new Date().toISOString()); // avoid browser caching
          }
          alert('Please check your internet connection!');
        });
      }
    }
  ]
});
```
But it works perfectly if the chunk of the view does not depend on other module. for example view_A depends on module_B, this is the risk:
![image](https://user-images.githubusercontent.com/50461902/167172757-e3ee9ac5-1833-40eb-badd-0b749d71c6e2.png)

It would be better if the browser didn't cache the failed files.
Another solution is implementing an importing method likes the code above, and replace all of the import method.

**Comment by abrthel** [comment]
Linhx, you are absolutely right and I was thinking about this issue all wrong. I didn't think vite was using js dynamic imports in production builds and just assumed import calls were being re-written during the rollup build process. 

I'll have to investigate your solution more, though I can indeed see scenarios in my own projects where `view_a` could rely on `module_b`. At least I have somewhere to start looking. Thank you!

For anyone else coming to this issue later see:
* https://github.com/whatwg/html/issues/6768
* https://github.com/vitejs/vite/issues/5101

**Comment by cj0x39e** [comment]
I wrote a library to attempt to solve this issue, https://github.com/cj0x39e/retrying-dynamic-import

**Comment by nathnolt** [comment]
Dirty hack to solve it:
`component: () => import('../views/AboutView.vue?r=' + Date.now())`

By adding `?r=' + Date.now()` after the resource, it makes it so the URL is never the same, and thus it will keep retrying it.
