### ISSUE TITLE
Working example app in documentation

### ISSUE THREAD

**Issue by swartchris8** [vuejs/router#1334]
### What problem does this feature solve?
One of the best things about the vue docs are working examples and the tutorial also provides working examples each step.

I found for me to understand vue router a working example would have helped a lot. I propose adding a tiny working example to the vue router docs.

I would be happy to contribute an extremely basic hello world application that showcases how to use the router.

### What does the proposed API look like?
I think the ideal example would showcase a single page application home page on / and would have the components used there also available on their own routes such as /helloworld1 and /helloworld2

**Comment by posva** [comment]
Let's track this at https://github.com/vuejs/router/issues/829

I think that using a simple project with vite might be a better option that the currently existing one with html files, I will share with the doc team.
