### ISSUE TITLE
Add support for dynamic base URL for the web history

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/router#1336]
### What problem does this feature solve?
In our project, the back-end application should render the Vue.js app when the user requests the `/group/:id/module_name` page. Where the :id is a dynamic parameter. But when I pass `/group/:id/module_name`  value to the `createWebHistory` call, the base URL considers as static. Can you add support for dynamic base URLs? Thanks in advance!

### What does the proposed API look like?
Keep the same logic as we have now in terms of base URL within `createWebHistory` function, but add handling the URLs like it is working in the route `path` property.

So in the end, if I do:

```
const router = createRouter({
  history: createWebHistory('/group/:id/module_name'),
  routes: []
})
```
:id is not considered static and then when I request for example `/group/1/module_name` URL, it should render the view.

Please let me know I need to add more details

**Comment by posva** [comment]
This is intentional. Base is meant to be static for deployments.

you can use https://github.com/vuejs/router/pull/1190 to group routes
