### ISSUE TITLE
Adding nested routes  can't add children routes

### ISSUE THREAD

**Issue by afnto** [vuejs/router#1337]
### Version
4.0.14

### Reproduction link
[https://router.vuejs.org/](https://router.vuejs.org/)

### Steps to reproduce
router.addRoute({ name: "admin", path: "/admin", component: HomeView });
router.addRoute('admin', {name:'settings', path: '/settings', component: HomeView })

### What is expected?
```
{
    name: "admin",
    path: "/admin",
    component: HomeView,
    children: [
      {
        name: "settings",
        path: "/settings",
        component: HomeView,
        children: [
          {
            name: "admin1",
            path: "/admin1",
            component: HomeView,
          },
        ],
      },
    ],
  }
```
### What is actually happening?
use "router.addRoute('admin', { path: 'settings', component: AdminSettings })"  can't add children routes

**Comment by posva** [comment]
not a valid repro.
