### ISSUE TITLE
Router-links stopped working in 4.0.14 

### ISSUE THREAD

**Issue by ansbar** [vuejs/router#1338]
### Version
4.0.14

### Reproduction link
[jsfiddle.net/posva/3yq6ojLv/5](https://jsfiddle.net/posva/3yq6ojLv/5)

### Steps to reproduce
Add a normal router-link with a to-value and try to click it.

### What is expected?
To change page

### What is actually happening?
Nothing

---
I don't know how to use a specific version in jsfiddle so I cant reproduce it there =/

If I switch from 4.0.13 to 4.0.14 they stop working. The link renders fine but nothing happens when clicking it.

We're using SSR and "vue": "^3.2.31" and "vite": "^2.8.6"

**Comment by posva** [comment]
I can't reproduce. Do you have more info?

**Comment by sbscan** [comment]
@ansbar check console. If you get api.now() error, you can switch to 4.0.13

**Comment by LinusBorg** [comment]
That's from the Vue devtools plugin. And only happens if you are still on the beta. 

Happened to me today when checking in another browser that still was on the 6.0 beta version instead of the stable one we released recently.

**Comment by sbscan** [comment]
@LinusBorg should be, I can't confirm because can't always reproduce the bug.
Now switched to stable. If no bug all day, I'll comment here.

**Comment by posva** [comment]
Maybe it’s worth gracefully handle it somewhere. It could also serve as a hint to make users upgrade their devtools version 🙂

**Comment by josetanta** [comment]
I have same problem 
![image](https://user-images.githubusercontent.com/57731864/158114303-ca8c6f2d-5cdf-43fb-9fb6-00e26e6cc7d8.png)

**Comment by ansbar** [comment]
I can confirm uninstalling devtools beta (6.0.0.23?) and running 6.1.0 instead solved this issue.
Thank you @LinusBorg

**Comment by mdunisch** [comment]
same here, switch from beta to stable version of the vue dev tools help!

**Comment by awacode21** [comment]
I am having the same problem with same vue-router version 4.0.14 but without any errors on dev tools console. There is nothing logged, but the router links simply are not working. No feedback. Will try to uninstall and install again the dev tools. Try to confirm if that helps.

**Comment by awacode21** [comment]
i can confirm the error is gone after updating to stable devtools.

**Comment by Hisioni** [comment]
![image](https://user-images.githubusercontent.com/38490508/160549982-fe3b2513-eee1-44fc-9b77-a008db3238c6.png)
same, Ver: 4.0.14

**Comment by DZ8540** [comment]
I'm also have a problem, i use useRouter in composition api, but it throwed error below(

![изображение](https://user-images.githubusercontent.com/50152205/161428071-827802d3-8207-4a73-93fe-f4a907dfe083.png)

**Comment by li-jingxuan** [comment]
This is a bug with "vue devtools 6.0.0 bate", Install the new version to solve

**Comment by lianghan911** [comment]
把vue-router的版本换为4.0.10就可以了

**Comment by zjfresh** [comment]
https://github.com/vuejs/router/blob/87d09f81ba11a9153af45836f4b10a5736257cae/src/RouterLink.ts#L145

**Comment by zjfresh** [comment]
> I am having the same problem with same vue-router version 4.0.14 but without any errors on dev tools console. There is nothing logged, but the router links simply are not working. No feedback. Will try to uninstall and install again the dev tools. Try to confirm if that helps.

I have the same problem(the beta devtool, and firstly need to open DevTools Vue panel ).  It's caused by the code behind:

https://github.com/vuejs/router/blob/87d09f81ba11a9153af45836f4b10a5736257cae/src/RouterLink.ts#L138-L148

https://github.com/vuejs/router/blob/87d09f81ba11a9153af45836f4b10a5736257cae/src/utils/index.ts#L26

Update the node_modules/vue-router/dist/vue-router.esm-bundler.js ``const noop = () => { };`` to ``const noop = (err) => { console.error(err)};``, the error that took me hours finally was showed in console!!

![image](https://user-images.githubusercontent.com/28496323/164389494-7c2d605d-b553-48bd-91e5-596cffde8687.png)

**Comment by DarcyNing** [comment]
Thanks guys, too much appreciate for all your comment.  it's a fantastic community.
I have tried and it works.  

Step 1:
Change router/index.js from:
`const router = createRouter({
    history: createWebHashHistory(),
    routes
})

export default router`
to 
`export const router = createRouter({
    history: createWebHashHistory(),
    routes
})
`
Step 2:
Change main.js from 
`import router from './router'`
to
`import { router  } from './router'`

Step 3:
Run command  `yarn serve` will see the issue fixed.

Step4:
Change all code back. the issue will not back.

**Comment by b-avb** [comment]
The same problem using `"vue-router": "^4.0.13"`

**Comment by 0106WeiWeiDeng** [comment]
I got a similar problems with `"vue-router": "^4.0.14"`.  When I add new router-link and click it, all the links would fail(got black pages). The chrome console errors are :

1)
```
warn2 @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:3740 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:3740:17)
    at Proxy._sfc_render (scST_qc.vue:136:15)
    at renderComponentRoot (runtime-core.esm-bundler.js:895:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5059:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at setupRenderEffect (runtime-core.esm-bundler.js:5185:9)
    at mountComponent (runtime-core.esm-bundler.js:4968:9)
    at processComponent (runtime-core.esm-bundler.js:4926:17)
    at patch (runtime-core.esm-bundler.js:4518:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5136:17)
```
2)

```
runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5138:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:36)
    at flushJobs (runtime-core.esm-bundler.js:394:17)
```

**Comment by posva** [comment]
This will warn as it does in pina in 4.1 to help people notice the issue 🙂
