### ISSUE TITLE
 route.fullPath's query is not similar with route.query

### ISSUE THREAD

**Issue by shenX-2021** [vuejs/router#1342]
### Version
4.0.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/query-bug-mzlml1?file=/src/App.vue)

### Steps to reproduce
1. click "About" button
2. watch the Console Dev
3. you can see the fullPath's query is not similar with the query prop

### What is expected?
the fullPath's query is similar with the query prop

### What is actually happening?
the fullPath's query is not similar with the query prop

**Comment by posva** [comment]
`route.query` is decoded: https://router.vuejs.org/guide/migration/#route-properties-encoding
