### ISSUE TITLE
got error api.now is not a function when called router.push() and vue devtools panel is opened

### ISSUE THREAD

**Issue by saatana97** [vuejs/router#1345]
### Version
4.0.14

### Reproduction link
[github.com](https://github.com/vuejs/router/issues)

### Steps to reproduce
open vue devtools
call router.push()

### What is expected?
navigate to my route page

### What is actually happening?
Uncaught (in promise) TypeError: api.now is not a function

---
I saw replace Date.now() to api.now() in latest version

**Comment by dhi2** [comment]
Me too.

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
