### ISSUE TITLE
Can parameters be made mor powerful by accepting objects?

### ISSUE THREAD

**Issue by patchthecode** [vuejs/router#1347]
### What problem does this feature solve?
To pass data from one view to another view on a router URL change, we use parameters.
But this seems to only pass [String:String] string values.   Is there a way to pass object values?

The issue is that we already pass data from one view to another, therefore the restriction that it can only be string value type seems like a limiting restriction. 

I wish to pass data to another view, but i have to flatten the objects first into Key:String Value:Sting just every where, and then reassemble it back on the other side.

I think this feature can be a trivial change with no side effects as it is up to the developer to determine what parameters is sent over.

### What does the proposed API look like?
router.push({name: my_route, parameters: { what ever object i want instead of string:string only} }

**Comment by posva** [comment]
params **must be** in the url, so they have to be strings. You can serialize them to strings but I wouldn't recommend to store complex state in them, they are not meant for that

**Comment by patchthecode** [comment]
I do not understand.

I use 
```
router.push(name, params)
```

They do not appear in the url at all.
But, if params are the wrong place to do it, then is there a better way pass objects to new views using the `router.push()` command?

If there isnt one, then is this a good use case to create an upgrade to do it?

**Comment by WeaverOfTheWeb** [comment]
I assumed Params were like POST headers so they shouldn't have anything to do with the URL and its limitation in length, where as this would apply to query? It just seems odd that you can no longer provide param properties with object values when you could in the past - [CodeSandbox example](https://codesandbox.io/s/vigorous-joji-b0zjfd?file=/src/views/Home.vue).

It took me forever to realise that the latest Vue Router allows you to only assign string values so I'm having to now stringify and then parse them back to objects when this never used to be the case. Another [CodeSandbox example](https://codesandbox.io/s/cocky-allen-3op605?file=/src/views/Home.vue) with this in place for Vue3/Vue Router 4.

**Comment by WeaverOfTheWeb** [comment]
Understandably it confuses a lot of people as you once could provide param properties with object values - [CodeSandbox example](https://codesandbox.io/s/vigorous-joji-b0zjfd?file=/src/views/Home.vue).

Due to the internet being littered with old code it took me a while to realise that the latest Vue Router only allows string values so you now have to stringify and then parse them back to objects. Another [CodeSandbox example](https://codesandbox.io/s/cocky-allen-3op605?file=/src/views/Home.vue) with this in place for Vue3/Vue Router 4.
