### ISSUE TITLE
Cannot read property '__vccOpts' of undefined

### ISSUE THREAD

**Issue by jimhucksly** [vuejs/router#1349]
### Version
4.0.14

### Reproduction link
[gitlab.com](https://gitlab.com/jimhucksly/pitertour/-/tree/master)

### Steps to reproduce
npm i
npm run dev

### What is expected?
localhost:4000 is work fine!

### What is actually happening?
Error in terminal

"TypeError: Cannot read property '__vccOpts' of undefined
    at D:\pitertour\node_modules\vue-router\dist\vue-router.cjs.js:2026:55"

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-router#why-repro when reporting a bug. In this case, no Nuxt would help. Open a new issue if you manage to reproduce it without Nuxt.

**Comment by jimhucksly** [comment]
Great! I must create a reproduction without nuxt, without webpack, without vue, without ....
