### ISSUE TITLE
跳转的 path 后面带的参数丢失

### ISSUE THREAD

**Issue by zhujunel** [vuejs/router#1352]
### Version
4.0.14

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/zh/guide/migration/index.html#route-%E5%B1%9E%E6%80%A7%E7%BC%96%E7%A0%81)

### Steps to reproduce
router.beforeEach((to, from, next) => {
next({
                name: "login",
                query: {
                    redirect: encodeURIComponent(to.fullPath),
                },
});
}

// login-登录成功后
const { redirect } = route.query;
router.push({
    path: decodeURIComponent(redirect),
});

能跳转成功，路由名后参数丢失。
比如：
/detail?id=123变成了/detail

### What is expected?
期望能带上参数

### What is actually happening?
?后的参数丢失

**Comment by zhujunel** [comment]
已解决

**Comment by jianshe** [comment]
@zhujunel 请问，如何解决的，我是遇到，中间有一次query参数被替换为空，然后最终参数能正确传递的问题。
![image](https://user-images.githubusercontent.com/5591588/164601448-e6b05170-bcef-402a-bdf1-5ee42bb2f529.png)

**Comment by fuguxu** [comment]
请问怎么解决的，router.push({path : `/front/ai/taskAdd?id=3`})，也出现参数丢失的问题

**Comment by heroboy** [comment]
`path`是不带query的，`fullPath`是带query的。
所以`to.fullPath`有query部分，而`router.push({path: '/a?b=c'})`忽略了query部分。
应该使用`router.push('/a?b=c')`，或者`router.push({path:'', query:{} })`
