### ISSUE TITLE
Strange behavior when prop is passed in chain through <router-view />

### ISSUE THREAD

**Issue by vuphuctho** [vuejs/router#1354]
### Version
4.0.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/peaceful-noether-u6gce8)

### Steps to reproduce
In sample app, we have this router with 3 level of views: Home > First Child > Second Child. Home and FirstChild both pass props `value` to its children `router-view`:

```
// Home
<template>
  <router-view :value="1" />
</template>

// FirstChild
<template>
  <router-view :value="2" />
</template>
```

### What is expected?
Children of FirstChild (SecondChild) should pick up prop value from its immediate parent, so `value` should be 2

### What is actually happening?
`value` is picked up from Home (ancestor route), not FirstChild

---
Strangely enough, if we wrap div around `router-view` in FirstChild, the value is correctly passed
```
<template>
  <div>
    <router-view :value="2" />
  </div>
</template>
```
Even stranger is that if we just add a commend block in FirstChild, the value is also correctly passed
```
<template>
  <router-view :value="2" />
  <!-- Adding this is enough to change behavior -->
</template>
```

**Comment by posva** [comment]
This is because components [inheritAttrs by default](https://vuejs.org/api/options-misc.html#inheritattrs). That's why wrapping or using a fragment solves the problem. You can also just disable that option for your view components.
