### ISSUE TITLE
The value of `router.currentRoute.value.fullPath` is `/`

### ISSUE THREAD

**Issue by likecreep** [vuejs/router#1355]
### Version
4.0.14

### Reproduction link
[jsfiddle.net/m0a3o2pt/](https://jsfiddle.net/m0a3o2pt/)

### Steps to reproduce
use `router.currentRoute.value.fullPath` in `main.js`

### What is expected?
the value of `router.currentRoute.value.fullPath`  is the current url.

### What is actually happening?
the value of `router.currentRoute.value.fullPath`  is `/`.

---
```js
setTimeout(() => {
  console.log(router.currentRoute.value.fullPath)
}, 50)
```  
can get the correct url, 
but 
```js
setTimeout(() => {
  console.log(router.currentRoute.value.fullPath)
}, 0)
``` 
still get `/` as the result.
Is this a bug or how to get the correct result instantly?

**Comment by posva** [comment]
As explained in other issues, because navigations are async, in the beginning, the current location is a nowhere state.

**Comment by candy-Tong** [comment]
The Doc say that we can use `router.replace(router.currentRoute.value.fullPath)` to trigger navigation that make addRoute work
[https://router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes](https://router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes)

```typescript
router.addRoute({ path: '/about', component: About })
// 我们也可以使用 this.$route 或 route = useRoute() （在 setup 中）
router.replace(router.currentRoute.value.fullPath)
```

However, if we use `router.currentRoute.value.fullPath` in the beginning, the `router.currentRoute.value.fullPath` is `/`.
This will cause a problem that all url will be redirected to `/`
How to deal with this problem ?
