### ISSUE TITLE
[Vue warn]: Unhandled error during execution of render function

### ISSUE THREAD

**Issue by johan8863** [vuejs/router#1356]
### Version
4.0.14

### Reproduction link
[github.com](https://github.com/johan8863/vue-routes)

### Steps to reproduce
click the link which says "Por Id" and see the console output, or just add to the url /pokemon/pokemonid/150, the final number can be changes of course

### What is expected?
the console not to complain

### What is actually happening?
The application is orking just fine, but the console throws warnings and one error

---
If I can be informed to this mail  - jtravieso8863@gmail.com I'll be grateful

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You probably need to remove the `a` tag from https://github.com/johan8863/vue-routes/blob/main/src/modules/shared/components/CustomLink.vue#L14. More info at https://router.vuejs.org/api/#router-link-s-v-slot
