### ISSUE TITLE
How to pass props to an component rendering via RouterView?

### ISSUE THREAD

**Issue by MaddyCrowle** [vuejs/router#1361]
### Version
4.0.14

### Reproduction link
[codepen.io](https://codepen.io/maddycrowle/pen/yLpjdwQ)

### Steps to reproduce
Copy this little code and put it in any Vue3 component.

### What is expected?
Prop is passing to children component.

### What is actually happening?
Extraneous non-props attributes (product) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

---

I have code like:
```

<template>
 <router-view :an-prop="product" />
</template>
<script setup lang="ts">

...

const product: Ref<IProduct|undefined>: ref();

...

</script>
```

I need to pass product as a prop to the component which loads in router-view.

Some time ago it was possible just like `<router-view :an-prop="product" />`, but since new version of Vue was released I've got warning:

> Extraneous non-props attributes (product) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

Maybe I'm blind, but I honestly didn't find anything about it in the official documentation, only trivial examples of using <router-view> and billions of trivial examples of using vue-router programmatically. After hours of experiments and studies search engines' results I found out that now router-view uses slots and end up with such code:

```
<router-view v-slot="{ Component }">
 <component :is="Component" />
</router-view>
```

Which gave me not much, actually. Anyway I don't understand what to do next. Is there any way to pass props to an component rendering via RouterView nowadays in vue3?

**Comment by LinusBorg** [comment]
You do it by passing props to the component, literally:
```js
<router-view v-slot="{ Component }">
 <component :is="Component" your-prop="your-value" />
</router-view>
```

**Comment by LinusBorg** [comment]
I reopen this as we should document his I think

**Comment by MaddyCrowle** [comment]
> You do it by passing props to the component, literally:
> 
> ```js
> <router-view v-slot="{ Component }">
>  <component :is="Component" your-prop="your-value" />
> </router-view>
> ```

Sure, I tried it first, but unfortunately it throws the same warning 

> Extraneous non-props attributes (product) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

Otherwise I wouldn't ask such a question.

**Comment by posva** [comment]
It’s because some of your views don’t have that prop declared probably.

PR welcome to add a note in the API section

**Comment by MaddyCrowle** [comment]
> It’s because some of your views don’t have that prop declared probably.

I checked several times, child component, rendering in router-view, 100% has that prop, but defined in "setup style" like:

```
const props = defineProps({
 product: {
  type: Object as PropType<IProduct>,
  default: {}
 }
});
```
can it cause described issue?

**Comment by LinusBorg** [comment]
> Otherwise I wouldn't ask such a question.

Well, I couldn't have known.

> can it cause described issue?

No. You would need to provide more info.

**Comment by MaddyCrowle** [comment]
> Does your router only have this one route? so it will only render this one component which has a `product` prop?

My router has many routes, only one has `product` property. I started new empty project from the scratch for the experiments, and here is what I found out:

App.vue
```
<template>
    APP
    <router-view v-slot="{ Component, route }">
        <transition name="fade">
            <component :test-prop="123" :is="Component" :key="route.path" />
        </transition>
    </router-view>
    <router-link :to="{ name: 'Test1' }">page 1</router-link>
    <router-link :to="{ name: 'Test2' }">page 2</router-link>
</template>
```

Test1
```
<template>
<div>
            <h1>Test 1 page</h1>
            this is test text
</div>
</template>
```

Test2
```
<template>
    <div style="position: absolute;">
        <h1>Test 2 page</h1>
    </div>
</template>
```

1. If Test1 has property `testProp` and between `<template>` and `</template>` only 1 parent tag - no warning, even if Test2 doesn't have property `testProp`;
2. If between `<template>` and `</template>` only 1 parent tag and Test1 and Test2 both don't have property `testProp` - no warning;
3. If one of the components which going to be loaded in router-view has more than 1 parent tags between `<template>` and `</template>`, for example:
```
<template>
    <div style="position: absolute;">
        <h1>Test 2 page</h1>
    </div>
    <div>just footer</div>
</template>
```
, no matter if they have or not property `testProp`, - causes the mentioned warning:
```
Extraneous non-props attributes (test-prop) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Test2 onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > test-prop=0  ... > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="fade" > 
  at <RouterView> 
  at <App>
```

Is it expected behavior? I thought `<template>` already counts as root element during rendering.

**Comment by MohammadArefHaidary** [comment]
in

**Comment by pei-han** [comment]
the document of vue-router is sucked.
i can not find anything about component element at all.

**Comment by AlejandroPaez1** [comment]
The same thing happens to me, I want to pass a text through
                 <router-view ref="mapComponent" :myProp="myData" ></router-view>

and nothing happens, it does not send

**Comment by sh-at-cs** [comment]
The paragraph that was added in https://github.com/vuejs/router/commit/5ad486473eb7f5bbcdbc721b13b1373bc3a8f6df seems to have been removed from the docs again :-/

**Comment by Payn** [comment]
> You do it by passing props to the component, literally:
> 
> ```js
> <router-view v-slot="{ Component }">
>  <component :is="Component" your-prop="your-value" />
> </router-view>
> ```

This doesn't work. Passed prop still produces error in component saying it's undefined.
