### ISSUE TITLE
A warning appeared when passing a base path includes '#' to function createWebHashHistory

### ISSUE THREAD

**Issue by vjguo** [vuejs/router#1362]
### Version
4.0.14

### Reproduction link
[github.com](https://github.com/vuejs/router/blob/main/src/history/hash.ts#L39)

### Steps to reproduce
call createWebHashHistory like createWebHashHistory('/#/app')

### What is expected?
No warning.

### What is actually happening?
A warning appeared:
[Vue Router warn]: A hash base must end with a "#":
"/#/app" should be "/#".

**Comment by vjguo** [comment]
I saw there is a commit(ae8b28934b1c9a092174ebd6fb5aa10aefe1de44) that create a warning if to do so.
But I have no idea and this looks like a standard usage on the official website. Will anything goes wrong in this way？

**Comment by posva** [comment]
You need to fix it like the warning said
