### ISSUE TITLE
Vue router Back button leads to the wrong savedPosition

### ISSUE THREAD

**Issue by cabronara** [vuejs/router#1363]
### Version
4.0.13

### Reproduction link
[https://www.test.timetip.app/](https://www.test.timetip.app/)

### Steps to reproduce
1. Scroll down a bit on the page
2. Click any Picture or Button that leads you to another route
3. Click the back button

### What is expected?
Router should lead back to the exact same position

### What is actually happening?
Router leads back to a slightly different position

---
My router configuration:

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes,
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) { return savedPosition }
    else {return { top: 0, behavior: 'instant' }}
  }
})

If I remove the part "else {return { top: 0, behavior: 'instant' }}" then the back button behavior works fine. But I need the instant scroll behavior if I click on a next page.
What could be the issue here?

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro when reporting a bug. Most bugs should be reproducible with the [SFC Playground](https://sfc.vuejs.org).
