### ISSUE TITLE
<router-view> Props route:undefined

### ISSUE THREAD

**Issue by Ryongyon** [vuejs/router#1364]
### Version
4.0.14

### Reproduction link
[router.vuejs.org/zh/api/#route](https://router.vuejs.org/zh/api/#route)

[![LAwQln.png](https://s1.ax1x.com/2022/04/10/LAwQln.png)](https://imgtu.com/i/LAwQln)

### Steps to reproduce
-

### What is expected?
route: RouteLocationNormalized

### What is actually happening?
route: undefined

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
