### ISSUE TITLE
Load route meta synchronously on lazy loaded routes

### ISSUE THREAD

**Issue by Soviut** [vuejs/router#1366]
### What problem does this feature solve?
In my app I have a few public-facing pages that hide the site's "chrome" (header, navbar, etc.). I used an optional meta variable to hide those elements. However, when I made the pages lazy load I got a "flash of chrome" because the meta variable is unset while the route loads async, then flips to being set when it's loaded.

### What does the proposed API look like?
It would be nice if the meta loaded synchronously even if the component is lazy loaded.

**Comment by posva** [comment]
meta is loaded whenever a route is loaded, it cannot be off-sync. This is something you will have to handle on userland for your specific case.
