### ISSUE TITLE
`vm` arg in `next` callback in `beforeRouteEnter` there is an inconsistent result with <script setup>

### ISSUE THREAD

**Issue by richex-cn** [vuejs/router#1367]
### Version
4.0.14

### Reproduction link
https://codesandbox.io/s/issue-vue3-router-beforerouteenter-q81re4
https://github.com/richex-cn/issue-vue-router-beforeRouteEnter

### Steps to reproduce

Open reproduction links, and open console to view result.

In the [previous reproduction](https://codesandbox.io/s/issue-vue3-router-beforerouteenter-q81re4), The result as follows:

```javascript
<script>
export default {
  beforeRouteEnter: (to, from, next) => {
    console.log("home beforeRouteEnter");
    next((vm) => {
      console.log("vm.now", vm.now); // undefined
      vm.$nextTick(() => {
        console.log("vm.now", vm.now); // undefined
      });
      vm.$nextTick(function () {
        console.log(this === vm); // true
        console.log("this.now", this.now); // undefined
        console.log("this.getName", this.getName); // undefined
      });
    });
  },
};
</script>

<script setup>
import { ref } from "vue";

console.log("home setup");

const now = ref(Date.now());
const getName = () => "Vue";
</script>
```

In the [second example](https://github.com/richex-cn/issue-vue-router-beforeRouteEnter), The result as follows:

```javascript
<script lang="ts">
export default {
  beforeRouteEnter: (to, from, next) => {
    console.log('home beforeRouteEnter')
    next(vm => {
      console.log('vm.now', vm.now) // undefined
      vm.$nextTick(() => {
        console.log('vm.now', vm.now) // undefined
      })
      vm.$nextTick(function () {
        console.log(this === vm) // false
        console.log('this.now', this.now) // 1649657580119
        console.log('this.getName', this.getName) // () => "Vue"
      })
    })
  }
}
</script>

<script lang="ts" setup>
import { ref } from 'vue'

console.log('home setup')

const now = ref(Date.now())
const getName = () => 'Vue'
</script>
```

If you remove `<script setup>`, all of them are normal, You can view the `detail.vue` file of two reproductions.

### What is expected?
Keep consistent result

### What is actually happening?
Got inconsistent result

---

BTW, The current beforeRouteEnter and TypeScript don't seem to work together. Some related issues:
https://github.com/vuejs/vue-router/issues/1863
https://github.com/vuejs/router/issues/701

**Comment by posva** [comment]
Unfortunately this is inherent to how script setup works. You need to use `defineExpose()` if you want to use `this.now` and others. See the [generated JS code](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBsYW5nPVwidHNcIj5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgYmVmb3JlUm91dGVFbnRlcjogKHRvLCBmcm9tLCBuZXh0KSA9PiB7XG4gICAgY29uc29sZS5sb2coJ2hvbWUgYmVmb3JlUm91dGVFbnRlcicpXG4gICAgbmV4dCh2bSA9PiB7XG4gICAgICBjb25zb2xlLmxvZygndm0ubm93Jywgdm0ubm93KSAvLyB1bmRlZmluZWRcbiAgICAgIHZtLiRuZXh0VGljaygoKSA9PiB7XG4gICAgICAgIGNvbnNvbGUubG9nKCd2bS5ub3cnLCB2bS5ub3cpIC8vIHVuZGVmaW5lZFxuICAgICAgfSlcbiAgICAgIHZtLiRuZXh0VGljayhmdW5jdGlvbiAoKSB7XG4gICAgICAgIGNvbnNvbGUubG9nKHRoaXMgPT09IHZtKSAvLyBmYWxzZVxuICAgICAgICBjb25zb2xlLmxvZygndGhpcy5ub3cnLCB0aGlzLm5vdykgLy8gMTY0OTY1NzU4MDExOVxuICAgICAgICBjb25zb2xlLmxvZygndGhpcy5nZXROYW1lJywgdGhpcy5nZXROYW1lKSAvLyAoKSA9PiBcIlZ1ZVwiXG4gICAgICB9KVxuICAgIH0pXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zb2xlLmxvZygnaG9tZSBzZXR1cCcpXG5cbmNvbnN0IG5vdyA9IHJlZihEYXRlLm5vdygpKVxuY29uc3QgZ2V0TmFtZSA9ICgpID0+ICdWdWUnXG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=) and you will see nothing is returned inside setup.
