### ISSUE TITLE
ScrollBehavior not restoring savedPosition on routes with suspense and top level await

### ISSUE THREAD

**Issue by Soviut** [vuejs/router#1369]
### Version
4.0.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/awesome-wood-i8wjjj)

### Steps to reproduce
- wrap `<router-view>` in `<suspense>`
- create a route with a `<script setup>` page that does not have a top level `await`
- create a route with a `<script setup>` page that has a top level `await`
- setup `scrollBehavior` in router
```typescript
  scrollBehavior(to, from, savedPosition) {
    return savedPosition ?? { left: 0, top: 0 }
  },
```
- navigate to the route without async
- navigate to the route with async
- scroll down the page
- use back/forward buttons
- notice the route with async returns to top

### What is expected?
routes should restore their `savedPosition`

### What is actually happening?
page is scrolling to top

**Comment by posva** [comment]
Unfortunately, this is expected until Suspense is integrated into the navigation flow (which is something currently being worked on). The navigation ends and the scroll behavior triggers while the About page is still not rendered. You could work around it by awaiting the suspense to finish within the scrollBehavior function.

**Comment by 719media** [comment]
Can you provide an example of a reasonable way to await the suspense from within scrollBehavior?

**Comment by Soviut** [comment]
@719media this is a closed issue. If you have a reproducible issue you should open a new ticket.

**Comment by 719media** [comment]
I just thought the proposed workaround was not trivial, and curious if there was an example. In my opinion, most coming to this ticket would probably have the same thought, so I was just looking to see if there was any available example.

having scrollBehavior able to handle a suspense loader is part of the solution, but when going to a new route that utilizes the same component structure will not cause the suspense to drop into a pending state again, so it's only a partial fix. Some solutions would involve using a "unique key=" attribute for the RouterView, but this has drawbacks, etc. etc. Anyway, this could be drawn out, or I thought maybe there is a nice community solution out there. Unfortunately, I don't think there is.

Thanks!
