### ISSUE TITLE
hash模式下，query在hash前无法获取到

### ISSUE THREAD

**Issue by mcck** [vuejs/router#1374]
### Version
4.0.14

### Reproduction link
[http://demo.heyj.top/](http://demo.heyj.top/)

### Steps to reproduce
点按钮查看

### What is expected?
query在hash前还是后都能获取到

### What is actually happening?
query在hash前无法获取参数

---
如果hash在前query在后，如：http://localhost:8090/#/login?query=121
使用浏览器的 location.search 也是获取不到，java中的URL类也一样，不知道这个是bug还是设计如此？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
