### ISSUE TITLE
Using router-link without "to" attribute gives unclear error

### ISSUE THREAD

**Issue by victorberland** [vuejs/router#1377]
### Version
4.0.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-router-4-reproduction-forked-burbqj?file=/index.html)

### Steps to reproduce
See line 13 where i have added "<router-link>Test</router-link>".

### What is expected?
Either, the link can render normally without an error (just like a regular anchor tag without the href attribute), or at least give a more useful error message.

### What is actually happening?
The console prints "Uncaught TypeError: right-hand side of 'in' should be an object, got undefined". This may for new Vue users lead to confusion.

By looking closer at the error, it seems to be related to the line "if ('path' in rawLocation) {" in my bundled js.

**Comment by victorberland** [comment]
It seems like the `if ('path' in rawLocation) {` line appears on line 462 in `src/router.ts`

**Comment by posva** [comment]
Always look at the first error/warning first:

```
[Vue warn]: Missing required prop: "to" 
  at <RouterLink> 
  at <App> 
```

**Comment by victorberland** [comment]
Apologies, my bad.
Wouldn't it make more sense to handle the warning a bit better instead of throwing an error?
