### ISSUE TITLE
active-class prop works like exact-active-class

### ISSUE THREAD

**Issue by frbuceta** [vuejs/router#1379]
### Version
4.0.14

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/github-u2sqdh-pxek8u)

### Steps to reproduce
In the example you can see that in the route `/` both are applied but in the route `/123` neither is applied

### What is expected?
In the route `/` `exact-active-class` should be applied when it is defined if not apply `active-class` and in the route `/123` only `active-class` should be applied

### What is actually happening?
Doesn't work as expected

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

See https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link
