### ISSUE TITLE
Export `NavigationGuardReturn` type

### ISSUE THREAD

**Issue by salazarr-js** [vuejs/router#1388]
### What problem does this feature solve?
trying to make some route guards type safe found that `NavigationGuardReturn` type on `vue-router.d.ts` is not exported

```ts
declare type NavigationGuardReturn = void | Error | RouteLocationRaw | boolean | NavigationGuardNextCallback;
```

### What does the proposed API look like?
it would be nice if `NavigationGuardReturn` is correctly exported so we can use it to define route guards types

```ts
import type { NavigationGuardReturn, RouteLocationNormalized } from 'vue-router'

/** Route guard function type */
export type RouteGuard = (to: RouteLocationNormalized, from: RouteLocationNormalized) => Promise<NavigationGuardReturn>
```

**Comment by posva** [comment]
Note you already have a route guard type, it's `NavigationGuard`. Is there anything not doable with that type or `ReturnType<NavigationGuard>`?

**Comment by salazarr-js** [comment]
@posva  you're complety  right the `NavigationGuard` works perfectly, i didn't see it before 🤯

I ended refactoring my `RouteGuard`

```ts
import type { NavigationGuard, RouteLocationNormalized } from 'vue-router'

/** Route guard context param model */
export interface RouteGuardContext {
  to: RouteLocationNormalized
  from: RouteLocationNormalized
}

/** Route guard function type */
export type RouteGuard = (ctx: RouteGuardContext) => ReturnType<NavigationGuard>
```

so this way i can destructuring the `ctx` and avoid [eslint `no-unused-vars`](https://eslint.org/docs/rules/no-unused-vars) error on guards that don't use all the args, and don't messing up with [next()](https://router.vuejs.org/guide/advanced/navigation-guards.html#optional-third-argument-next) funct
