### ISSUE TITLE
Cannot install vue-router in other vue plugin

### ISSUE THREAD

**Issue by daoxincc** [vuejs/router#1390]
### Version
4.0.15

### Reproduction link
[www.npmjs.com](https://www.npmjs.com/package/nirvana-js-sdk)

### Steps to reproduce
I created a new vue plugin. and I add "vue-router": "^4.0.15" in my vue plugin dependencies.
1. I use  app.install(Router) in my install function.
2. pnpm link my-vue-plugin
3.startup vue project

then I got a warn and a error

[Vue warn]: injection "Symbol([vue-router]: router)" not found. 

app.js:79 Uncaught TypeError: Cannot read properties of null (reading 'parent')
    at warnDeprecatedUsage (nirvana-js-sdk.esm-bundler.js?38c5:3096:1)
    at setup (nirvana-js-sdk.esm-bundler.js?38c5:2984:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?8f05:155:1)
    at setupStatefulComponent (runtime-core.esm-bundler.js?8f05:7109:1)
    at setupComponent (runtime-core.esm-bundler.js?8f05:7063:1)
    at mountComponent (runtime-core.esm-bundler.js?8f05:4951:1)
    at processComponent (runtime-core.esm-bundler.js?8f05:4926:1)
    at patch (runtime-core.esm-bundler.js?8f05:4518:1)
    at mountChildren (runtime-core.esm-bundler.js?8f05:4714:1)
    at processFragment (runtime-core.esm-bundler.js?8f05:4885:1)

the getCurrentInstance() return null?

```js
function warnDeprecatedUsage() {
    const instance = getCurrentInstance();
    const parentName = instance.parent && instance.parent.type.name;
    if (parentName &&
        (parentName === 'KeepAlive' || parentName.includes('Transition'))) {
        const comp = parentName === 'KeepAlive' ? 'keep-alive' : 'transition';
        warn(`<router-view> can no longer be used directly inside <transition> or <keep-alive>.\n` +
            `Use slot props instead:\n\n` +
            `<router-view v-slot="{ Component }">\n` +
            `  <${comp}>\n` +
            `    <component :is="Component" />\n` +
            `  </${comp}>\n` +
            `</router-view>`);
    }
}

```
### What is expected?
use vue-router in my vue plugin has worked

### What is actually happening?
the getCurrentInstance() return null

but app._context.provides contains key 'Symbol([vue-router]: router)'

**Comment by posva** [comment]
vue-router must be a peer dependency, like vue. You can see more explanations of what to do in Vue repository. I personally use yalc to handle this.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by daoxincc** [comment]
> vue-router must be a peer dependency, like vue. You can see more explanations of what to do in Vue repository. I personally use yalc to handle this.
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

it's worked .thank u  :)

**Comment by mandarino-x** [comment]
How npm handles this

**Comment by mandarino-x** [comment]
> > vue-router 必须是对等依赖项，如 vue。你可以在 Vue 存储库中看到更多关于做什么的解释。我个人使用 yalc 来处理这个问题。
> > 记得使用[论坛](http://forum.vuejs.org/)或[Discord 聊天](https://vue-land.js.org/)来提问！
> 
> 它的工作。谢谢你:)

pnpm 如何处理这个

**Comment by mandarino-x** [comment]
> > vue-router 必须是对等依赖项，如 vue。你可以在 Vue 存储库中查看更多关于什么的解释。我个人 yalc 来处理这个。
> > 记得使用[论坛](http://forum.vuejs.org/)或[Discord聊天](https://vue-land.js.org/)来聊天！
> 
> 它的工作。谢谢你:)

How pnpm handles this

**Comment by mandarino-x** [comment]
> > vue-router must be a peer dependency, like vue. You can see more explanations of what to do in Vue repository. I personally use yalc to handle this.
> > Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
> 
> it's worked .thank u :)

How pnpm handles this

**Comment by andredewaard** [comment]
> vue-router must be a peer dependency, like vue. You can see more explanations of what to do in Vue repository. I personally use yalc to handle this.
> 
> Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

Sorry if this is the wrong place to ask but, how do you do this? i stumble on the same issue where I'm creating an plugin for myself which already has some router functionality. Importing it in my vite plugin and using said functionality will throw an error that `const router = useRouter()` is undefined. i tried adding vue-router to peerDependencies inside the plugin and also add it to the vite.config als external like so
```
    rollupOptions: {
      external: ['vue', 'vue-i18n'],
      output: {
        globals: {
          vue: 'Vue',
          'vue-i18n': 'vue-i18n',
        },
      },
    },
```
