### ISSUE TITLE
vue-router.esm-bundler.js:72 [Vue Router warn]: No match found for location with path xxxx

### ISSUE THREAD

**Issue by x-carrier** [vuejs/router#1391]
### Version
4.0.15

### Reproduction link
[github.com](https://github.com/x-carrier/wms-admin)

### Steps to reproduce
import { createRouter, createWebHashHistory, RouteRecordRaw, RouterView } from 'vue-router'
import Layout from '@/layout/index.vue'

const routes:RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue')
  },
  {
    path: '/',
    component: Layout,
    children: [
      {
        path: '', // 为空则为默认子路由
        name: 'Home',
        component: () => import('@/views/home/index.vue')
      },
      {
        path: 'data',
        component: RouterView,
        children: [
          {
            path: '/sku',
            name: 'sku',
            component: () => import('@/views/data/sku/index.vue')
          },
          {
            path: '/box',
            name: 'box',
            component: () => import('@/views/data/box/index.vue')
          }
        ]
      }
    ]
  }
]

const router = createRouter({
  history: createWebHashHistory(),
  routes
})

export default router

This is my vue-Router configuration

### What is expected?
I want to call /data/sku to ask about the SKU component

### What is actually happening?
控制台打印警告
[Vue Router warn]: No match found for location with path "/data/sku"
![image](https://user-images.githubusercontent.com/49521216/166936094-6a49e8f9-2828-4c50-90e1-bffe07745ff8.png)

However, when I checked vue-devtools, I found that the /data/ sku route exists
![image](https://user-images.githubusercontent.com/49521216/166936210-ba847da4-51cf-4c63-9efa-904840c65a6c.png)

Strangely, when I accessed /sku, I found that the route at /data/sku was matched
![image](https://user-images.githubusercontent.com/49521216/166936313-3e655aba-07a0-40c4-9be1-2611970d9515.png)

The page also displays as an sku Component
This will not happen in the previous version, is there a problem with my configuration?

**Comment by LinusBorg** [comment]
```diff
- path: '/sku',
+ path: 'sku',
```
