### ISSUE TITLE
route.params can return array, but also string

### ISSUE THREAD

**Issue by 719media** [vuejs/router#1400]
### Version
4.0.15

### Reproduction link
[jsfiddle.net/z6ht9v0w/5/](https://jsfiddle.net/z6ht9v0w/5/)

### Steps to reproduce
If you create a route with wildcard, say, /post/:tags*, and then hit the route with /post/a/b/c, the value of route.params.tags will be ['a', 'b', 'c'] inside of the props(route) function.
However, if you navigate to /post, the value of route.params.tags will be empty string ''
I think it would be better to align the return type here and pass an empty array []

### What is expected?
Passing an empty array []

### What is actually happening?
Passing an empty string ''

---
There may be a specific reason for the empty string behavior, but I didn't see any issues or commits explaining why.

**Comment by posva** [comment]
I think this was intended but I don't remember why. If there are tests that check this behavior, it's definitely intended and while I'm not sure of the original reasons, it was at least done to keep backwards compatibility.

**Comment by posva** [comment]
I remembered the reason: it's to align with optional parameters and allowing easier type narrowing:

```ts
// given /path/:s*
if (route.params.s) {
  // route.params.s is a non empty array
}
```

instead of writting `route.params.s.length`.

Note this will improve with #1397 and typed routes
