### ISSUE TITLE
 The dynamic redirecting of  using path and query  will cause the browser console show warn.

### ISSUE THREAD

**Issue by jyp114110** [vuejs/router#1401]
### Version
4.0.15

### Reproduction link

https://jsfiddle.net/posva/3yq6ojLv/5

### Steps to reproduce
step1:
I config routes. You can details in minimal reproduction.
step2: 
I print the  'http://localhost:8080/#/s/1' into browser‘s address 

### What is expected?
the browser console will not show any warning info.

### What is actually happening?
vue-router.esm-bundler.js?ec2d:72 [Vue Router warn]: Path "search" was passed with params but they will be ignored. Use a named route alongside params instead.

**Comment by tux2nicolae** [comment]
Apparently after upgrade, this seems to broke some of my nuxt redirects

```
    'pages:extend'(routes) {
      routes.push(
        {
          path: '/t/:table',
          redirect: '/restaurant-menu/table/:table',
        },
      }
```
