### ISSUE TITLE
使用push向同页面修改query参数时报错 Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by xu509** [vuejs/router#1402]
### What problem does this feature solve?
使用push向同页面修改query参数时报错 Avoided redundant navigation to current location，无法实现修改query的功能

### What does the proposed API look like?
使用push向同页面修改query参数时报错 Avoided redundant navigation to current location，无法实现修改query的功能

**Comment by posva** [comment]
This is expected. You can still add a new query parameter or use force: true when pushing
