### ISSUE TITLE
<router-view> v-slot route param with nested route

### ISSUE THREAD

**Issue by yurks** [vuejs/router#1404]
### Version
4.0.15

### Reproduction link
[jsfiddle.net/jxreq8p0/79/](https://jsfiddle.net/jxreq8p0/79/)

### Steps to reproduce
1. Having a nested routes tree:
```
const Foo = { template: `<div>foo <router-view/></div>` }
const Bar = { template: `<div>bar</div>` }
[
  { path: '/foo', name: "foo-route", component: Foo, children: [  	
      { path: 'bar', name: "bar-route", component: Bar }
    ] },
]
```
2. Having a root template
```
<router-view v-slot="{ Component, route }">
  {{ route.name }}
  <component :is="Component" />
</router-view>
```

### What is expected?
`route` should contains matched route like matched Component

### What is actually happening?
It contains current route, which doesn't make sense at all

---
So, when navigating to `bar-route`, the `Bar` component appears inside nested `<router-view>` and `Foo` component still remains which is expected. But `route` comes with `Foo` component through `v-slot` properties now points to `bar-route`.

**Comment by posva** [comment]
The route contains many properties, what you are looking for is probably the array `route.matched`, which contains both, Foo and Bar. The current routes is the same across the whole application, **it has to have the same name everywhere**.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by yurks** [comment]
Well, I'm not looking for `roure.matched`. Please, check the demo, I looking for whole *matched* route object, corresponding to component attached. I understand about namings, so maybe a new one property to bind, like 'matchedRoute'?
