### ISSUE TITLE
Smooth scrolling after router-link does not work in firefox, but in chrome based browsers

### ISSUE THREAD

**Issue by lxgr-linux** [vuejs/router#1409]
### Version
4.0.15

### Reproduction link
[github.com](https://github.com/DecentralCardGame/frontend/tree/scrollback)

### Steps to reproduce
I am using this
```
scrollBehavior (to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition
    } else {
      return { top: 0, behavior: 'smooth'}
    }
  },
```
As `scrollBehavior` in my router, like described here: https://router.vuejs.org/guide/advanced/scroll-behavior.html .

### What is expected?
It is expected that when I scroll down the page and click on a router-link, that the page this directs to smoothly scrolls up.

### What is actually happening?
The page does not scroll up.

---
Removing `behavior: 'smooth'` makes it directly jump to the top of the new page, but does not scroll smoothly.
This only happens in firefox.

**Comment by lxgr-linux** [comment]
Intended behavior in chrome:

https://user-images.githubusercontent.com/64218491/169366757-679d854f-9d02-40be-a81c-c07afe017f17.mp4

Behavior in firefox:

https://user-images.githubusercontent.com/64218491/169367390-a42ee53c-eb3e-4762-9bb9-4042614d9426.mp4

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction that follows the instructions at https://new-issue.vuejs.org/?repo=vuejs/router#why-repro (use the link of the jsfiddle there).

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled down reproduction.
