### ISSUE TITLE
Invalid string error: `DOMException: String contains an invalid character` when attempting to route to page with `%` in HTML

### ISSUE THREAD

**Issue by jeffrey-dot-li** [vuejs/router#1413]
### Version
4.0.15

### Reproduction link
[github.com](https://github.com/jeffrey-dot-li/VueRouterInvalidString)

### Steps to reproduce
Run the minimal reproduction repo based off of https://github.com/antfu/vitesse-nuxt3. Click on GO will sucessfully route to the demo page, but clicking BACK will cause router error because there is a string with `%` attribute on index page.

### What is expected?
Routing to go back to index page

### What is actually happening?
`%` in html attribute causes vue router to be unable to render page.

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/router#why-repro when reporting a bug and open a new issue if you can reproduce it without Nuxt.

That being said, the error seems originated by the browser and not related to vue router
