### ISSUE TITLE
Support the Navigation API

### ISSUE THREAD

**Issue by LifeIsStrange** [vuejs/router#1415]
### What problem does this feature solve?

Chromium 102 has been released stable, which means that Chrome, Edge, Opera, Brave, Vivaldi, etc and Electron supports the Navigation API
https://chromestatus.com/feature/6232287446302720
The Navigation API is the successor of the History API and is better suited for SPAs.
Therefore, routers should allow to target and leverage it.

### Why should this feature be included?

> The existing window.history API is hard to deal with in practice, especially for single-page applications. In the best case, developers can work around this with various hacks. In the worst case, it causes user-facing pain in the form of lost state and broken back buttons, or the inability to achieve the desired navigation flow for a web app.

### What does the proposed API look like?
see the spec https://chromestatus.com/feature/6232287446302720

**Comment by posva** [comment]
I'm aware and active in the open discussion of the API and it's still too early to adopt. It will be adopted possible.
