### ISSUE TITLE
Why is it necessary to execute replacestate once when calling the push method

### ISSUE THREAD

**Issue by 0scarecrow0** [vuejs/router#1416]
### Version
4.0.15

### Reproduction link
[github.com](https://github.com/0scarecrow0/chrome-extension-yapiMock)

### Steps to reproduce
When calling the push method, history.replacestate and history.pushstate will be triggered, resulting in problems in the Statistics website PV. Looking at the source code, I found that when calling the push method, I first executed replacestate. I don't understand why?

### What is expected?
Only history is triggered when pushing pushState

### What is actually happening?
Push history.replacestate and history.pushstate will trigger

<img width="767" alt="image" src="https://user-images.githubusercontent.com/45458124/170430625-2e35719a-b6b4-49bc-a7c6-906e13d09c93.png">

**Comment by posva** [comment]
This is necessary to update the current history entry to be able to cancel ui initiated navigations through navigation guards. It allows knowing the direction of a navigation and the relative position in the history stack. There is unfortunately no other way of doing this yet.

I don't know what "Statistics website PV" is but it should check in replaceState calls if the page changes as the point is really to "replace the state" of the current history entry.

**Comment by chf007** [comment]
Is it possible to add a flag to the `state` to distinguish the real `replace` call, or the other purpose call?

**Comment by kangw3n** [comment]
I need to raise this issue again.

Executing both replaceState and pushState causes problems with Google Tag Manager and Google Analytics when History event detection is enabled. (See https://support.google.com/tagmanager/answer/7679322?hl=en for reference.)

This setting causes page view events to be triggered twice. Turning it off, however, requires all events to be manually configured. This can be problematic when Google Tag Manager is managing multiple sites simultaneously, especially with Single Page Application (SPA) or NuxtLink implementations.

I'm not sure how other sites deal with this issue, but calling both replaceState and pushState on a single navigation seems to go against web API best practices. 

Any thoughts on this?
