### ISSUE TITLE
Different Route, same component, when change route, the event onBeforeRouteUpdate of the component is not trigger

### ISSUE THREAD

**Issue by IrvingZhao** [vuejs/router#1417]
### Version
4.0.15

### Reproduction link
[codepen.io](https://codepen.io/irvingzhao/pen/eYVeQwP)

### Steps to reproduce
1. click route A1
2. click route A2
3. click route B1
4. click route B2

### What is expected?
onBeforeRouteUpdate will be trigger three times

### What is actually happening?
onBeforeRouteUpdate only trigger two times

**Comment by kissu** [comment]
Just to provide more details to people who may not understand when this hook would be called, this is a snippet example with a button that will update the router object without moving (by using a random hash).

```html
<button @click="$router.push({ hash: `#${Math.floor(Math.random() * 10)}` })">
  random hash
</button>
```
