### ISSUE TITLE
New parametr for getRoutes function

### ISSUE THREAD

**Issue by JakubChimiak** [vuejs/router#1420]
### What problem does this feature solve?
Dynamic menu fetching, for example now I have all my protected routes nested in "Panel" route

### What does the proposed API look like?
getRoutes(parentName?: string | symbol)

**Comment by posva** [comment]
`getRoutes()` is intended to be very simple. Any custom transformations to be done with `filter()`, `map()`, or `reduce()` are to be done by the user for their specific application use cases.
