### ISSUE TITLE
router-link to named route not matching nested routes like router-link to path does

### ISSUE THREAD

**Issue by Soviut** [vuejs/router#1423]
### Version
4.0.15

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/kind-roentgen-vyk6zy)

### Steps to reproduce
- In App.vue create a router-view
- create a route, give it a name `parent`, add a heading saying `parent`, add a `<router-view>`
- add a child route with an empty path `''`, give it a name `child`, add a heading saying `child`, add a `<router-view>`
- add a grandchild route with an empty path, give it a name `grandchild`,  add a heading saying `grandchild`
- in App.vue, create a `<router-link :to="{ name: 'parent' }">`
- in App.vue, create a `<router-link to="/parent">`
- click the first route (using name) and observe that only `parent` page shows, none of the router-views show
- click the second route (using path) and observe that `parent`, `child` and `grandchild`, all the nested router-views show

### What is expected?
Clicking a router-link with a route name should cascade through the nested routes it matches, just like a router-link with a path does.

![image](https://user-images.githubusercontent.com/226882/170816258-056476d3-43c3-4aa5-8364-7e6ef46cd4a7.png)

### What is actually happening?
Clicking a router-link with a route name does not match on any nested routes.

![image](https://user-images.githubusercontent.com/226882/170816280-9f7ae320-0216-4e09-9cf1-6823b5d8f5fe.png)

**Comment by posva** [comment]
This is expected behavior. Use the name of the child if you want to target the child.

**Comment by Soviut** [comment]
@posva I can't target the child in this situation. It's my top level nav and targeting a specific child will mean active-class won't get set except when the child route is active.

I have a somewhat complex routing situation because my index page has its own sub-routes and its own layout. So I have to do the following so that the layout does not appear on the edit page.

```javascript
    {
      path: '/users',
      component: PassthruLayout,
      name: 'users',
      children: [
        {
          path: '',
          component: UserLayout, // <-- layout with tabs specifically for the index page routes
          name: 'users-index',
          children: [
            {
              path: '',
              component: UserIndex,
              name: 'users-all',
            },
            {
              path: 'flagged',
              component: UserIndex,
              name: 'users-flagged',
            },
            {
              path: 'banned',
              component: UserIndex,
              name: 'users-banned',
            },
          ],
        },
        {
          path: ':id', // <-- edit page does not share the tabbed layout
          component: UserEdit,
          name: 'users-edit',
          props: true,
        },
      ],
    },
```

**Comment by posva** [comment]
In that case, you should be able to either:

- add a `redirect`:
  ```js
  path: "/parent",
  component: Parent,
  redirect: () => ({ name: 'grandchild' }),
  ```
- Add the class manually with `:class="{ 'active-link': $route.path.startsWith(...) }"`

**Comment by Soviut** [comment]
Ah, the redirect worked. I didn't realize I could put a redirect and a component on the same route; I thought they were mutually exclusive.

**Comment by Soviut** [comment]
I still think it's very strange behaviour for nested router-views to not load anything because the parent route was linked by name. Especially since it's inconsistent with the way path routing works.
