### ISSUE TITLE
有没有类似于 angular的route的resolve的功能呢？

### ISSUE THREAD

**Issue by maoxianmmd** [vuejs/router#1424]
### What problem does this feature solve?
有没有类似于 angular的route的resolve的功能呢？

### What does the proposed API look like?
有没有类似于 angular的route的resolve的功能呢？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
