### ISSUE TITLE
Nested Routes are not working in Production Build

### ISSUE THREAD

**Issue by Saqib92** [vuejs/router#1428]
### Version
4.0.15

### Reproduction link
[github.com](https://github.com/vuejs/vue-router/issues/3757)

### Steps to reproduce
Create nested Routes and check in production build. 

using command: `Yarn Build`

### What is expected?
Production Build Should work with nested Routes

### What is actually happening?
Application is working fine but after making production build: yarn build nested routes are not working. URL gets Changed but there is nothing but a blank page. and this is happening is on on nested routes.

---
```const routes = [
//other Routes,

{
        path: '/search',
        name: 'search',
        component: () => import( /* webpackChunkName: "about" */ '../views/SearchView.vue'),
        children: [
            { path: 'stacker', component: import( /* webpackChunkName: "about" */ '../views/SearchStackerView.vue') },
            { path: 'filter', component: import( /* webpackChunkName: "about" */ '../views/SearchFilterView.vue') },
            { path: 'keypad', component: import( /* webpackChunkName: "about" */ '../views/SearchKeypadView.vue') },
        ],
    }
]```

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
