### ISSUE TITLE
onBeforeRouteEnter guard for composition API

### ISSUE THREAD

**Issue by Q-back** [vuejs/router#1433]
```vue-router@4.0.12```
## What problem does this feature solve?
According to [this StackOverflow answer](https://stackoverflow.com/a/66482308/7284582) there's no way to do something like `onBeforeRouteEnter` in the composition-api flavor. This is especially painful when I work with components using `<script setup>` syntax.

## What does the proposed API look like?
```vue
<script setup>
import { onBeforeRouteEnter } from "vue-router";

onBeforeRouteEnter((to, from, next) => {
  console.log("Route did not enter yet. You can modify route.params or whatever.");
});
</script>
```

**Comment by posva** [comment]
We are aware of this and there are plans to support a new navigation guard that works with Suspense. It will go through an RFC to get feedback from the community.

**Comment by dante01yoon** [comment]
@posva Is RFC related on this still in progress?

**Comment by hobuttt** [comment]
Not yet? )

**Comment by posva** [comment]
It’s actually up with the data loaders rfc. It’s a bit different but it’s been up for a long time https://uvr.esm.is/rfcs/data-loaders/
