### ISSUE TITLE
RouteRecordRaw type error

### ISSUE THREAD

**Issue by cloudhao1999** [vuejs/router#1452]
### Version
4.1.0

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/kind-forest-up24i1?file=/src/router/autoload/index.ts)

### Steps to reproduce
Select version 4.0.16, the type prompt is normal
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/32376445/177235500-5a917b34-654d-4c0d-8ee6-6c0e17e800e6.png">

 switch to version 4.1.0 RouteRecordRaw type error, display TS2339: Property 'children' does not exist on type 'RouteRecordRaw'.
<img width="1867" alt="image" src="https://user-images.githubusercontent.com/32376445/177235407-7e27b23b-5483-41c3-b332-51b60b176ae2.png">

### What is expected?
Type inference is correct or provide alternative solutions

### What is actually happening?
Property 'children' does not exist on type 'RouteRecordRaw'.
  Property 'children' does not exist on type 'RouteRecordSingleView'.

---
No type problem in version 4.0.16, upgrade to version 4.1.0 with TS2339 type error

**Comment by posva** [comment]
hmm, so this is supposed to be a feature: stricter type checking. I agree I would rather do `r.children` than `'children' in r` (which works) but maybe this strictness isn't necessary. This was added with
- https://github.com/vuejs/router/issues/1174

Adding back support for it makes other invalid routes pass when defining routes 😞 . I will have to dig a little bit deeper
