### ISSUE TITLE
Make asynchronous data requesting and accessing first-class citizens in SPAs.

### ISSUE THREAD

**Issue by jasonbodily** [vuejs/router#1458]
### What problem does this feature solve?

Answer: Leveraging asynchronous data.

Vue with Vue Router is a leading 21st century, single-page application solution built on Javascript. Consequently any interested developer would expect to find it _exceptional_ at handling asynchronous use cases.

Consider a common use case like that of navigating from a movies categories page to a specific movie landing page. Before loading the landing page, it's expected that assets relating to the specific movie load correctly. Currently Vue proposes to handle these requests in `beforeRouteEnter` and `beforeRouteUpdate` hooks.

The trouble comes in leveraging any asynchronously loaded asset in composing the component. In the event of beforeRouteEnter, the loaded data is not made available to the component until "nextTick" (https://github.com/vuejs/vue-router/issues/1144). This means that a component that can only exist given the existence of an asset, still has to account for that asset being undefined/null in its first render cycle. It means the asynchronously loaded data is not made available to the component during the "data" or "created" lifecycle hooks unless a data store is introduced to bridge that accessibility. It means asynchronously loaded cannot be somehow marked as reactive, but must rather be defined and loaded, and then defined again in the "data" or "ref" hooks.

While this has been head scratching, what is more confusing is that any chance to bridge this gap with mixins has been made impossible by the "unintentional" removal of mixin route support (https://github.com/vuejs/router/issues/454). It is most curious to find asynchronous features and support dismissed out of hand. I ask again—Why in the 21st century of Javascript SPAs is it so hard to asynchronously load data and use it in the composition of a component?

I propose a feature that allows users to resolve any amount of asynchronous requests and then make the data resolved _immediately_ available to the component. I propose first-class async mixin support for route resolving. In short, in the non-compositional component definitions, anywhere "this" is accessible so should the data that has been loaded asynchronously.

### What does the proposed API look like?
It could be as simple as:
```
async beforeRouteEnter() {
   ... do async code to load a,b,c
  return {  a:a, b:b, c:c }
}
```
and then expose a, b, and c to the component's `this` for immediate use during the creation/initialization of the component.

A more advanced (not recommended, only shown for illustrative purposes) example harkens back to Angular's early days:
```
export default {
  resolve: [{
    movie: () => fetch('api.com/movie'),
    movieUserExperience: ['movie', movie => fetch('api.com/movieUserExperience/${movie.id}']  
  },
    () => fetch('api.com/reportmovievisit'),
    () => fetch('api.com/fetchstoreresource')
  ]
}
```
, where `movie` and `movieUserExperience` are available immediately on the component at every level and can be made reactive. While I recognize a core library may not want to take on a feature more nuanced like this, removing mixin support and generally disregarding async functionality in new component design makes servicing this need for developers only that much more difficult.

It is my opinion that in the 21st century, async development should not be difficult, but rather the bread and butter of any SPA framework.

**Comment by posva** [comment]
We have plans to make async setup be part of navigations. It will go through an RFC soon.
