### ISSUE TITLE
RouterView Issue with Teleporting Component

### ISSUE THREAD

**Issue by incutonez** [vuejs/router#1473]
### Version
4.1.2

### Reproduction link
[codesandbox.io/s/rvovr6](https://codesandbox.io/s/rvovr6?file=/src/FooView.vue)

### Steps to reproduce
- Make sure Fiddle's route starts on Home
- Notice Home shows in the main body (expected)
- Click Foo RouterLink
- Notice Foo shows below the main body (expected)
- Click Home RouterLink
- Notice Home now shows below the main body (unexpected)

### What is expected?
When you click Home after clicking Foo, it should show back in the main body.

### What is actually happening?
Home is showing in the overlayContainer div, where Foo was injected.

---
In App.vue, you'll also see that I've tried manually having HomeView and FooView toggled through a `v-show`, which works as expected, so it seems like there might be an issue with RouterView when it comes to elements that are teleported.  I've also tried having the `Teleport` tag be used in FooView as the main tag, but that seems to throw some sort of child is null error.

**Comment by posva** [comment]
You cannot manually move elements that are controlled by Vue, that's why it breaks. You should try using `<Teleport>` (https://vuejs.org/guide/built-ins/teleport.html#teleport)

```vue
<Teleport to="body">
	<RouterView />
</Teleport>
```

**Comment by incutonez** [comment]
@posva The problem with what you've posted is that you're now teleporting everything to the body, which is not what I want.  The component itself is what's controlling that.

**Comment by incutonez** [comment]
For anyone else that comes to this, it definitely seems like a bug in `RouterView`, but I guess we're more concerned about closing issues as fast as possible without reading the full description of the issue.  Either way, I fixed this by wrapping the RouterView component in a tag... e.g. [this](https://codesandbox.io/s/objective-chaum-whxofx?file=/src/App.vue)
