### ISSUE TITLE
vue3使用history模式，本地打包后路由会消失(是路由直接消失)

### ISSUE THREAD

**Issue by Melody1008** [vuejs/router#1490]
### What problem does this feature solve?
vue3使用history模式，本地打包后路由会消失(是路由直接消失),使用nginx重定向还是没有路由，
但是在createWebHistory函数内部添加路径(比如'/'）就可以显示，
这个在官方文档里面没有显示，

### What does the proposed API look like?
vue3使用history模式，本地打包后路由会消失(是路由直接消失),使用nginx重定向还是没有路由，
但是在createWebHistory函数内部添加路径(比如'/'）就可以显示，
这个在官方文档里面没有显示，

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
