### ISSUE TITLE
routing by "name" doesnt resolve nested routes with empty path

### ISSUE THREAD

**Issue by Schloemicher** [vuejs/router#1493]
### Version
4.1.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/intelligent-surf-psyjqo?file=/src/router.js)

### Steps to reproduce
- create a parent route with a name
- create children
  - one with empty string "" as path
  - one with an id

navigate somewhere by name to the parent 

### What is expected?
the component with the "" empty path is also shown

### What is actually happening?
only the parent is shown

---
it is somewhat unintuitive that you have to use the name of the child with the empty path because it doesnt work like the like de docs https://router.vuejs.org/guide/essentials/nested-routes.html promises

**Comment by posva** [comment]
This is intended behavior so one can target the parent with no child. You even get a warning if you name the parent without naming the child route 🙂 . If you think this could be improved in documentation, please open a PR with the proposal
