### ISSUE TITLE
isExactActive is false after a redirect with a named route

### ISSUE THREAD

**Issue by Florent-Bouisset** [vuejs/router#1497]
### Version
4.1.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/awesome-fast-mjksyp?file=/index.html)

### Steps to reproduce
- Click on Home Link, isExactActive and isActive is true
- Click on 4O4 link
- You are redirected to Home page
- You current url is /home

### What is expected?
`isExactActive` and `isActive` are `true` for page `Home` because you have been redirected to this page

### What is actually happening?
`isActive` is true but `isExactActive` is `false`

---
I have this issue only when I redirect with a named route, I don't have it when I redirect with a url

**Comment by posva** [comment]
Using a `beforeEnter()` guard also works a a workaround
