### ISSUE TITLE
[Documentation] Wrong link to Dynamic Imports docs

### ISSUE THREAD

**Issue by f3oall** [vuejs/router#1498]
### Version
4.1.3

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/guide/advanced/lazy-loading.html#lazy-loading-routes)

### Steps to reproduce
1. Open the page
2. Find the paragraph and click on the link "Vue Router supports [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) out of the box, meaning you can replace static imports with dynamic ones:"

### What is expected?
The link will lead to:  
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What is actually happening?
The link leads to:  
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports

**Comment by posva** [comment]
Can you open the PR?

**Comment by f3oall** [comment]
Sure, hope it's fine!
