### ISSUE TITLE
Export members of  'RouteRecordRaw' union from 'vue-router.d.ts'

### ISSUE THREAD

**Issue by f3oall** [vuejs/router#1499]
### What problem does this feature solve?
I was trying to add custom functions for route generation, something like this:
```typescript
export function redirect(path: string, redirect: string): RouteRecordRaw {
  return { path, redirect }
}

export function route(path: string, filePath: string, meta: RouteMeta = {}, children = []): RouteRecordRaw {
  return { path, component: page(filePath), meta, children }
}
```
As you can see I used the type 'RouteRecordRaw', because it's the only exported one. This type itself is a Union of sub-types:
```typescript
export declare type RouteRecordRaw = RouteRecordSingleView | RouteRecordSingleViewWithChildren | RouteRecordMultipleViews | RouteRecordMultipleViewsWithChildren | RouteRecordRedirect;
```
So if I could use these union members in my code as separate types it would provide an opportunity to set types more specifically.

Therefore can we export these types?

### What does the proposed API look like?
In *vue-router.d.ts*
```typescript
// Add export for each union member
export declare interface RouteRecordRedirect extends _RouteRecordBase {
    redirect: RouteRecordRedirectOption;
    component?: never;
    components?: never;
    props?: never;
}
// Same for others
// ....
```

**Comment by posva** [comment]
Why do you need to use those types?
The RouteRecordRaw should be enough for user usage, that's why others are not exported.

**Comment by f3oall** [comment]
Yeah, it's not a big deal of course. 

I have a simple idea. If my function returns the object which will be used only as **RouterRecordRedirect**, I would prefer to set it explicitly. Because type **RouteRecordRaw** doesn't give us enough info about the shape of the value. This example is true for other union members as well.

So, it's definitely not very important, but it also requires small amount of changes in code, doesn't it?

**Comment by posva** [comment]
Unfortunately, exposing new public API is always a risk of breaking changes in the future, being small does not change that.

If there is no need to use anything more specific than RouterRecordRaw, let's keep it this way.
