### ISSUE TITLE
router-view在渲染完路由后以路由外层的div的形式存在，并没有完全被路由内容所替换

### ISSUE THREAD

**Issue by QianShi-ffg** [vuejs/router#1501]
### Version
4.1.2

### Reproduction link
[codepen.io](https://codepen.io/qianshi-ffg/pen/bGvvjJo)

### Steps to reproduce
//主路由所在结构
 <el-main>
      <div id="box-card">
           
           <router-view/>  
       </div>
 </el-main>

// 子路由
<template>
  <div id="articleBtn"></div>
<template>

### What is expected?
 // 期望生成这样的结果
<div id="box-card">
         <div id="articleBtn"></div>
 </div>

### What is actually happening?
 // 实际生成这样的结果
<div id="box-card">
         <div data-v-2f8eac8e>
                <div id="articleBtn"></div>
         </div>
 </div>

---
我在页面上需要将子路由展示出来，设置router-view后 页面展示出来却多出一层div ，并未达到期望的效果，这个在之前使用过程中是并未有见到过

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
