### ISSUE TITLE
Duplicate API documentation contents.

### ISSUE THREAD

**Issue by niceplugin** [vuejs/router#1504]
### Version
4.1.3

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/api/interfaces/Router.html#aftereach)

### Steps to reproduce
See the minimal link.
The main content describing this method has two return sections.
Also, the return section repeats the explanatory content exactly the same.
A lot of the API documentation is in this state.
I recommend checking the typedoc.

### What is expected?
Non-duplicate document content.

### What is actually happening?
Duplicate document content.

---
I've stopped the translation work because I think many parts of the document will probably change again.
Always thank you for your hard work.

**Comment by posva** [comment]
This might be a bug in the generating lib or in the way the tsdocs are written

**Comment by BboyAkers** [comment]
I can look into this if it's not taken!

**Comment by oelerpearler** [comment]
Any news on this "issue"? I didn't realize this seemingly needless duplication of the docs until now, but I guess this is not the intention of the original authors I guess?
![image](https://user-images.githubusercontent.com/982123/208251082-3183757d-0572-4d1e-827d-b502091ca9f3.png)

In my oppinion, the docs are really great, so it's not really bad, but it just unnecessarily bloats the docs and makes them less concise.

**Comment by NozomuIkuta** [comment]
This issue has been fixed at some point, hasn't it?

**Comment by posva** [comment]
I think so
