### ISSUE TITLE
Critical Bug: Undefined URLs

### ISSUE THREAD

**Issue by brunomartinspro** [vuejs/router#1507]
### Version
4.1.3

### Reproduction link
It is hard to add a link to reproduce this since the code is running on private repos of the company i work for with multiple edge cases.

### Steps to reproduce
1) Use the latest vue , vue-router, single-spa with webpack
2) Add multiple router-links and one with the to mapped to the root
2) navigate multiple levels below and click on the router link
3) You get redirected to baseUrlUndefined

### What is expected?
We don't add undefined to the URL

### What is actually happening?
We are adding undefined to the URL

---
I added a Pull request with the fix, https://github.com/vuejs/router/pull/1502

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction that follows the instructions at https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled down reproduction.
