### ISSUE TITLE
The meta objects of nested routes are merged, is this a bug or feature ?

### ISSUE THREAD

**Issue by hooray** [vuejs/router#1508]
### Version
4.1.3

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-router-4-reproduction-forked-v5xml5?file=/index.html)

### Steps to reproduce
This is my nested routes, when I visit and print `/foo/test`, the `meta` object is `{ a: 1, b: 2 }`
```
          {
            path: '/foo',
            component: Foo,
            meta: { a: 1 },
            children: [
              {
                path: 'test',
                component: Test,
                meta: { b: 2 },
              },
            ],
          }
```

### What is expected?
print `{ b: 2 }`

### What is actually happening?
/

**Comment by posva** [comment]
As mentioned in docs, this is intended.
