### ISSUE TITLE
Docs text incorrectly identified as URL 

### ISSUE THREAD

**Issue by Bamblehorse** [vuejs/router#1511]
### Version
4.1.3

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/api/interfaces/routerlinkprops.html#inherited-from-1)

### Steps to reproduce
Navigate to: https://router.vuejs.org/api/interfaces/routerlinkprops.html#inherited-from-1

Observe that `RouterLinkOptions.to` is a link although it is meant to be just text

### What is expected?
The text `RouterLinkOptions.to` should not be transformed into a link

### What is actually happening?
The text `RouterLinkOptions.to` is transformed into a link

---
There may be other parts of the documentation with this issue due to commonly used domain name endings such as `.to`

**Comment by posva** [comment]
This seems to be a vitepress bug as the markdown is just plain text. It probably got fixed as we are still blocked with an older version
