### ISSUE TITLE
Vue Router 中文文档错误

### ISSUE THREAD

**Issue by MrLiNuo** [vuejs/router#1515]
### Version
4.1.3

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/zh/guide/advanced/composition-api.html#%E5%AF%BC%E8%88%AA%E5%AE%88%E5%8D%AB)

### Steps to reproduce
组合式api注释出现误导现象，在setup中是无法访问this的，这里并没有给出明确说明，结合上下文 导航守卫api 容易让人误导

组合式api中，导航守卫小节 中文注释 ：
//与 beforeRouteLeave 相同，无法访问 this 
 // 与 beforeRouteUpdate 相同，无法访问 `this`

但导航守卫api中     组件内的守卫 可用的配置api小节中 
beforeRouteUpdate // 因为在这种情况发生的时候，组件已经挂载好了，导航守卫可以访问组件实例 `this` 
beforeRouteLeave  // 与 `beforeRouteUpdate` 一样，它可以访问组件实例 `this`

### What is expected?
没有

### What is actually happening?
没有

---
没有

**Comment by posva** [comment]
I don't find it confusing, if you have a proposal, could you instead open a PR, please?
