### ISSUE TITLE
route.push encode bug

### ISSUE THREAD

**Issue by maoxian-1** [vuejs/router#1518]
### Version
4.1.3

### Reproduction link
[jsfiddle.net/5zn8yf0v/3/](https://jsfiddle.net/5zn8yf0v/3/)

### Steps to reproduce
When I use this params

```js
route.push({
path,
query: {
 cburl:'https://www.baidu.com/s?wd=1&1=1'
}
})
```

I will redirect to path?cburl=https://www.baidu.com/s?wd=1&1=1
But when I use this params

```js
route.push({
path,
query: {
 cburl: encodeURIComponent('https://www.baidu.com/s?wd=1&1=1')
}
})
```

I will redirect to path?cburl=https%253A%252F%252Fwww.baidu.com%252Fs%253Fwd%253D1%25261%253D1

I can not redirect to this url :path?cburl=https%3A%2F%2Fwww.baidu.com%2Fs%3Fwd%3D1%261%3D1

### What is expected?
encode url bug

### What is actually happening?
Can not encode url but will encode url after encodeURIComponent, It means I only can encode twice or none

**Comment by posva** [comment]
Params and query params already encode/decode what is passed, so you don't need to encode anything. Just remove that `encodeURIComponent()` call

**Comment by maoxian-1** [comment]
> Params and query params already encode/decode what is passed, so you don't need to encode anything. Just remove that `encodeURIComponent()` call

But how can I go to path?cburl=https%3A%2F%2Fwww.baidu.com%2Fs%3Fwd%3D1%261%3D1

Now I only can go to  path?cburl=https://www.baidu.com/s?wd=1&1=1  and  path?cburl=https%253A%252F%252Fwww.baidu.com%252Fs%253Fwd%253D1%25261%253D1
