### ISSUE TITLE
TypeScript error when passing props using "Boolean mode"

### ISSUE THREAD

**Issue by JoostKersjes** [vuejs/router#1521]
### Version
4.1.3

### Reproduction link
[jsfiddle.net/sqghye34/5/](https://jsfiddle.net/sqghye34/5/)

### Steps to reproduce
See link to minimal reproduction for some code.

1. Set a route to pass props using ["Boolean mode"](https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode)
2. Attempt to assign a `boolean`, `number` or `object` type as one of the route's `params`.

### What is expected?
I expect the `params` type to allow me to pass props that are required  using "Boolean mode" **or** I expect `vue-router` to throw an error when passing unexpected values if this is considered to be abusing the `params`.

### What is actually happening?
The props are passed correctly, no matter the type, but I get the following TypeScript error:
```
Type 'number' is not assignable to type 'string | string[]'.ts(2322)
```

Now I'm uncertain if this is an undocumented feature suffering from a bad type signature, or if I'm abusing the `params`.

---
If "Boolean mode" is not intended to pass props that fall outside of the `string | string[]` type signature, this should be cleared up in the documentation.

**Comment by posva** [comment]
You cannot modify `to` or the route object, they are readonly. This TS error is working as expected. You can still format the prop to be a number though:

```ts
props: to => ({ foo: Number(to.params.number) })
```
