### ISSUE TITLE
Expose useHistoryStateNavigation and useHistoryListeners for custom history handler

### ISSUE THREAD

**Issue by xolott** [vuejs/router#1522]
### What problem does this feature solve?
I'm creating a Chrome extension using `vue-router` and the `createWebHashHistory` method. 

My app is injected into the page, and the base path is a hash (`#appName`) When the app goes out of "focus" `app.unmount()` is called, but the router keeps working in the background. Hence, if a navigate to another native route (within the "host" page) with a hash on the url, my app's `vue-router` instance changes the hash to #appName

This may be a bug, but I solved the issue by creating a custom history handler for the router. So, it would be great to have `useHistoryStateNavigation` and `useHistoryListeners` exposed by vue-router from (router/packages/router/src/history/html5.ts)

Right now, I had to copy a lot of code from the source code.

### What does the proposed API look like?
Just expose existing methods

**Comment by posva** [comment]
I don't understand what bug you are trying to solve, I guess opening a new issue with a boiled-down repro would help. Calling app.unmount() also destroys the router.

Those methods are intentionally internal, we don't want to expose them as public API as they are very low level and they could change between versions.
