### ISSUE TITLE
The parameters of the  replace()  method are escaped

### ISSUE THREAD

**Issue by ILfengzi** [vuejs/router#1523]
### Version
4.1.3

### Reproduction link
[www.sorry.i.can%27t.provide.this.at.this.time.com](http://www.Sorry.I.can't.provide.this.at.this.time.com)

### Steps to reproduce
router.replace('/m?param=test%3D%3D') ==> url: '/m?param=test=='

### What is expected?
url: '/m?param=test%3D%3D'

### What is actually happening?
url: '/m?param=test=='

**Comment by posva** [comment]
This is just necessary otherwise we can't parse them...

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!

**Comment by ILfengzi** [comment]
已收到！
