### ISSUE TITLE
Redundant `require('@vue/devtools-api')` in the CJS prod build

### ISSUE THREAD

**Issue by sodatea** [vuejs/router#1524]
### Version
4.1.3

### Reproduction link
[unpkg.com](https://unpkg.com/vue-router@4.1.3/dist/vue-router.prod.cjs)

### Steps to reproduce
Cmd + F, search for `require('@vue/devtools-api')` on the page

### What is expected?
The `require` statement should be tree-shaken away from the bundle, because non of its exports are used in the prod bundle of `vue-router`, and the package is of `sideEffects: false`:
https://github.com/vuejs/devtools/blob/ba54bb770a829429226a630dd5dbedcf596f27ef/packages/api/package.json#L9

### What is actually happening?
It remains in the CJS prod bundle

---
Originally reported at https://github.com/vuejs/devtools/issues/1932
As my comment on the issue, it's not a big issue as most users would use the `esm-bundler` version, which could be correctly tree-shaken.
But this issue still indicates that something might be wrong in `vue-router`'s rollup config.

**Comment by posva** [comment]
It's funny, we were just talking about this with the Nuxt team yesterday for pinia: https://github.com/vuejs/pinia/pull/1561

It does seem like a bug in rollup (or maybe intentional for perf reasons) but we did find a way to remove it so I will just apply the same change
