### ISSUE TITLE
router-link does cannot work with createVNode and render

### ISSUE THREAD

**Issue by jambonn** [vuejs/router#1525]
### Version
4.1.3

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-ckpvz9)

### Steps to reproduce
1. Render component to child element with createVNode and render
2. The rendered component won't render router-link
3. Console display message: [Vue warn]: Failed to resolve component: router-link

### What is expected?
router-link render normal

### What is actually happening?
[Vue warn]: Failed to resolve component: router-link

**Comment by posva** [comment]
This is not related to Vue Router, it's about `createVNode()`, you probably meant to use `h()` but also you seem to be trying to mount (or `render()`) a component on nodes rendered by vue? Which is not really supported behavior.

**Comment by jambonn** [comment]
@posva Thanks for the reply. I also realized it is an issue of vue even I createApp with the _context of the root app also error

**Comment by posva** [comment]
Yeah… you should really avoid using internals and undocumented features. There is likely another way of reaching your goal
