### ISSUE TITLE
stringifyQuery does not encode correct

### ISSUE THREAD

**Issue by mseele** [vuejs/router#1528]
### Version
4.1.4

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/kind-ramanujan-rtvq2t)

### Steps to reproduce
- Open https://codesandbox.io/s/kind-ramanujan-rtvq2t
- Click on About Link
- Check URL path ends with "/about?x=[{()}]" (which is incorrect / no encoding happened)

### What is expected?
Expected behaviour would be that the query value of x ([{()}]) is encoded (%5B%7B%28%29%7D%5D).

### What is actually happening?
The query value of x is not encoded.

---

### Workaround / Solution
Using [qs](https://github.com/ljharb/qs) instead of stringifyQuery, everything works like expected.
Please see this [codesandbox.io](https://codesandbox.io/s/zen-darkness-kezlqb).

### (Possible) Fix

For me, it looks like that the replace attributes of `encodeQueryValue` are in a wrong order:

It should **NOT** be `.replace(ENC_CURLY_OPEN_RE, '{')`, it should be `.replace('{', ENC_CURLY_OPEN_RE)`.

Right now, `encodeQueryValue` is decoding, not encoding.

**Comment by posva** [comment]
Note js cannot control what the browser displays on the URL. The only thing that matters from the router perspective is that the decoding of the query is consistent:

- https://rtvq2t.csb.app/about?x=%5B%7B%28%29%7D%5D -> `$route.query` is decoded
- https://rtvq2t.csb.app/about?x=[{()}] -> same

You can check more about the encoding strategy in the source code: https://github.com/vuejs/router/blob/main/packages/router/src/encoding.ts
