### ISSUE TITLE
Pretty pagination link

### ISSUE THREAD

**Issue by weblabio** [vuejs/router#1530]
### Version
4.1.3

### Reproduction link
[jsfiddle.net](https://jsfiddle.net/Weblabio/0kbsac3j/9/)

### Steps to reproduce
1. Go to  
`localhost:3000/posts ` 
`localhost:3000/posts/page/2`

2. Open console in DevTools

### What is expected?
I need the following links for my pagination  
`localhost:3000/posts  `  - status 200 
`localhost:3000/posts/page/2  `  - status 200 
`localhost:3000/posts/page `  - status 404 
`localhost:3000/posts/any/2 `  - status 404 

`page/*` - optional part  

**Unfortunately I didn't find a way to do this without alias**

### What is actually happening?
The route works but in the console I get an warning:  
`[Vue Router warn]: Alias "/posts" and the original record: "/posts/page/:page(\d+)" should have the exact same param named "page"`

---
`localhost:3000/posts/page/2` - classic pagination link  
  
`localhost:3000/posts/2` - ugly format, what is 2? Page or Post ID?  
  
What if I need to make pagination on the home page?  
`localhost:3000/2` - this is not a pretty link  
`localhost:3000/page/2` - is ok  
  
please don't suggest this:  
`localhost:3000/posts?page=2`   
or  
`localhost:3000/posts#page-2  `
these URLs are ugly and do not match my requirements specification  
  
I understand what the warning is, can I ignore it?  
any suggestions how to make pretty link with `~(page/\d+)?~
`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by weblabio** [comment]
@posva 
my question and bug report (1) and feature request (2), it's not my fault that you don't have a flexible template
1. Error
`[Vue Router warn]: Alias "/posts" and the original record: "/posts/page/:page(\d+)" should have the exact same param named "page"`
2. Your package does not allow you to use simple regular expressions.

there is no answer on StackOverflow where you sent me.

**Comment by Akryum** [comment]
Hey! A bug report is basically an actual behavior that doesn't match an expected (and documented) behavior. Your post is about questions on general usage of the library, not a bug. Please use the help channels [linked above](https://github.com/vuejs/router/issues/1530#issuecomment-1226784294) to get help on how to implement your routes using vue-router.

**Comment by weblabio** [comment]
thank you.
I understand what you're talking about, you made up the rules...
But, the **issue** the package is that it does not allow you to implement a simple and real task. 
You send me to the community where I came from with a question.Your rules don't work, don't solve problems, why is this all?
Vue is a tool for solving problems, vue-router is a package for Vue that solves routing problems and the fact that the package does not allow real tasks to be implemented is a **issue**. And what do you write - it's bureaucracy, time wasted, the problem remains :(

**Comment by Akryum** [comment]
> the fact that the package does not allow real tasks to be implemented

You can implement the routes you posted, there is no bug exposed here. Please use the channels linked to get help on how to implement your routes. This issue board is not the right place. Thanks a lot!

**Comment by e-han-cyber** [comment]
Hi @weblabio , you could have a look at [path-to-regexp](https://github.com/pillarjs/path-to-regexp).

**Comment by Atharparvez** [comment]
const handlepagechange = (page) => {
    setpagination(page);
    router.push(`/server/products1/?page=${page}`);
 };
but im getting in URL
 http://localhost:3000/server/products1?page=1 the forward slash is missing
