### ISSUE TITLE
Vue-router creates html anchor using empty space after word

### ISSUE THREAD

**Issue by chriswill** [vuejs/router#1533]
### Version
4.1.4

### Reproduction link
[jsfiddle.net/c4ok93n7/](https://jsfiddle.net/c4ok93n7/)

### Steps to reproduce
Following the eslint rule https://eslint.vuejs.org/rules/singleline-html-element-content-newline.html, create a link with router-link that has a punctuation after it, such as "?", "!", or "."

For example:
```
      <router-link to="/">
        Go home
      </router-link>?
```

The html that is created has spaces, which looks like this: 

```
<a href="/" class=""> Go home </a>
?

The space at the beginning of the word is not obvious, but there is a space between the word and the punctuation mark that is included in the hyperlink.  This is unattractive.

### What is expected?
The router would create a hyperlink that looks like this:
`<a href="/" class="">Go home</a>`
with no spaces.

### What is actually happening?
The router is creating a hyperlink that includes spaces and is unattractive.

The only way to avoid this is to break the [vue/singleline-html-element-content-newline](https://eslint.vuejs.org/rules/singleline-html-element-content-newline.html) rule

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by chriswill** [comment]
![image](https://user-images.githubusercontent.com/216290/186788808-3345b36e-2619-4d57-89a9-6982bd09ed00.png)

**Comment by posva** [comment]
This is just how HTML works.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!
