### ISSUE TITLE
Can we add 'href' as property to the type for Router.currentRoute

### ISSUE THREAD

**Issue by benkroeger** [vuejs/router#1541]
### What problem does this feature solve?
the `currentRoute` value is initially defined without `href` property (from `START_LOCATION_NORMALIZED`) but on Router.install() it is immediately overwritten with an object that ultimately comes from router.resolve() (which has return type `RouteLocation & { href: string }`.
So it appears to me that `currentRoute` (at runtime) almost always has the `href` property - which helps tremendously when composing urls in your application and working with a base other than `/` (e.g. to copy a complete and valid url to the clipboard).

Due to the fact that the initial value doesn't have `href` prop, one could ether make the `href` prop optional (in type definition) or extend `START_LOCATION_NORMALIZED` to have a `href` property (with initial value from 'fullPath') as well.

### What does the proposed API look like?
```ts
export interface Router {
  /**
   * @internal
   */
  // readonly history: RouterHistory
  /**
   * Current {@link RouteLocationNormalized}
   */
  readonly currentRoute: Ref<RouteLocationNormalizedLoaded & { href?: string }>
}
```

**Comment by benkroeger** [comment]
This is what the currentRoute looks like immediately after app initialization with `base = '/foo/'` and route `/question/:id`:

![image](https://user-images.githubusercontent.com/7782055/187704297-a9be27f8-db04-42d3-ae10-24be648be810.png)

**Comment by posva** [comment]
The lack of `href` is intended as it's only used in very specific places.

> which helps tremendously when composing urls in your application and working with a base other than / (e.g. to copy a complete and valid url to the clipboard).

What do you mean? Do you have concrete examples? It should be doable with `router.resolve()`

**Comment by benkroeger** [comment]
The ultimate goal is to receive the current URL from the browser (incl. origin) and overwrite the `hash` property.

You're right. This can be done with `router.resolve()`. Here is how I did it:

```ts
import { type RouteQueryAndHash, useRoute, useRouter } from 'vue-router';
const router = useRouter();
const currentRoute = useRoute();

const getCurrentRouteAsURL = (overrides: RouteQueryAndHash = {}) => 
  new URL(router.resolve({ ...currentRoute, ...overrides }).href, window.location.origin);
```

thanks for the hint.
