### ISSUE TITLE
Expressive routing with template-inlined Route elements

### ISSUE THREAD

**Issue by jez9999** [vuejs/router#1548]
### What problem does this feature solve?
The current Vue router requires that Vue components simply have a `<router-view></router-view>` element in order to render content that is determined by the router's configuration.  This decouples technologies, but it also decouples two very closely-related *concerns*: the components, and where/when they will be rendered.  In a large-sized SPA app, you may have hundreds of components, and only a tiny percentage of them will be rendered on a given rendering because the router is deciding what should be rendered.  It makes sense to have this very important information included in the component templates themselves.

### What does the proposed API look like?
Vue router should add React-router style inline route elements `BrowserRouter`, `Routes`, `Route`, and `Outlet`.  Thus, configuring routes could look something like this:

**App.vue**
```
<template>
    <BrowserRouter>
        <Routes>
            <Route path="/" component="Layout">
                <Route index component="Home" />
                <Route path="about" component="About" />
                <Route path="game/:gameId" component="PlayGame" />
                <Route path="highscores" component="HighScores" />
                <Route path=":pathMatch(.*)*" component="NotFound" />
            </Route>
        </Routes>
    </BrowserRouter>
</template>
```

**Layout.vue**
```
<template>
    <Navbar />
    <div class="container fancy-border">
        <Outlet />
    </div>
</template>
```

When looking at `Layout.vue`, one can easily see that `Outlet` will render the child content of the parent.  To figure out what will render there, you just look at the parent component which should be immediately obvious.  It may take some time to find that same route configuration in a separate router config object.

When looking at `App.vue`, you can immediately see what child components might get rendered, and the route that will trigger their rendering.  You can add a new route configuration directly from the parent component, instead of having this information separated in a different routing configuration file.

I think this is a much more expressive and natural way of defining routes.  Instead of seeing `router-view` and having to go examine a complex router configuration object, you can quickly see which components might be rendered as children of the current component, and the routes that will trigger that rendering.  It tightly couples these closely-related concerns, and is well worth implementing as an option for Vue router.

In addition, it comes with the side benefit that you can embed routes, so routes embedded underneath a given `<Route>` can use relative route paths to the parent route rather than worrying about the absolute path.

**Comment by posva** [comment]
Declarative routing is something that has been considered in the past but it turned out to have other downsides as well and being just another way of declaring routes. In react it might seem more natural but in Vue, we prefer it this way. However, the dynamic routing api allows to build such declarative API in userland. If you want to read more about this or maybe find what other users have created I think you should find the Dynamic Routing RFC in the Vuejs/rfcs repo useful

**Comment by jez9999** [comment]
@posva Yeah but why close this down instead of leaving it open as a possible option in the future?  The two could live side-by-side, allowing users to pick this as an option if they wanted.

Also, could you show me any links to the discussion on the downsides of declarative routing?  For me it's a very natural extension to the likes of `v-if`, which is already bundling logic on whether to render elements with the HTML markup itself.
