### ISSUE TITLE
Add option to fire beforeEnter per-route guard when path and/or query changes

### ISSUE THREAD

**Issue by sgpinkus** [vuejs/router#1551]
### Version
4.1.5

### Reproduction link
[jsfiddle.net/wpknr4yz/20/](https://jsfiddle.net/wpknr4yz/20/)

### Steps to reproduce
Currently beforeEnter will not be reevaluated when the path or query changes but the component is the same as stated in the doc -- https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard.

### What is expected?
beforeEnter should be reevaluated when ever the the path or query changes. 

### What is actually happening?
As above.

---

Why this?

  1. router.beforeEach is run whenever the path or query changes, so the behavior of befireEnter seems inconsistent.
  2. I believe it's more intuitive. A different path semantically represents a new resource, the logic in the beforeEnter is likely to be conditional on the semantic resource identity not the underlying component.
  3. It means beforeEnter can't be used for async data fetches required by the component reliably. I would like to do this as I think it achieves a better separation of concerns.

**Comment by posva** [comment]
This is intended. Use beforeEach instead.

**Comment by sgpinkus** [comment]
I know it's intended, it says so in the docs. But it doesn't say why. Why is it intended?

**Comment by sgpinkus** [comment]
FYI found a middleware that does it -- https://github.com/abellion/vue-router-shield. Would obviously prefer vue-router support though (still can't understand why against it, it's odd omission IMO).
