### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')     at __webpack_require__

### ISSUE THREAD

**Issue by 973240647** [vuejs/router#1555]
### Version
4.0.8

### Reproduction link
[segmentfault.com](https://segmentfault.com/q/1010000019069938)

### Steps to reproduce
1、Execute npm run build to package and deploy the online server
2、An error is reported after clicking the route menu, as shown below
TypeError: Cannot read properties of undefined (reading 'call')     at __webpack_require__

 Uncaught (in promise) Error:Couldn't resolve Qcomponent "default" at "/sbjh”  vue-router.esm-bundler.js:2043

TypeError: cannot read properties of undefined (reading 'call ')at_webpack_require__ (app.js : 85: 30)

at eval (vue-router.esm-bundler.js :2043;47)

at ./node_modules/cache-loader/dist/cjs.js ? !./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue- loader-v16/dist/index.js?!./src/views/project/component/lxxmTemplate/index.vue?vue&type-script&lang-js(31.js:83:1)

at_webpack_require_ (app.js:85: 30)at eval (index. vue:2:303)
at ./src/views/project/component/lxxmTemplate/index.vue?vue&type=script&lang=js(31.js:299:1)
at _webpack_require__ (aPp.js:85: 30)at eval (VM1514 index.vue:3:92)
at ./src/views/project/component/lxxmTemplate/index.vue (31.js:287:1)at_webpack_require__ (app.js:85:30)

3、The code was not modified, repackaged and deployed. After a period of time, it was found that the system could run normally, that is, no error was reported when clicking the route
4、Because some functions have been modified and repackaged for deployment, the problem this time is that the above error occurs after some routes are clicked. After a period of time, the system logs in again about 30 minutes later and finds that the operation is normal without error

### What is expected?
What causes the above problems and what modifications are needed

### What is actually happening?
An error is reported after clicking the route menu

---
I tried to delete the dependency, reinstall the package, and found related errors on the Internet, but they were not resolved very well

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
