### ISSUE TITLE
Cannot render RouterLink  in functional component  in SSR

### ISSUE THREAD

**Issue by Kaciras** [vuejs/router#1558]
### Version
4.1.5

### Reproduction link
[github.com](https://github.com/Kaciras/vue-router-issue)

### Steps to reproduce
Run `node ssr.js`

Navigate to http://localhost:5173/

### What is expected?
It should render the RouterLink component.

### What is actually happening?
```
TypeError: Cannot destructure property 'options' of 'vue.inject(...)' as it is undefined.
```

**Comment by posva** [comment]
Sorry, I can't reproduce the error. I noticed you are doing `attrs.to = ...`, note you should do `h(..., { ...attrs, to })` instead. 
I recommend you to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask further questions or provide a working reproduction.

**Comment by Kaciras** [comment]
I create a [CodeSandBox](https://codesandbox.io/p/github/Kaciras/vue-router-issue/master?file=%2FREADME.md) and it should work.
