### ISSUE TITLE
vue3的router4的addRoute0()功能添加路由后，router.push()操作后，页面路由菜单没有实时更新？

### ISSUE THREAD

**Issue by wenlongFam** [vuejs/router#1564]
### Version
4.1.5

### Reproduction link
[segmentfault.com](https://segmentfault.com/q/1010000042553244)

### Steps to reproduce
package.json
`"vue-router": "^4.1.4",`

下面是代码：

`  console.log(router.getRoutes());   //这里是array.length=10
  //添加系统3 路由
  router.addRoute('Duolianjixitong', {
    path: '/projectbrowsing/duolianjixitong/xitong/id=3',
    component: () => import('@/views/Projectbrowsing/duolianjixitong/xitong/systemTabShow.vue'),
    name: 'Xitong3',
    meta: {
      title: t('routers.xtyc3'),
    }
  })

  console.log(router.getRoutes());   //这里是array.length=11

  router.push("/projectbrowsing/duolianjixitong")  //这里是触发新的导航
`

这是router4官网的提示，
提示
请注意，添加路由并不会触发新的导航。也就是说，除非触发新的导航，否则不会显示所添加的路由。

### What is expected?
页面路由菜单实时更新addRoute()的路由。

### What is actually happening?
addRoute()添加路由数据后，getRoutes()数据值是正确的，但是页面菜单未更新？

---
请告诉一下addRoute()添加路由后，怎样才能页面菜单实时更新？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by Valar103769** [comment]
如果你跟我一样,菜单是通过原始的路由表生成的话, 不更新很正常, 因为getroutes返回的是扁平的数据, 只有静态路由那行的children下才有数据,而数据还是之前的

**Comment by wenlongFam** [comment]
addRoute()可以添加数据到路由里，菜单显示需要重新从路由里重新拿数据渲染菜单就对了。
