### ISSUE TITLE
Post flush watchers are re-executed when leaving suspended page

### ISSUE THREAD

**Issue by adamjedlicka** [vuejs/router#1565]
### Version
4.1.5

### Reproduction link
[jsfiddle.net/ocbx1hf7/1/](https://jsfiddle.net/ocbx1hf7/1/)

### Steps to reproduce
Post flush watchers are NOT re-executed in synchronous pages (expected behaviour), but when route component is wrapped in suspense, watchers from olde page are executed.

### What is expected?
When switching from Category 2 to Product 1 in the example, only "Product 1" should be logged in the console.

### What is actually happening?
When switching from Category 2 to Product 1 in the example, "Product 1" alongside with the "Category 1" from the old page are logged in the console.

**Comment by posva** [comment]
Opened

- https://github.com/vuejs/core/issues/6811
