### ISSUE TITLE
Separate routes are being created for routes that are children to the parent route

### ISSUE THREAD

**Issue by LittleWhiteLoti** [vuejs/router#1568]
### Version
4.1.5

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/hungry-mcclintock-4b9esh?file=/src/pages/Index.vue)

### Steps to reproduce
Look at the initial-routes.js in the src/routing/initial-routes.js.

### What is expected?
There should only be 2 routes. One for index and the other is tests. The child routes appear nested as they should.

### What is actually happening?
It is creating a separate route for each child in the test route. Along with the test route and children.

---
The problem that arises is when I go to remove them using router.removeRoute(someName). It deletes the child route which is now a root route when I really want to delete the child route inside the test route.

**Comment by posva** [comment]
This is expected and documented behavior for getRoutes(). The initial records children property are not changed because what matters is the flat structure
