### ISSUE TITLE
Support non-lineaer router

### ISSUE THREAD

**Issue by tachibana-shin** [vuejs/router#1573]
### What problem does this feature solve?
I'm using vue-router for a native application, which solves the routes when I use the tab. It looks like this https://ionicframework.com/docs/vue/navigation#non-linear-routing

### What does the proposed API look like?
https://ionicframework.com/docs/vue/navigation#non-linear-routing

**Comment by posva** [comment]
Cool idea! I don’t have the bandwidth to write such a library but with custom history and marcher you should be able to build this yourself and plug it into the router 👍

**Comment by tachibana-shin** [comment]
How can i do so? i need something that looks like `onMounted` with all routes when vue-router transitions is there any such API?

**Comment by tachibana-shin** [comment]
> Cool idea! I don’t have the bandwidth to write such a library but with custom history and marcher you should be able to build this yourself and plug it into the router 👍

How can i do so? i need something that looks like `onMounted` with all routes when vue-router transitions is there any such API?
