### ISSUE TITLE
support convention routing

### ISSUE THREAD

**Issue by Mr-try** [vuejs/router#1576]
### What problem does this feature solve?
Conventional routing greatly improves development efficiency
although some package support this feature，it is not perfect.（ vue-auto-routing looks not support pass parameters）

### What does the proposed API look like?
 convention routing feature default open & some rules like this:
1、file views/about equal  router about
2、file views/useInfo/[id]  equal  router useInfo/:id
...

**Comment by posva** [comment]
Use https://github.com/posva/unplugin-vue-router

I will at some point open an RFC to maybe make it official
