### ISSUE TITLE
Lazy loaded routes fail to load after deployment

### ISSUE THREAD

**Issue by domnantas** [vuejs/router#1580]
### Version
4.1.5

### Reproduction link
[https://github.com/domnantas/lazy-routes-after-deployment-bug](https://github.com/domnantas/lazy-routes-after-deployment-bug)

### Steps to reproduce
- Use lazy loaded routes
- Run `npm run build`
- Run `npm run preview` (simulating production deployment)
- Open browser, navigate to the preview Home route
- Make changes to `AboutView.vue` (add text to `template` for example)
- Run `npm run build`
- In the same browser window click `About` link

### What is expected?
Browser should navigate to About route

### What is actually happening?
Nothing happens and `Failed to fetch dynamically imported module` error is thrown.

---
I understand this is not really a _vue-router_ issue, but I don't know where else to post it. It happens because `AboutView` bundle hash gets updated. It is not a great experience when users are interacting with the application, application gets deployed, and that causes navigation between routes to completely break and the only fix is browser refresh. The only possible fix I can see is to disable lazy loaded routes, but that would cause large main bundle sizes for applications that have multiple large routes. Here's a related [stackoverflow question](https://stackoverflow.com/questions/69300341/typeerror-failed-to-fetch-dynamically-imported-module-on-vue-vite-vanilla-set)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can use a global `router.onError()` to detect these and reload the page so it fetches the new js bundles

**Comment by domnantas** [comment]
Thanks! I see some significant drawbacks with reloading in `router.onError()` (losing state and staying on the same page on the first click), but I agree that GitHub Issues isn't the right place for this discussion.

[Posted on the forums](https://forum.vuejs.org/t/lazy-loaded-routes-fail-to-load-after-new-build-deployment/133136)
