### ISSUE TITLE
router api文档错误

### ISSUE THREAD

**Issue by hugselina2019** [vuejs/router#1584]
### Version
4.1.5

### Reproduction link
[router.vuejs.org/zh/api/](https://router.vuejs.org/zh/api/#addroute)

### Steps to reproduce
怎么有两个addRoute....

### What is expected?
有两个 重复了

### What is actually happening?
正常展示

![7ec084ff968db1e9936e40b71c01664](https://user-images.githubusercontent.com/20763416/196584932-b89c5a2b-db14-4ccc-a657-41889d40f5ad.jpg)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by posva** [comment]
They are functions overloads

**Comment by hugselina2019** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Thank you for answering
