### ISSUE TITLE
State of back/forward navigation

### ISSUE THREAD

**Issue by holtwick** [vuejs/router#1587]
### What problem does this feature solve?
It is possible to use `router.back()` and `router.forward()` to programmatically navigate. But I was not able to find a state that tells, if this navigation is possible or not. This would be required to create a custom back/forward navigation in a headless browser, where buttons would be disabled if no navigation would be possible.

### What does the proposed API look like?
API could look like `router.canNavigateBack()` and `router.canNavigateForward()`.

**Comment by posva** [comment]
Unfortunately, this is an API limitation of the History API. You can implement a userland version of it by keeping track of the different calls to the router but there is no plan to add a native API for this.

However, this should be possible with the upcoming Navigation API

**Comment by holtwick** [comment]
Ok, I see. Thanks @posva for the feedback.

**Comment by holtwick** [comment]
In case somebody is looking for a solution to this problem, this *hack* works for me:

```js
const state  = reactive({
  forward: false,
  back: false,
})

window.addEventListener('popstate', (event) => { 
  state.back = event.state.back != null
  state.forward = event.state.forward != null
})

router.afterEach((to, from, failure) => { 
  state.back = true
  state.forward = false
})
```
