### ISSUE TITLE
SSR - Doing router.push(req.url) without await right before router.isReady() sometimes resolves before it is ready

### ISSUE THREAD

**Issue by iPrytz** [vuejs/router#1591]
### Version
4.0.15

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/guide/migration/index.html#new-history-option-to-replace-mode)

### Steps to reproduce
On node server is: 
```
router.push(req.url) // fething data inside async navigation guards 
await router.isReady() // navigation never happens

 const html = await renderToString(app, ctx)

// html is rendered without any data
```
This is a weird case, and it happens only some times.. 
But i have logging inside each navigation guard, and in about 1/20 cases it never output any logs and the html i get back is without any fetched data.  

### What is expected?
To await until data is loaded in the navigation guards

### What is actually happening?
It skips the navigation, and I get no logs indicating a navigation happen  

---
This is roughly whats inside the navigation guards.
```
  router.beforeEach((to) => {
    log('router beforeEach',)
  })
  
  router.afterEach((to) => {
    log('router afterEach')
  })
  
  router.beforeResolve(async (to, from) => {
    log('router beforeResolve')
    const { redirectUrl, statusCode,} = await getData(to.name)
    // ... Handle redirect etc
  })
```
I read about putting await before router.push, but the documentation never mention that it is needed in this case.

**Comment by posva** [comment]
I can't do much without a boiled down reproduction. If you manage to reproduce it, please open a new issue.

**Comment by iPrytz** [comment]
Ok, I'll see if I can reproduce it in sandbox. But am I supposed to use await on router.push before router.isReady()? because the documentations says nothing about it.
