### ISSUE TITLE
iframe refresh BUG when using Vue Router API beforeRouteLeave to prevent browser's native back behavior

### ISSUE THREAD

**Issue by BurstLinker996** [vuejs/router#1592]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/laughing-forest-okcmmr?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
In Xiaomi/Samsung browsers, when a webpage with an Iframe uses "VUE - beforerouterleave", it can only prevent the webpage from refreshing, but the Iframe will automatically refresh

Example, click "Demo page2" in "Demo page1" and enter into "Demo page2", then click "back button" in xiaomi/Samsung browser, you will find that the “countdown” refresh to 999 seconds

### What is expected?
Both the website and iframe content in the website can remain the previous status when we use VUE -- beforerouterleave

### What is actually happening?
When we test in Samsung/XiaoMi browsers, only website remain the previous status and Iframe content in the website will refresh when we use VUE -- beforerouterleave

**Comment by posva** [comment]
Unfortunately, this is a browser limitation: an iframe influences its parent history by also pushing/removing entries so you end up having two router instances but only one single history track. You need to find a way that matches your use case and allows you to control them independently
