### ISSUE TITLE
console.log(to.params)  // params will lose 

### ISSUE THREAD

**Issue by Verdicts-ye** [vuejs/router#1593]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/flamboyant-satoshi-83tc9q?file=/src/App.vue)

### Steps to reproduce
router.push({name:'pages',params:{key:value}})

router.beforeEach((to, from, next) => {
 console.log(to.params)  // params will lose  ,  this problem did not occur in V 4.1.3 ,when I upgrade to 4.1.6 has this problem
}

### What is expected?
Object.keys(to.parmas).length !=0

### What is actually happening?
Object.keys(to.parmas).length==0

**Comment by posva** [comment]
This is explained in the change log
