### ISSUE TITLE
Path with same name gets overwritten

### ISSUE THREAD

**Issue by Nevah5** [vuejs/router#1596]
### Version
4.1.6

### Reproduction link
[gist.github.com](https://gist.github.com/Nevah5/5453df59d5b7c6315c85afe103ecb227)

### Steps to reproduce
You can find everything on the gists link provided.
Here is also the stackoverflow issue on what I've tried https://stackoverflow.com/questions/74282811/vue-router-4-path-with-same-name-gets-overwritten

### What is expected?
I should be able to access localhost:8080/gallery/231.

### What is actually happening?
I guess that the /admin/gallery child somehow overwrites the /gallery/:id route, because if you swap them around, so that /admin/gallery comes first, the /gallery:id route works but not the admin one.

---
I hope this is not my mistake, else I am very sorry. But the documentation didn't help and it looks like I did everything correctly.

**Comment by posva** [comment]
Names are unique so this is expected.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!
