### ISSUE TITLE
getRoutes can return not flatten routes? like as RouteRecordRaw? 

### ISSUE THREAD

**Issue by Valar103769** [vuejs/router#1597]
### Version
4.1.6

### Reproduction link
[router.vuejs.org/zh/api/](https://router.vuejs.org/zh/api/#routerecordraw)

### Steps to reproduce
Does anyone really need a flat route?

bad api design, has one agreen ?

### What is expected?
Does anyone really need a flat route?

### What is actually happening?
Does anyone really need a flat route?

**Comment by posva** [comment]
This has been explained in other issues. Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
