### ISSUE TITLE
Strange things are happening with nuxt 3

### ISSUE THREAD

**Issue by Maxp777** [vuejs/router#1599]
### Version
4.1.6

### Reproduction link
[www.veed.io](https://www.veed.io/view/642fb7b0-49ad-4f11-b73a-4352f2e1022c)

### Steps to reproduce
Not navigate login and register page, only if type direct link to login page and when i can go to register page and back to login page.

### What is expected?
Open the requested page

### What is actually happening?
console log message thousand times

**Comment by Maxp777** [comment]
https://github.com/nuxt/framework/issues/8724#issuecomment-1304541517

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
