### ISSUE TITLE
Vue Router breaks Hot Reload with circular Router references

### ISSUE THREAD

**Issue by RickStrahl** [vuejs/router#1601]
### Version
4.1.6

### Reproduction link
[github.com](https://github.com/RickStrahl/vue-router-circular-reference-hot-reload-bug)

### Steps to reproduce
Link contains stock CLI Vue project with vue-router. I've modified the `HomeView.vue` to `import` and reference the vue router in order to navigate to another page off a button. 

This all works with standard navigation.

However, now open the console with the HomeView open, then make a change to the page which should trigger hot-reload to attempt to reload the page. 

Instead an error occurs and the page does not actually reload:

![image](https://user-images.githubusercontent.com/1374013/200486114-8bb355e6-d247-4dae-bcfd-0d9b3217470a.png)

Now remove the `import router` and the `router.push()` call from the page.

Make another change - now hot reload works. Add it back in... boom.

### What is expected?
Hot reload should work when router is imported and referenced.

### What is actually happening?
Hot reload fails when any router referenced component or sub-component is reloaded.

**Comment by posva** [comment]
use `useRouter()` instead of importing the router, it avoids circular dependencies which is a problem out of the router's scope.
BTW: your reproduction link seems private
