### ISSUE TITLE
Matched Params error

### ISSUE THREAD

**Issue by xjccc** [vuejs/router#1603]
### Version
4.1.6

### Reproduction link
[paths.esm.dev/](https://paths.esm.dev/?p=AAMeJRyAwQkYLKbA0AcAF2DtNBPbGUABAkMLiLZB5RdAgQ..&t=/price_123_234#)

### Steps to reproduce
price_[nid]_[sid].vue

### What is expected?
/price_123_456
{nid: 123, sid: 456}

### What is actually happening?
{ "nid_": "1", "sid": "23_456" }

**Comment by posva** [comment]
This is expected, use a regex to limit what can be matched [example](https://paths.esm.dev/?p=AAMeJRyAwQkYLKbA0AcAF2DtABMHUAFLBKhAo2xngAIFhhYQbYM48irGoNI.&t=/price_123_234#)
