### ISSUE TITLE
linkActiveClass not working as expected after upgrade from 4.1.5 to 4.1.6 anymore

### ISSUE THREAD

**Issue by Kirsten-G** [vuejs/router#1608]
### Version
4.1.6

### Reproduction link
[too-complicated-to-recreate-for-just-reporting-this-issue](http://too-complicated-to-recreate-for-just-reporting-this-issue)

### Steps to reproduce
Upgrade from 4.1.5 to version 4.1.6

### What is expected?
Top level menu is highlighted when a sub-menu item is active.

### What is actually happening?
After upgrading to version 4.1.6 top level menu is not highlighted anymore when sub-menu is active. 

---
It is too complicated to sign-up on one of those sandboxes just to report this issue.

**Comment by posva** [comment]
Can't do much without a repro but this is very likely linked to https://github.com/vuejs/router/commit/756f755731284f0f1899a2f8b62cb074b6f0f842

Remember to use the [forum](http://forum.vuejs.org/), Discussions (here) or the [Discord chat](https://chat.vuejs.org/) to ask questions!
