### ISSUE TITLE
router.push('.') consistency between router for vue3 and vue2

### ISSUE THREAD

**Issue by young-zy** [vuejs/router#1620]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/gallant-knuth-0bhk47?file=/src/views/FooBar.vue)

### Steps to reproduce
When current path is "/#/foo/bar", invoking $router.push('.') leads path to "/#/foo/."

### What is expected?
In vue2, same code leads to "/#/foo".     
vue2 example here: https://codesandbox.io/s/vue-2-playground-forked-4ifi8v?file=/src/App.vue

### What is actually happening?
path leads to "/#/foo/."

---
Is this an undefined behavior and wouldn't be fixed in future versions?
If so, what is the correct way to implement "step up one level" of current route("/foo/bar" to "/foo", not "/foo/", there may be params in path)?

**Comment by posva** [comment]
This is not really documented but it should work. As a workaround, make sure to add the trailing `/` when using `.` or `..`: `router.push('./')`

**Comment by young-zy** [comment]
> This is not really documented but it should work. As a workaround, make sure to add the trailing `/` when using `.` or `..`: `router.push('./')`

Using router.push('./') is not a propper workaround.


https://codesandbox.io/s/gallant-knuth-0bhk47?file=/src/views/FooBar.vue

**Comment by posva** [comment]
ah, then you want `../`

**Comment by young-zy** [comment]
> ah, then you want `../`

not really, there seems to be more inconsistency.

invoking "router.push('../')" from "/foo/bar/foobar" ends up "/foo/"
invoking "router.push('../')" from "/foo/bar" ends up to "/foo"
invoking "router.push('../')" from "/foo/bar/" ends up to "/foo/"
invoking "router.push('./')" from "/foo/bar" ends up to "/foo/"

https://codesandbox.io/s/gallant-knuth-0bhk47?file=/src/views/FooBarFooBar.vue

**Comment by young-zy** [comment]
I've found a possible workaround.
Make all path in routes end with trailing slash('/') , then use the router.push('../') to go up one level. This should work as expectation.

example
https://codesandbox.io/s/wonderful-cdn-lf1il9?file=/src/router.js
