### ISSUE TITLE
can't use /:pathMatch(.*)* to match 404

### ISSUE THREAD

**Issue by Valar103769** [vuejs/router#1626]
### Version
4.1.6

### Reproduction link
[github.com](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js)

### Steps to reproduce
```js
{ path: '/:pathMatch(.*)*', name: 'NotFound', component: NotFound }, // it can't work if your  route generated by addRoute  when refresh page

=> 
{
    path: '/(.*)*', // it can work if your  route generated by addRoute 
    name: 'NotFound',
    component: NotFound,
  }
```

or don't push  end of the routes

### What is expected?
into correct page 

### What is actually happening?
if has async addRoute(),  into 404 when refresh 

---

routes difine is same as vue-element-admin,and 404 route is end of routes
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/router/index.js

addRoutes is in permission

**Comment by posva** [comment]
Hello, make sure to always provide a reproduction that follows the instructions at https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro.

Open a new issue with a reproduction that follows those instructions if you manage to create a boiled down reproduction.
