### ISSUE TITLE
addRoute If more than 11 routes are dynamically added, the first added route will be invalidated by directly accessing the url

### ISSUE THREAD

**Issue by wangronglei** [vuejs/router#1643]
First of all sorry, my English is not good

### Version
4.1.6

### Reproduction link
[github.com](https://github.com/wangronglei/vue3-demo.git)

After packaging in our project, it is normal, and this problem will occur in the development mode

### Steps to reproduce
npm install
npm start

Clicking view1 to view13 is normal, but directly accessing "http://localhost:8080/view1" will appear "[Vue Router warn]: Unexpected error when starting the router: Error: Infinite redirect in navigation guard", the page will not appear.

You can add or delete "router.beforeEach(dynamicLoad(View13Router))" in the code [router/index.js], and you will find that it has something to do with the number. If there are more than 11, this problem will occur in the first added route. This problem occurs with the first two routes of the 12.

### What is expected?
Direct access to "http://localhost:8080/view1" page appears

### What is actually happening?
[Vue Router warn]: Unexpected error when starting the router: Error: Infinite redirect in navigation guard

**Comment by posva** [comment]
I think the problem comes from https://github.com/wangronglei/vue3-demo/blob/main/src/common/dynamic-load/index.js#L17, it makes no sense to redirect to the same location we are going to, instead, return true. That's what the warning is telling you.

**Comment by posva** [comment]
BTW, you should call `router.push()` when adding new routes if you want to take them into account for the navigation and cancel the existing navigation.

More at https://router.vuejs.org/guide/advanced/dynamic-routing.html#dynamic-routing, usu

**Comment by wangronglei** [comment]
> BTW, you should call `router.push()` when adding new routes if you want to take them into account for the navigation and cancel the existing navigation.
> 
> More at https://router.vuejs.org/guide/advanced/dynamic-routing.html#dynamic-routing, usu


Thank you for your reply
