### ISSUE TITLE
Missing `to` props shouldn't crash app

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/router#1648]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/p/sandbox/lingering-dream-7dbpxn?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A32%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A32%2C%22startLineNumber%22%3A2%7D%5D)

### Steps to reproduce
Create a Vue app with Vue-router.
Add `<router-link>Test</router-link>` to the template.

### What is expected?
The app should not throw a fatal error and crash.
Why isn't the behavior like the`<a>` HTML tag ?
Render a link that is not clickable, or render a link to the `/` route by default ?
This should be a console warning.
I often use link without target when developing and I don't have yet created the other page component or if I don't yet know the final destination of the link.

### What is actually happening?
The app will crash with error `Missing required props to`

**Comment by posva** [comment]
A code with a missing required prop should never go into production because the component is requesting that prop in order to function correctly. This is why you see both the warning and a crash, it's much easier to spot during dev that silently failing and producing a wrong behavior.

**Comment by mrleblanc101** [comment]
This doesn't match the `<a>` which still work even if it has no destination.

**Comment by posva** [comment]
A and RouterLink might be use for similar things but they serve different purposes an RouterLink doesn’t replace A, so it’s normal for their behavior to differ
