### ISSUE TITLE
useRouter returns undefined in production SSR

### ISSUE THREAD

**Issue by duannx** [vuejs/router#1651]
### Version
```
"vue": "3.2.45",
"vue-router": "4.1.6"
"vite": "4.0.4"
```

### Reproduction link
[github.com](https://github.com/duannx/vue-router-ssr-test)

### Steps to reproduce
- Clone the repository https://github.com/duannx/vue-router-ssr-test
- Install dependencies `yarn`
- Build for production `yarn build`
- Run production version `yarn serve`
- Open the app on the browser http://localhost:6173
- Now you can see in the terminal of the nodejs server the error as follow: `TypeError: Cannot read properties of undefined (reading 'afterEach')`

### What is expected?
`useRouter` returns the correct router that is injected in Vue 

### What is actually happening?
`useRouter` returns `undefined` despite it being called on the setup function

### Other information
- The error comes from my package https://github.com/duannx/vue-router-transition
```js
setup(props) {
    const router = useRouter();
    router.afterEach((to, from) => {
       ...
   })
}
```
- I notice that my package uses the file `vue-router.prod.cjs`. But if I call `useRouter` directly in `App.vue` it uses the file `vue-router.mjs`. It might lead to the use of another instance of Vue
- The error does not happen on dev env
- The error does not happen on the browser in both the dev and production

I'm not sure if it is the problem of `vite` or `vue-router` or my package itself but the issue can happen with any package that uses `vue-router` inside it.

**Comment by posva** [comment]
If this happens just within your package, it's unlikely to be a bug of vue router (even though, in theory, it could be coming from a misconfiguration in the package).

Maybe you need to add an [alias](https://vitejs.dev/config/shared-options.html#resolve-alias) to your vite config to force the version of vue router being used

Apart from that, the only help I can give here is to make the extensions of the js files consistent: cjs.js -> .cjs and es.js -> .mjs. This changes what files are required/imported by node at runtime.

**Comment by duannx** [comment]
@posva Thank you for your suggestion. 

I tested (locally) changing the file extension `cjs.js -> .cjs` and `es.js -> .mjs ` and update my `package.json` accordingly but the error still persists

But it points me in the right direction. My package is lacking the `exports` statement. It just contains the module definition:
```
  "main": "dist/index.cjs",
  "module": "./dist/index.mjs", <--- nodejs is ignoring it
```
So when building app in SSR mode, vite 4 uses import instead of require
```
import { useRouter } from "vue-router";              <-- this will use vue-router/dist/vue-router.node.mjs
import { RouterViewTransition } from "my-package";   <-- this will use my-package/dist/index.cjs that uses require inside it and point to vue-router/dist/vue-router.prod.cjs
```

Adding  `exports` to my `package.json` will solve the problem
```
"exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./index.cjs"
    }
  },
```

But I am still concerned that what happens with other packages that only support `cjs`. It will fail absolutely. And I believe that some packages that support es modules will have mistakes like mine. 

So is there anything that we can do in `vue-router` to make it works with any package without explicit configuration?

**Comment by posva** [comment]
> But I am still concerned that what happens with other packages that only support cjs. It will fail absolutely. And I believe that some packages that support es modules will have mistakes like mine.

Yes, that's one of the issues of ESM/CJS with node and therefor SSR apps 😓 

> So is there anything that we can do in vue-router to make it works with any package without explicit configuration?

I don't think so, authoring npm packages is more complicated than before for reasons like this.

One idea that might be worth exploring is exporting symbols in a common chunk when bundling vue, vue-router, and other libraries like pinia to make them more robust to this but other problems might arise later on, ending up in unncessary complexity for nothing
