### ISSUE TITLE
The css animation attribute acts on the root dom of the vue file, and cannot be successfully switched when switching routes

### ISSUE THREAD

**Issue by smartisantt** [vuejs/router#1652]
### Version
4.1.5

### Reproduction link
[codepen.io](https://codepen.io/Ashleyququ/pen/vYaXMgj)

### Steps to reproduce
1. vue template has   router-view> transition>keep-alive
2. when a vue file root dom with animation attribute
3. vue router don't work

### What is expected?
vue router should work

### What is actually happening?
vue router don't work

**Comment by posva** [comment]
Your repro is importing the node vue router version, it's normal it doesn't run.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!
