### ISSUE TITLE
How to obtain the previous record?

### ISSUE THREAD

**Issue by xiaozhuclassmate** [vuejs/router#1654]
### What problem does this feature solve?
I now have a problem. For example, I opened a page from the browser, but I don't know whether the current page is the first page I entered. It is invalid for me to use router.back. I hope there is a place to get whether the previous record exists, so that I can know that the current page is the first matching page，At present, I haven't found the relevant api to solve this problem.

### What does the proposed API look like?
I hope you can provide an API or a parameter, or if the  backfails, return a false message to let me know that I cannot go back.
- back() : boolean

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

See https://github.com/vuejs/router/issues/1647#issuecomment-1368286928

**Comment by xiaozhuclassmate** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
> 
> See https://github.com/vuejs/router/issues/1647#issuecomment-1368286928


Ok
