### ISSUE TITLE
Scroll to top from Footer does not work

### ISSUE THREAD

**Issue by HegeBa** [vuejs/router#1657]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/loving-cori-5znj46)

### Steps to reproduce
1. Open the following page: https://healthb-no.web.app/brukervilkar
2. Scroll down to the bottom of the page and click "Brukervilkår" from the footer
3. Repeat this at least three times

OR 
1. Open the minimal reproduction: https://codesandbox.io/s/loving-cori-5znj46
2. Scroll down to the bottom of the page and click "About" from the footer
3. Repeat this at least three times

### What is expected?
The page should always open at the top of the page, unless otherwise specified

### What is actually happening?
Sometimes it opens at the top, sometimes it opens at the bottom, and other times it scrolls to what seems to be a totally random location

---
I am using RouterLinks
```
<RouterLink to="/personvernerklaering">Personvernerklæring</RouterLink><br />
<RouterLink to="/brukervilkar">Brukervilkår</RouterLink>
```

```
and scrollBehaviour as indicated in documentation:
  scrollBehavior(to, from) {
    if (to.hash) {
      return {
        el: to.hash,
        top: 60,
        behavior: "smooth",
      };
    } else {
      return { top: 0 };
    }
  },
```

I am using Bulma CSS, which has some overflow classes, that, according to other articles I have read, might influence the Vue scroll behavior. However, I have tried to remove CSS altogether and even tried a completely new and clean Vue3 installation. I still get the same result, so it's not CSS, and nothing particular about my setup either. 

It happens consistently when trying to create RouterLinks from the bottom of the page.

**Comment by posva** [comment]
Cannot reproduce on the minimal reproduction. What browser are you seeing the issue on?

**Comment by HegeBa** [comment]
Chrome, Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by HegeBa** [comment]
Hah, I think I figured it out. 
It seems to take "overflow" scrolling from the previous page and applying it to the next one.

If I scroll really fast to the bottom of the page with the mouse wheel, that scrolling will continue after I click the RouterLink for whatever pixels it couldn't scroll on the original page.

If I use the scrollbar handle and scroll slowly, the problem does not occur.

So patient users that actually read your site instead of scrolling past everything will not encounter this issue, but I would still consider it to be a bug.

That explains why this problem seems to be so incredibly finicky in all the various forums I read with people having problems with the Vue Router scroll behavior.

**Comment by posva** [comment]
Thanks for the confirmation
