### ISSUE TITLE
[Contributing Guide bug] pnpm build fails on Apple M1 Pro

### ISSUE THREAD

**Issue by subdavis** [vuejs/router#1661]
### Version

router version: commit 0cc849d88113e925fe5ccfe3e5e74d509f3f709c
pnpm version 7.24.3
node version v18.12.1
**OS: MacOS 13.1 (22C65) (M1 Pro)**

**Note**: Someone else has tested for me on a 2020 M1 and build works for them.  I'm less confident that this is a hardware issue now, but I still can't think of anything strange or special about my environment configuration.

### Reproduction link

[github.com/vuejs/router](https://github.com/vuejs/router)

### Steps to reproduce

Using a MacBook with an M1 Pro processor:

* `pnpm install`
* `pnpm build`
* See error

This issue is related to https://forum.vuejs.org/t/vuejs-router-pnpm-build-fails-on-apple-m1-pro/134934

I opened that topic first, but I believe this is a bug in the contributing guide for M1 Pro users.  Following that guide does not result in a functioning development environment.

### What is expected?
`pnpm build` should succeed

### What is actually happening?
build throws `ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL`

**Comment by posva** [comment]
I can't reproduce using node 16 nor 18 and pnpm 7. Please let me know if you manage to find where the problem comes and if there is anything to improve in the contribution guide 🙂
