### ISSUE TITLE
After using the transition in router-view, the scrollBehavior in vue-router is invalid

### ISSUE THREAD

**Issue by trry-github** [vuejs/router#1663]
### Vue version

3.2.45

### Link to minimal reproduction

https://github.com/trry-github/issue/tree/scrollBehavior

### Steps to reproduce

1. Switch the route to about and scroll a certain distance
2. Switch the route to home
3. Use the Back button of the browser to return
4. The scroll position of the about page is not maintained, but the savedPosition value is normal

```
app.vue
<router-view v-slot="{ Component, route }">
    <transition name="main" mode="out-in" appear>
      <component :is="Component" :key="route.fullPath" />
    </transition>
  </router-view>


router.ts
scrollBehavior(to, from, savedPosition) {
    console.log('%c [savedPosition]', 'font-size:15px; color:#42b983;', savedPosition)
    if (savedPosition) {
      return savedPosition
    } else {
      return { top: 0, left: 0 }
    }
  }

```

1. After cancelling transition, everything is fine

![Kapture 2023-01-12 at 20 02 17](https://user-images.githubusercontent.com/67309192/212063761-608632be-c777-47dd-ba01-d01da58eaad9.gif)

### What is expected?

The expectation is that, while using the transition, the scrollBehavior will also hold the scrolling position normally

### What is actually happening?

During transition, the scrollBehavior cannot keep the last page scroll position

**Comment by LinusBorg** [comment]
https://router.vuejs.org/guide/advanced/scroll-behavior.html#delaying-the-scroll
