### ISSUE TITLE
Pipe characters is not encoded in query parameter

### ISSUE THREAD

**Issue by ltshb** [vuejs/router#1666]
### Version
4.1.6

### Steps to reproduce
In the `stringifyQuery` method the `|` pipe character is not encoded. The issue with non encoded pipe characters rise  with some tools like for example JIRA hyperlink which won't work correctly if the hyperlink contains a pipe character (pipe in JIRA wysiwyg is reserved as separator). 

### What is expected?
From the URI spec `|` are not allowed and should be encoded.

### What is actually happening?
Pipe characters are not encoded

---
I'm wondering why vue router explicitly don't encode `|` ? see https://github.com/vuejs/router/blob/30002aa62130139b81530083f1393bd367160dd2/packages/router/src/encoding.ts#L61

**Comment by ltshb** [comment]
@posva here is an example of a link with pipe that don't work in jira:

https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML||https:%2F%2Fpublic.geo.admin.ch%2Fapi%2Fkml%2Ffiles%2FT27O2qmORYqWL80FyHDsyQ

NOTE: once open in the browser the pipe will get automatically encoded by the javascript application once open, but if you try to add this link in JIRA it will not take the whole string as hyperlink but only the first part until the first pipe.

I'm actually working on a replacement of https://map.geo.admin.ch, the new application is using Vue 3 and Vue Router and I had the issue with the pipe not being encoded and couldn't add proper link in our internal jira to our internal test server. I've copied the Vue router implementation and removed the pipe decoding to solve my issue, see https://github.com/geoadmin/web-mapviewer/pull/348. 
So I'm really wondering why this issue did not came before. 
Also looking at the URL RFC https://www.rfc-editor.org/rfc/rfc3986#section-3.4 (which is quite old) we can see that pipe is not part of the allowed characters. Its seems that implementation of `URL` allow it but I could not find any spec that specify that it is allowed. I don't know if other tool have the same issue with pipe in an URL, probably confluence.

**Comment by posva** [comment]
Ah I see, thanks! Oo that's a Jira bug (or feature if they did it on purpose 😆 ). It's great you managed to find a workaround for your use case.

That RFC is indeed outdated. The spec is https://url.spec.whatwg.org/

Note that in future versions we are likely to use the official URL constructors to encode/decode URLs as they start to get better support among browsers
