### ISSUE TITLE
Vue router can not update query string that is an array

### ISSUE THREAD

**Issue by duannx** [vuejs/router#1667]
### Version
4.1.6

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-4h126e?file=src%2FApp.vue,package.json,src%2Frouter.ts,src%2Fpages%2FHome.vue,src%2Fmain.ts&terminal=dev)

### Steps to reproduce
Visit this link https://vitejsvite4h126e-obnz--5173.local-credentialless.webcontainer.io/?test=1&test=2

### What is expected?
The query string should be updated to `?test=1&test=2&test=3` after the App mounted

### What is actually happening?
The query string stays at `?test=1&test=2`

---
Let's consider the code:
```js
onMounted(async () => {
  const testQuery = route.query['test'];
  testQuery.push(3);
  router.replace({
    query: {
      test: testQuery,
    },
  });
});
```
This code should update the page's query string to `?test=1&test=2&test=3` but it does not.

The reason is that `vue-router` [check the same route location](https://github.com/vuejs/router/blob/0cc849d88113e925fe5ccfe3e5e74d509f3f709c/packages/router/src/router.ts#L672) to avoid pushing.

This line takes the current route query as value but javascript treats it as a reference
```js
const testQuery = route.query['test'];
```
So when pushing to `testQuery`, we actually push to `route.query.test`. So, `isSameRouteLocation` will return true because it compares the same object.

The issue can be fixed easily by cloning the route query when using it 
```
const testQuery = [...route.query['test']]
```

But I don't think it is a good solution. Because it requires the developer to have awareness of this issue and it's not natural behavior. I spent hours debugging this issue. 

My suggestion is to prevent the issue from `vue-router` side. Maybe we should add a getter to `router.query` to export cloned object only

**Comment by posva** [comment]
The route object is read only, you **have to clone the query**. Creating a copy each time you read the query would be very bad for performance.

IMO a more natural way of writing this is:

```ts
router.replace({
    query: {
      test: [...route.query.test, 'test2']
    },
  });
```

Which avoids the problem altogether. If you think the fact the route query (and params) is readonly should be somewhere document, I'm open to PR suggestions 😀 
In the past, I tried setting these properties as readonly arrays but it created other problems when dealing with TypeScript in application code that made it difficult to work with.

**Comment by duannx** [comment]
@posva What do you think about exporting a function to get the cloned version of the route query only and adding it to the docs? Another common mistake that developers mutate directly to query objects like following: 
```js
const query = route.query;
  query.someField = '1';
  router.replace({
    query,
  });
```
Another approach is to make `router.query` as a computed object. I think it will not hurt the performance
