### ISSUE TITLE
Vue Router catching routes to static assets

### ISSUE THREAD

**Issue by GuibertLo** [vuejs/router#1671]
### Version
4.1.6

### Reproduction link
[jsfiddle.net/oaLx4tbg/3/](https://jsfiddle.net/oaLx4tbg/3/)

### Steps to reproduce
Define Vue Router and its routes, and integrating it to the Vue application.

### What is expected?
Serve the different views only

### What is actually happening?
The static assets, stored in the /public folder, is catched by Vue Router and the application displays a page with an empty router-view. If the page is refreshed with ctrl+maj+r, the static asset from the public folder is displayed.

**Comment by posva** [comment]
Static Assets are unrelated to Vue Router, you need to configure your server to handle the static assets (although most servers handle this out of the box).

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://chat.vuejs.org/) to ask questions!

**Comment by GuibertLo** [comment]
@posva Thank you very much for your help. However, I feel like my Nginx configuration is appropriate; I tried multiple ones before and did not see any difference Here is the only location rule I have in my virtual host:
```
location / {
        try_files $uri $uri/ /index.html;
}
```
Thank you again!

**Comment by mrjackwills** [comment]
Can confirm am having exactly the same issue;

visiting `http://www.example.com/letter.pdf` works perfectly, opens up in the browser pdf viewer, but having a `<a class='href' href='http://www.example.com/letter.pdf' target='_blank' rel='noopener noreferrer'>download CV as pdf</a>`, the vue-router takes over, and instead redirects to the error page.

My vue-router has this, to catch errors, 
```typescript
{
    path: '/:pathMatch(.*)*',
    component: () => import('@/views/ErrorView.vue')
},
```

My idea was to add something to the path here to ignore .pdf's, but I'm not sure how that would be formed

**Comment by mrjackwills** [comment]
> I will leave here my solution to fix this problem if anyone has the same one. I tried a lot of different fixes, and I found one that worked. I noticed that the issue was coming from the history of Vue Router, which is odd because I followed the instructions for the Nginx configuration. So I did several things:
> 
>     * I made sure that the Nginx cache was disabled
> 
>     * I changed the history mode from HTML5 to Hash
> 
>     * The link to the resource is relative, for example `href="./resource.pdf"`

I had exactly the same issue yesterday, and sounds like have a similar setup, but I found the problem to be with [vite-plugin-pwa](https://github.com/vite-pwa/vite-plugin-pwa), if you use that, you need to make sure that the workbox config has `navigateFallback: undefined` option set

**Comment by GuibertLo** [comment]
> > I will leave here my solution to fix this problem if anyone has the same one. I tried a lot of different fixes, and I found one that worked. I noticed that the issue was coming from the history of Vue Router, which is odd because I followed the instructions for the Nginx configuration. So I did several things:
> > ```
> > * I made sure that the Nginx cache was disabled
> > 
> > * I changed the history mode from HTML5 to Hash
> > 
> > * The link to the resource is relative, for example `href="./resource.pdf"`
> > ```
> 
> I had exactly the same issue yesterday, and sounds like have a similar setup, but I found the problem to be with [vite-plugin-pwa](https://github.com/vite-pwa/vite-plugin-pwa), if you use that, you need to make sure that the workbox config has `navigateFallback: undefined` option set

You are a lifesaver, that was exactly it! I added this option in my config and now it works. Thank you sooo much :)
