### ISSUE TITLE
route.push called from an asyncComponent throws an "Uncaught (in promise) TypeError: oldVNode is undefined" error

### ISSUE THREAD

**Issue by psantos9** [vuejs/router#1675]
### Version
4.1.6

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-vwphx1?file=src/router.js)

### Steps to reproduce
Use case: generate a breadcrumb component using the meta field in RouteParams.
1. Open the stackblitz link: https://stackblitz.com/edit/vitejs-vite-vwphx1?file=src/router.js
2. Open the console in developer tools
3. Click twice on the "generated breadcrumb" component to navigate to the "third view". Observe the error thrown in the console ("Uncaught (in promise) TypeError: oldVNode is undefined").
4. Reload the stackblitz container (the app will start in the "third view"). Click on the generated breadcrumb component and observe the error thrown in the console ("Uncaught (in promise) TypeError: vnode.component is null"). The app will stop working.

### What is expected?
I can navigate between the different views by clicking on the generated breadcrumb component, and no errors are thrown.

### What is actually happening?
We are getting the following errors while navigating through the app:
"Uncaught (in promise) TypeError: oldVNode is undefined"
"Uncaught (in promise) TypeError: vnode.component is null"

---
I ran into this bug while developing a breadcrumb component that required to run async code after entering a certain route.

**Comment by posva** [comment]
You are resolving vnodes instead of a component. Notice the `() =>` in this version:

```ts
breadcrumbComponent: () => h(
          defineAsyncComponent({
            loader: async () => new Promise(
              resolve => setTimeout(() => resolve(
                () => h('div', {
                  class: 'bg-red-600 p-1 text-white rounded cursor-pointer',
                  onClick: () => router.push({ name: 'mainView' })
                }, 'Third View, click me to navigate to Main View')
              ), 2000)
            ),
            loadingComponent: h('div', { class: 'bg-gray-600 text-white p-1 animate-pulse rounded' }, 'Loading...')
          })
        )
      }
```

**Comment by psantos9** [comment]
Thank you Eduardo, your answer pointed me in the right way.
