### ISSUE TITLE
routerView + transition +keepAlive Page component switching exception

### ISSUE THREAD

**Issue by zguiyang** [vuejs/router#1679]
### Version
4.1.6

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-tpdwcn?file=src%2Fviews%2Fhome.vue&terminal=dev)

### Steps to reproduce
1. modify any content in the script tag of the home.vue component
2. Click on the about link in the page
3. the page component is not loaded properly

If you do not do the above operation, directly click the home and about links in the page to switch pages without any exception

### What is expected?
Page components load normally

### What is actually happening?
The page does not switch properly

---
After testing, I found that it is the problem of wrapping and animation of transition formation in layouts/BasicLayout.vue component, but I don't know the exact cause and how to solve it

**Comment by posva** [comment]
I cannot reproduce, changing any of the components before navigating doesn't yield any error. Note that vue router doesn't add anything to the HMR, everything is handled by Vue so it might be worth trying to boil this down to only Vue with the [SFC playground](https://sfc.vuejs.org/). It would also help to know if we would need to add anything to the router
