### ISSUE TITLE
getRoutes() no show passing props on the use of addRoute

### ISSUE THREAD

**Issue by Jiinn** [vuejs/router#1681]
Version
4.0.13

Reproduction link
[https://jsfiddle.net/wpvfk4d1/11/](https://jsfiddle.net/wpvfk4d1/11/)

Steps to reproduce
Define Vue Router and its routes, and addRoute with props.

What is expected?
$router.getRoutes() show props

What is actually happening?
$router.getRoutes() not show props

**Comment by posva** [comment]
You have a typo it's `component` without the final `s`:

```js
component: HomeView,
```

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by Jiinn** [comment]
I see, without s, i can get props.  

but the initial code has : 

router.addRoute("main", {
      path: route[i].path,
      name: route[i].name,
      props: route[i].props,
      component: tempComponent,
    });

For add in children to main. and in this case not get props.

**Comment by posva** [comment]
Did you search existing issues 👀 ? This seems like this one: https://github.com/vuejs/router/issues/600

**Comment by Jiinn** [comment]
i don't think, 

in my case, if i dont use componentS, i dont have render of my component. 
with componentS i have render, all work, but i dont have prop in getRoutes().

i dont have see documentation  for componentS, but i have compare my getRoutes, and i adapted because it existed in return of static child route.
