### ISSUE TITLE
useRoute() returns empty query on page reload

### ISSUE THREAD

**Issue by MRezaKarimi** [vuejs/router#1688]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/green-fog-c6mhr0?file=/src/App.vue)

### Steps to reproduce
1. Change page using provided buttons
2. Refresh the preview window

### What is expected?
When I refresh the window, page's initial value must be the same as the `page` query param in the URL.

### What is actually happening?
page's value is undefined because `route.query.page` is undefined.

**Comment by posva** [comment]
As noted in docs (and other issues), this is expected behavior as all navigations are async. See `router.isReady()` in docs.

**Comment by MRezaKarimi** [comment]
I solved the problem by reading initial query from `window.location.search` instead of `route.query`. However, I tried to use `await router.isReady()` before reading `route.query`, but it didn't work.

**Comment by abbasogaji** [comment]
this still doesnt work, adding await router.isReady() before reading route.query also doesnt work, and the documentation is not clear on what to do
