### ISSUE TITLE
Vue Router does not match some paths containing "." in last path.

### ISSUE THREAD

**Issue by YuheiFUJITA** [vuejs/router#1689]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/p/sandbox/brave-carlos-ld15hu)

### Steps to reproduce
1. Open the Vue.js project in your CodeSandbox browser.
2. Click on "users/user.id" to go to "https://xxxxxxxx.preview.csb.app/users/user.id". 
3. Confirm that the page is displayed. 
4. Reload the CodeSandbox browser.
5. Nothing show on the screen.

### What is expected?
Matches `/users/:id`.

### What is actually happening?
Nothing is displayed.

The browser's default 404 is displayed.

---
It does not reproduce when <router-link> is clicked. It is reproduced by reloading the browser or accessing the URL directly.

Below is a list of the results we have tried with the same source code.

- `/users/user-id` -> match `/users/:id`
- `/users/user_id` -> match `/users/:id`
- `/users/user.id` -> not match
- `/users/user..id` -> not match
- `/users/user.-id` -> not match
- `/users/user-id/foo` -> match `/users/:id/foo`
- `/users/user_id/foo` -> match `/users/:id/foo`
- `/users/user.id/foo` -> match`/users/:id/foo`
- `/users/user..id/foo` -> match `/users/:id/foo`
- `/users/user.-id/foo` -> match `/users/:id/foo`

**Comment by posva** [comment]
That's a codesandobox bug, it's not showing you the application as if it was trying to get a static file. The `.` [doesn't have any special meaning in vue router params](https://paths.esm.dev/?p=AAMsIPQgYAEL9lNgQAECUgPgDIFiDgCg&t=/hello.id#)
