### ISSUE TITLE
Document <router-link>

### ISSUE THREAD

**Issue by stefnotch** [vuejs/router#1702]
### Version
4.1.6

### Reproduction link
[router.vuejs.org](https://router.vuejs.org/introduction.html)

### Steps to reproduce
Version 3 of the Vue Router had a page dedicated to the <router-link> component and the slots API. It also included examples.
https://v3.router.vuejs.org/api/#router-link

### What is expected?
It would be lovely if a similar page existed for the current library.

### What is actually happening?
No such page exists.

---
It'd be lovely if the documentation were a bit more focused on the modern use-case where one uses it with Vite.

e.g.

- installation
- imports (ES Module imports)
- composition API example
- options API example
- ...
- "Template Navigation" page which is dedicated to the router-link component, notes that the slots API exists, and *maybe* recommends using programmatic navigation instead of the slots API. After all, the slots API for the Vue router doesn't seem to always be advantageous, and breaks the Vue Testing Utils' Router Link Stub https://test-utils.vuejs.org/api/#routerlinkstub

**Comment by posva** [comment]
There is already a few pages about router link. the search shows them. 
Other issues exist about adapting the getting started guide.
I if you have other proposals, I think the best is to directly work on a or proposal 🙂

**Comment by stefnotch** [comment]
The first result that the search shows is https://router.vuejs.org/guide/advanced/extending-router-link.html#extending-routerlink , which is not a very useful result, since it's an advanced topic.
The second result is https://router.vuejs.org/guide/#router-link , which doesn't include an example.

![image](https://user-images.githubusercontent.com/10220080/219481095-2b66941e-9b20-4ce9-94f0-69490a0e7016.png)
