### ISSUE TITLE
The Migration Guide's link to the v-slot API documentation is broken

### ISSUE THREAD

**Issue by nd9600** [vuejs/router#1711]
### Version
n/a

### Reproduction link
[vue-router docs](https://router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link)

### Steps to reproduce
1. Go to https://router.vuejs.org/guide/migration/index.html#removal-of-event-and-tag-props-in-router-link
2. Click "[v-slot API](https://router.vuejs.org/api/#router-link-s-v-slot)"
3. 3. See no documentation on the `v-slot` API

### What is expected?
You should be able to see the API docs explaining what the `v-slot` API is.

### What is actually happening?
The docs homepage is shown instead - the `#router-link-s-v-slot` anchor goes nowhere.

---
The [vue-router v3 docs](https://v3.router.vuejs.org/api/#v-slot-api-3-1-0) actually show what I expected to see.

I was able to find [this page](https://router.vuejs.org/guide/advanced/extending-router-link.html) that explained what the `v-slot` API was, but it's not linked to from the Migration Guide.

**Comment by posva** [comment]
The link should be indeed updated. Can you open a pull request to update the link?

**Comment by nd9600** [comment]
@posva thanks for replying so quickly.

I would've opened a PR, but I think it's a bigger job than just updating the link.

The `v-slot` API isn't mentioned anywhere in the API docs (`v-slot` does not appear on the page), and I don't know enough about it to know what to write; I would probably just end up copying the [v3 docs](https://v3.router.vuejs.org/api/#v-slot-api-3-1-0) - does it behave exactly the same in v4 as in v3?

The v4 docs seem quite different in general to v3, almost more like JSDoc converted to Markdown than documentation.
