### ISSUE TITLE
Hashtag in the bar

### ISSUE THREAD

**Issue by ByronSilvaOlvera** [vuejs/router#1714]
How did he remove vueroute 4 the Hashtag from the search bar. 
http://localhost:5173/#/.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
