### ISSUE TITLE
Popstate event not cleaned upon unmounting app

### ISSUE THREAD

**Issue by Neevalt** [vuejs/router#1720]
### Version
4.1.6

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-jypskg?file=src%2Fmain.js)

### Steps to reproduce
1) In the reproduction link, click on "open in new tab" in the top bar (only works for chromium based for me)
This is needed because the embedded demo is inside an iframe which breaks what follows

2) open console

3) type `getEventListeners(window)`, notice absence of `popstate` events

4) press `mount` button

5) type `getEventListeners(window)`, notice 1 `poptstate` event

6) press `unmount` button

7) type `getEventListeners(window)`, notice 2 `popstate` events

You can repeat 4-7 as much as you want.

### What is expected?
The `popstate` event is cleared when app is unmounted

### What is actually happening?
`popstate` event are never unregistered

---
Hello ! 

First of all, thank you for your work on this amazing library !

 I am aware that we can "fix" the infinite push of popstate event by having the router initialized only once. However, there is still a dangling `popstate` event that will remain even in this case. Moreover, in our architecture, we create the router through a function which gets called everytime the app needs to be mounted. So we can't necessary rely on this solution. Nevertheless, I would argue that having dangling events can add unecessary noise, and it actually is creating an issue on our side with a micro-frontend architecture and several routers managing their own `popstate` events. 

We noticed that the `unmount` function does not call the `history`'s `destroy` function.

Would doing so break any behaviour that needs to be kept ?

If so, would it be possible to alter the API to provide an option like `router.destoryOnAppUnmounted` or so boolean to trigger this destroy ? If you uncomment line 37 in the reproduction link, you can see that it fixes the issue.

Thank you in advance,
cheers

**Comment by posva** [comment]
The history instance is passed to the router, not managed by it so it makes sense to manually destroy it when the app is unmounted. Destroying it would indeed break anybody reusing the history instance and it’s there on purpose for flexibility.
Adding a line of api to replace another line of code is definitely something I would avoid 🙂

**Comment by Neevalt** [comment]
Hey,
Thank you for your quick answer ! 😄 

Out of curiosity, what would be a use case of reusing the history after the app has been unmounted ?
And in such cases, what would be the goal of keeping the `popstate` event alive while the app is unmounted ?

About the API thing, I understand your point, but it's not necessary one line of code. If i simplify a bit our code, we have something like this : 
```
// router.js
export const routerFactory = (base) =>
  createRouter({
    history: createWebHistory(base),
    routes: routes,
  });
```
In order to destroy manually, it'd mean doing something like so : 
```
// router.js
export let history = undefined;

export const routerFactory = (base) =>
  if (!history) {
    history = createWebHistory(base);
  }

  createRouter({
    history: createWebHistory(base),
    routes: routes,
  });
```
and then
```
// index.js
import { history } from `router.js`;
...
app.use(router);
const appUnmount = app.unmount;
app.unmount = () => {
  history.destroy();
  appUnmount();
}
```

or 
```
// App.vue (root element)
<script setup>
import { history } from 'router.js';
...
onUnmounted(() => {
  history.destroy();
});
```

I find these two solutions to be somewhat verbose compared to 
```
// router.js
export const routerFactory = (base) =>
  createRouter({
    destroyHistoryOnUnmount: true,
    history: createWebHistory(base),
    routes: routes,
});
```

Wdyt ?

**Comment by posva** [comment]
I wasn’t sure if this was a bug so I checked but the history still registers one even listener and remove any router listener.
You should be able to reuse the history instance across multiple router instances

Destroying the history must indeed be done manually and I don’t think it’s a good idea to add one very specific Boolean option to the router to destroy the history

**Comment by Neevalt** [comment]
If anyone stumbles accross this post, this is what we went with, as it looked the less invasive in our code : 
```js
export const routerFactory = (base) => {
  const history = createWebHistory(base);
  const router = createRouter({
    history: history,
    routes: routes,
  });

  const installRouter = router.install.bind(router);
  router.install = (app) => {
    installRouter(app);

    const unmountApp = app.unmount;
    app.unmount = function () {
      history.destroy();
      unmountApp();
    };
  }

  return router;
}
```
