### ISSUE TITLE
Incompatible TS type for $route.query

### ISSUE THREAD

**Issue by lanten** [vuejs/router#1722]
### Version
4.1.6

### Reproduction link
[github.com](https://github.com/vuejs/router/blob/main/packages/router/src/query.ts#L29-L32)

### Steps to reproduce
install the vue-router@4.1.6, and use it.

```vue
<van-empty :description="$route.query.message"></van-empty>
```

The description field requires `string` type, and then:

```
Type 'LocationQueryValue | LocationQueryValue[]' is not assignable to type 'string | undefined'.
   Type 'null' is not assignable to type 'string | undefined'. ts(2322)
```

https://github.com/vuejs/router/blob/ec0d69537964b9cecb3f33901f0240245c6cb6c9/packages/router/src/query.ts#L29-L32

If I replace `declare type LocationQuery` here with `declare interface LocationQuery`, I can extend LocationQuery by `declare module 'vue-router'` .

in `vue-router.d.ts` :
```
export declare interface LocationQuery extends Record<string, LocationQueryValue | LocationQueryValue[]>{
    
}
```

in my code :

```ts
declare module 'vue-router' {
  interface LocationQuery {
    message: string
  }
}
```

That way everything is fine.

so, why use `declare type`?

### What is expected?
type correct

### What is actually happening?
type error

---
BTW, why `useRoute` cannot pass generic type to define the properties of `query` and `meta`

**Comment by posva** [comment]
null is a possible value for a query value so this is expected
