### ISSUE TITLE
Leading slash always added to relative 'base' when constructing router links

### ISSUE THREAD

**Issue by mrichar1** [vuejs/router#1725]
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/empty-bush-336hvz)

### Steps to reproduce
Inspect the HTML for the router links (i.e `Home` and `About`) and notice they are both absolute (`/./` and `/./about`)

### What is expected?
The relative value of base should be used as-is without a leading slash being affixed.

### What is actually happening?
A leading slash is being affixed. 

The issue seems to be that the code tries to re-add a slash that may have been removed previously - however it does not take account of the slash never having been present:

https://github.com/vuejs/router/blob/376edd32c39af004ee3689f569f0da65418c9577/packages/router/src/history/common.ts#L174

---
I discovered this bug when trying to use `./` for `base` with Vite as described here: https://vitejs.dev/config/shared-options.html#base

**Comment by posva** [comment]
That's indeed not a valid base. Just use `/` or nothing at all. [More in docs](https://router.vuejs.org/api/interfaces/RouterHistory.html#Properties-base)
