### ISSUE TITLE
Details in API docs generation

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/router#1743]
### Reproduction

Run the docs:api script

### Steps to reproduce the bug

1. `pnpm run docs:api` and `pnpm run docs` in `packages/docs` folder
2. see `api/index.md` and `http://localhost:5173/api/`

`### START\_LOCATION %{#Variables-START\_LOCATION}%` should be `### START\_LOCATION %{#Variables-START_LOCATION}%`:
![image](https://user-images.githubusercontent.com/206848/225493640-ace13b88-77f2-4fee-a154-fe7200f59932.png)

<code>\`ComputedRef\`<\`string\`\></code> is better to be <code>\`ComputedRef<string\>\`</code>:
![image](https://user-images.githubusercontent.com/206848/225493694-30c687d8-345a-4746-a14e-451c2749dbaa.png)

### Additional information

I found it during the Chinese translation #1743. I guess that's about something inside the typedoc. Just take note here in advance. Thanks.

**Comment by posva** [comment]
The generation of the custom hash in titles is in a custom script, so it should be easy to fix

`Type<T>` is generated by the tool and personally I prefer that style so I don't think we will change that
