### ISSUE TITLE
Links in the Documentation do not work in Mozilla Firefox

### ISSUE THREAD

**Issue by XamzatJR** [vuejs/router#1757]
### Reproduction

.

### Steps to reproduce the bug

Click on "Get started" button in home page.

### Expected behavior

Redirect to the [Installation](https://router.vuejs.org/installation.html) section

### Actual behavior

It stays on the same page.

### Everything works fine in Chrome

**Get this error** 
![изображение](https://user-images.githubusercontent.com/67521340/228082419-1fb1038e-2286-4836-8855-150e66883508.png)

**userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0"**

**Comment by lorand-horvath** [comment]
This has been fixed, see https://github.com/znckco/thesemetrics/issues/10#issuecomment-1498686986

**Comment by BANOnotIT** [comment]
@posva I do not use Avast and it still breaks.

![image](https://github.com/vuejs/router/assets/11363215/6178ceeb-6081-4e7b-9a7a-7ca20884a151)

**Comment by lorand-horvath** [comment]
@BANOnotIT It may be caused by another antivirus. Which one do you use? I've just rechecked and VirusTotal doesn't flag it anymore https://www.virustotal.com/gui/url/8110f0a1c991a53e5bee13d804f2bcf972d7da2f6b0fc9fd44160d8b912d1480

**Comment by BANOnotIT** [comment]
@lorand-horvath I use none

**Comment by BANOnotIT** [comment]
Turns out it is connected to adblocking extension.

https://github.com/AdguardTeam/AdguardFilters/issues/155459

**Comment by zqianem** [comment]
Ran into this today and got around it by disabling Firefox's Enhanced Tracking Protection (the shield icon in the left part of address bar). I sent a report upstream (via [these instructions](https://support.mozilla.org/en-US/kb/report-breakage-due-blocking)) and would encourage others to do the same 👍.
