### ISSUE TITLE
Properties such as this.$route.query are marked in IDEA as Weak Warning

### ISSUE THREAD

**Issue by NXY666** [vuejs/router#1762]
### Reproduction

https://codesandbox.io/s/cpoisd

### Steps to reproduce the bug

Call this.$route.query, this.$route.params in any of these places.

### Expected behavior

Identified normally and with code complements.

### Actual behavior

It is marked as "Weak Warning: Unresolved variable", this.$route and this.$router will not have any code completion options.
![image](https://user-images.githubusercontent.com/62371554/228829855-57d18d88-7679-4763-be83-8b715e003c7b.png)

### Additional information

I think it may be a documentation issue.

**Comment by posva** [comment]
The `$route` type is intentionally loose to allow any access. That's likely why your IDE is pointing out a warning (instead of an error). If you want typed routes check https://github.com/posva/unplugin-vue-router

**Comment by NXY666** [comment]
> The `$route` type is intentionally loose to allow any access. That's likely why your IDE is pointing out a warning (instead of an error). If you want typed routes check https://github.com/posva/unplugin-vue-router

![image](https://user-images.githubusercontent.com/62371554/229457813-4635814b-5571-4bd0-90de-5780116d3661.png)

Before that, this was a trinomial operator, but when I removed it, IDEA recognized it properly. I don't know if this has side effects, but at least it makes it less annoying.
