### ISSUE TITLE
 I found that Vue Router push encodes query twice

### ISSUE THREAD

**Issue by flynn-eye** [vuejs/router#1766]
### Reproduction

https://codesandbox.io/s/frosty-paper-c9ns3i?file=/src/router.js:301-307

### Steps to reproduce the bug

this demo will jump to the target page after mounted

encodeURI("你好") value  is ` '%E4%BD%A0%E5%A5%BD'`
encodeURI(encodeURI("你好") ) value is  ` '%25E4%25BD%25A0%25E5%25A5%25BD'`

after demo push to the new page ,this query value is  `'%25E4%25BD%25A0%25E5%25A5%25BD'`

### Expected behavior

i hope value is  `'%E4%BD%A0%E5%A5%BD'`
it only encodes once

### Actual behavior

it encodes twice

**Comment by flynn-eye** [comment]
when i pass '你好' to query, it doesn't encode, if i pass encode('你好'), it will encode twice

**Comment by sfwxp945** [comment]
你直接这样不行吗？
`setTimeout(() => {
      r.push({
        name: "about",
        query: {
          name: "你好",
        },
      });
    }, 4000);`

**Comment by flynn-eye** [comment]
这样不行哦，那query就没有encode。
this way doesn't work， query will not be encoded

**Comment by flynn-eye** [comment]
> 实际上就是因为会自动cencode所以才会来两次啊.你直接写中文,它就帮你encode 直接在你代码片段改成"你好"是可以直接跳转的,没问题

不知道为啥codesandbox上没复现， 我用vue cli 创建的项目复现了我说的问题
``` 
// app.vue
import { RouterLink, RouterView, useRouter } from 'vue-router'
import { onMounted } from 'vue'
import HelloWorld from '@/components/HelloWorld.vue'

const r = useRouter();

onMounted(() => {
      setTimeout(() => {
      r.push({
        name: "about",
        query: {
          name: "你好",
        },
      });
    }, 4000);
})

```

**Comment by sfwxp945** [comment]
事实上，这样并没有什么问题啊。我这使用跟你一样的参数，也可以正常在页面获取并输出。

**Comment by flynn-eye** [comment]
目前看起来不影响使用，只是好奇为啥会这样，我再研究研究
