### ISSUE TITLE
Allow comments inside ViewRouter without breaking rendering

### ISSUE THREAD

**Issue by RichardJECooke** [vuejs/router#1771]
### Reproduction

no

### Steps to reproduce the bug

1. Initialise the demo Vue project with VueRouter
2. In app.vue `<template>` this code won't render any routes:

```html
<RouterView>
    <!-- <RouterLink to="/hi">Go to Hi page</RouterLink> -->
</RouterView>
```

but this code works fine:

```html
<RouterView>
</RouterView>
```

### Expected behavior

Commented out html should have no effect on rendering.

### Actual behavior

Commented out html causes no rendering of routes to occur

**Comment by posva** [comment]
This is inherent to HTML and `v-slot`, `<RouterView>` allows passing slot content to override the way it renders. After all, comments are also HTML nodes. Usually you use `<RouterView>` in one of the two following ways:

```vue
<RouterView /> // no content
<RouterView v-slot="{ Component }">
  <Component :is="Component" /> // to wrap with KeepAlive or Transition
</RouterView>
```

If you pass content to a slot, it becomes:

```vue
<RouterView v-slot="{ Component }">
  <Component :is="Component">
</RouterView>
