### ISSUE TITLE
用正则匹配路由没有达到官网说的效果，使用的还是官网提供的例子

### ISSUE THREAD

**Issue by yyj961010** [vuejs/router#1779]
### Reproduction

https://paths.esm.dev/?p=AAMsIPQgwAUClgpg6wAGPiWgoAAAIwQ4PeACvAy4C2BygBgCYAu2KQBA&t=/25

### Steps to reproduce the bug

按官网的例子，输入/123 应该匹配到id=123，而现在确匹配到/:productName这个路由了
![image](https://user-images.githubusercontent.com/42398073/230294313-1766fada-9bbb-4198-9318-b1162e788fd1.png)

### Expected behavior

输入/123 应该匹配到id=123

### Actual behavior

现在确匹配到/:productName这个路由

### Additional information

使用的是官网的例子

![image](https://user-images.githubusercontent.com/42398073/230294591-e11f5104-4538-4938-abe9-601006434d05.png)

**Comment by posva** [comment]
In the paths explorer you shouldn't escape the `\`: https://paths.esm.dev/?p=AAMsIPQgwAUClgpg6wDUwKAEBBQHYJwAtwdXgIwBcAFADgFDBWzIMgAA&t=/25#

**Comment by yyj961010** [comment]
建议文档示例代码改下，文档上是`\\d`
多谢了
