### ISSUE TITLE
Allow named routers with the same path: name-first route matching for navigation through history

### ISSUE THREAD

**Issue by mahnunchik** [vuejs/router#1781]
### What problem is this solving

I'm working on an application which has multiple stages/steps to complete an action. According to the application logic, it makes no sense to make separate paths for additional steps, because reloading the page should lead to the first step.

For example login action:

```js
import { createRouter, createWebHistory } from 'vue-router';
import HomeView from '../views/HomeView.vue';
import LoginFirstView from '../views/LoginFirstView.vue';
import LoginSecondStep from '../views/LoginSecondStep.vue';

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: HomeView
    },
    {
      path: '/login',
      name: 'loginFirstStep',
      component: LoginFirstView,
    },
    {
      path: '/login',
      name: 'loginSecondStep',
      component: LoginSecondStep,
    },
  ],
});

export default router;
```

`$router.push({ name: 'loginSecondStep' })` works as expected, second step loaded after navigation by route name. 

But back and forward navigation doesn't work because path-only matching is used.

### Proposed solution

Feature request: name-first route matching for navigation through history. It should be possible by saving `name` of route in state object.

### Describe alternatives you've considered

The task can be solved by creating a view containing steps and a switch, but it breaks the router navigation logic.

**Comment by posva** [comment]
This is an intentional design on front end routing, it makes things predictable.

You should differentiate the route somehow with a query param or a different path. If you still want to use the same path, you can push custom state to the history entry. You can check the modal e2e test in this repository for a full example
