### ISSUE TITLE
Doc site https://router.vuejs.org/ internal links broken in Firefox

### ISSUE THREAD

**Issue by steadygaze** [vuejs/router#1784]
### Reproduction

N/A

### Steps to reproduce the bug

1. Navigate to https://router.vuejs.org/ in Firefox.
2. Try to click on any internal link (staying on https://router.vuejs.org/). For example, the "Get Started" button, or search something and try to click on an entry.

### Expected behavior

The browser navigates to the given link.

### Actual behavior

On the page, nothing happens. In the dev console, a `TypeError` appears:

![Screenshot of TypeError stack trace (see below)](https://user-images.githubusercontent.com/119086591/230543851-ad0ef9f2-ad87-41af-b87a-e6f01d103015.png)

```
Uncaught (in promise) TypeError: e is null
    t https://unpkg.com/thesemetrics@latest:1
    i https://unpkg.com/thesemetrics@latest:1
    j https://unpkg.com/thesemetrics@latest:1
    pageread https://unpkg.com/thesemetrics@latest:1
    _ https://unpkg.com/thesemetrics@latest:1
    r https://unpkg.com/thesemetrics@latest:1
    i https://unpkg.com/thesemetrics@latest:1
    o https://router.vuejs.org/assets/app.dc320762.js:1
    Sc https://router.vuejs.org/assets/app.dc320762.js:1
    Sc https://router.vuejs.org/assets/app.dc320762.js:1
    E1 https://router.vuejs.org/assets/app.dc320762.js:8
    L1 https://router.vuejs.org/assets/app.dc320762.js:8
    <anonymous> https://router.vuejs.org/assets/app.dc320762.js:8
[thesemetrics@latest:1:665](https://unpkg.com/thesemetrics@latest)
Source map error: Error: request failed with status 404
Resource URL: https://unpkg.com/thesemetrics@latest
Source Map URL: browser.min.js.map
```

### Additional information

- Sometimes the error appears on page load. When I was refreshing the page to test this, it actually worked once, but then went back to failing.
- Sometimes the stack trace appears twice on page load without having to do anything.
- Tried in Chromium and it works fine.

**Comment by posva** [comment]
This is an avast issue and should be fixed soon. It has been reported before.
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
