### ISSUE TITLE
Same stack nesting when using router.replace method

### ISSUE THREAD

**Issue by parkjunghwan-reco** [vuejs/router#1795]
### Reproduction

https://jsfiddle.net/parkjunghwan/g2L9mxke/66/

### Steps to reproduce the bug

When using router.replace or router.push({...replace:true}), I want to ignore the stack if it is the same route.

Below is an example.
1. Click a row in the user list screen.
2. The user details screen is displayed. Click the "Edit" button.
3. The user editing screen is displayed. After editing, click "Save". At this time, call replace to ignore the "modified screen" stack and move to the detailed screen.
4. I want to move to the user list screen when I perform "Back" on the detail screen.

### Expected behavior

When using replace, if the path? is the same, is it possible to maintain only one detail screen stack?

### Actual behavior

If you press "Back" in number 4, the "Details" stack becomes two, and the back screen appears once more, and you have to press "Back" again to move to the list screen.

**Comment by posva** [comment]
This is totally correct from the history api perspective so it's something you have to implement in userland. Note you could simply push instead of replace and the history entries would make more sense that way.
