### ISSUE TITLE
router.resolve parseURL error

### ISSUE THREAD

**Issue by canGeEr** [vuejs/router#1799]
### Reproduction

https://codesandbox.io/s/blissful-cherry-o3ri9o?file=/src/views/About.vue

### Steps to reproduce the bug

1. choose pages/About.vue
2. watch browser
3. click About link to /about
4. click a link

### Expected behavior

jump to /about/a

### Actual behavior

jump to /a

### Additional information

After view the sorce file，in **resolveRelativePath** method，should change
```ts
position = fromSegments.length - 1
```
to 
```ts
position = fromSegments.length
```
otherwise, that behavior will lose the last element of fromSegments.

**Comment by posva** [comment]
This is actually how a relative URL works

**Comment by canGeEr** [comment]
> This is actually how a relative URL works

i am sorry, although it doesn't quite ring common sense to me, but you are right
