### ISSUE TITLE
vue-router 3 with Vue 2.7 throwing "missing param for named route..." when empty string

### ISSUE THREAD

**Issue by VividLemon** [vuejs/router#1801]
### Reproduction

https://codesandbox.io/s/laughing-fermat-tgi9xi

### Steps to reproduce the bug

Note, the reproduction uses Vue-router @4, but the issue is on @3!

So, the code from that, just use @3 & vue 2.7

1. Create an optional route param
2. Try to navigate to route using `{name: 'About', params: { id: undefined } }` -- will work, but will through TS error.
3. Ok, so try `{name: 'About', params: {id: undefined ?? '' } }` -- Okay, no TS error, but throws 
`[vue-router] missing param for named route "About" Expected "id" to match "[^\/]+?", but received ""`
In addition to this, the URL will not be /About , it will send to / , but with the correct component.

### Expected behavior

Empty string is valid, no error, sends to correct route, URL changes to be correct place

### Actual behavior

Console warning, sends to root, URL is not correct

### Additional information

App is using vue-router@3.6.5

![image](https://user-images.githubusercontent.com/31498096/232552546-f4d64b1a-57d5-485a-9b55-1ef4410484a0.png)
![image](https://user-images.githubusercontent.com/31498096/232552494-2defc289-923c-4d0e-99f1-6a3ba1c7f4bf.png)
 
-- TS error, but works correctly
![image](https://user-images.githubusercontent.com/31498096/232552867-d80007f4-452f-4a76-b5ae-a3b4e524af49.png)
-- No TS error, but throws runtime issue
![image](https://user-images.githubusercontent.com/31498096/232553020-0698f8b9-b144-4470-8ba9-f320aef90dc5.png)
(`?? undefined` is redundant ik)

**Comment by posva** [comment]
This looks like a type error. Could you open an issue on the vuejs/vue-router repo **with a correct reproduction using vue router 3 and vue 2**?

**Comment by VividLemon** [comment]
Its not necessarily a type error, as the params type is correctly string[]... Its just how it handles empty strings when using optional dynamic parameters. 

I was planning on making a better repo, just haven't gotten around to it. Do you happen to have a blank codesandbox template that has @3 ? @posva

**Comment by VividLemon** [comment]
Oh I see, this @3 is a different repo.
