### ISSUE TITLE
router.resolve not resolving routes for unnamed routes coming from route.matched

### ISSUE THREAD

**Issue by kleinfreund** [vuejs/router#1829]
### Reproduction

https://codesandbox.io/s/wizardly-shtern-grqoyp

### Steps to reproduce the bug

Open the reproduction and look at the `routes` array rendered on screen.

In general (this is also done in the reproduction):

1. Create an _unnamed_ route definition with a dynamic path segment.
2. In a component that is rendered using this dynamic path segment, access the current route’s matched routes and resolve them (i.e. `route.matched.map((matchedRoute) => router.resolve(matchedRoute))`).

### Expected behavior

In the reproduction: The second entry is `"/test-path/test-segment"`.

Generally: Routes are always resolved regardless of whether they’re named or not.

### Actual behavior

In the reproduction: The second entry is `"/test-path/:dynamicSegment"`.

Generally: Routes are only resolved if they’re named.

### Additional information

* **Workaround**: Naming the route definition (see comment in src/router.js in reproduction) will cause the route to be resolved correctly.
* This isn’t directly related to the particular objects coming from `route.matched` but rather route objects in general that are unnamed and unresolved.
* Looking at the source code, there seems to be an assumption that unnamed routes with a path are already resolved:

https://github.com/vuejs/router/blob/c49541a0df99da45c129a12868419f5a5d3cddda/packages/router/src/matcher/index.ts#LL294C7-L294C73

Related issues:

* https://github.com/vuejs/vue-router/issues/3573

**Comment by posva** [comment]
The matched array contains route records so they cannot be resolved. You are seeing it work in some scenarios but it's because `router.resolve()`, by default, uses the current location (as second argument), which contains the param `test-segment`, which is applied when doing `router.resolve({ name: 'test-route' })`, which would include the cases of unnamed routes you are describing.

Passing the second argument will opt out from relative locations and give out an error:

```vue
<template>
  <pre>{{ JSON.stringify(routes, null, 2) }}</pre>

  <router-view></router-view>

  <pre>{{ $route.matched }}</pre>
</template>

<script>
import { START_LOCATION} from 'vue-router'
export default {
  name: "App",

  computed: {
    routes() {
      return this.$route.matched.map((matchedRoute) => {
        try {
          const resolvedRoute = this.$router.resolve(matchedRoute, START_LOCATION);

          return resolvedRoute.path;
        } catch (err) {
          console.error(err)
          return null;
        }
      });
    },
  },
};
</script>
```

**Comment by kleinfreund** [comment]
If I understand correctly (ignoring that as things stand `router.resolve` is not meant to handle records), it should be possible to always resolves records from `route.matched` provided they have a `name` because `route` will have its `path` and `params` resolved and all entries in `route.matched` are either `route` itself or an ancestor and so shouldn't be able to contain unknown `path`s or `params`.

Getting resolved routes from `route.matched` is quite handy in my opinion. It could be the backbone of a breadcrumbs navigation or help in determining active items in more complex navigation structures.

---

For posterity, I wanted to document the workaround I mentioned initially. It will allow `route.matched.map((record) => router.resolve(record))` to produce a list of correctly resolved route locations.

Do note that doing this affects how calls to `router.resolve` behave so if you already use this in your application, pay attention to those uses.

```js
const router = createRouter({
	history: createWebHistory(),
	routes: nameRecords(routes),
	     // ^ Makes sure all routes have a named.
})
app.use(router)

/**
 * Adds a `name` to all `records` that don't have one. This function mutates `records`.
 *
 * Keep in mind that routes added later (e.g. via `router.addRoute`) might need to be processed in the same manner (e.g. `router.addRoute(nameRoute(record))`).
 *
 * @param {RouteRecordRaw[]} records
 * @param {string} [prefix]
 * @returns {RouteRecordRaw[]}
 */
function nameRecords(records, prefix = 'route') {
	for (const [index, record] of Object.entries(records)) {
		nameRecord(record, `${prefix}-${index}`)

		if (Array.isArray(record.children)) {
			nameRecords(record.children, `${prefix}-${index}`)
		}
	}

	return records
}

/**
 * This function mutates `record`.
 *
 * @param {RouteRecordRaw} record
 * @param {string} name
 * @returns {RouteRecordRaw}
 */
function nameRecord(record, name) {
	if (!('name' in record)) {
		record.name = name
	}

	return record
}
```
