### ISSUE TITLE
onBeforeRouteLeave not being called on route that uses same component

### ISSUE THREAD

**Issue by gits-gretchelin** [vuejs/router#1831]
### Reproduction

https://codesandbox.io/s/objective-ptolemy-rlbsjj?file=/src/router.js

### Steps to reproduce the bug

Using the repro linked:

1. Click the link "Lorem Posts" 
2. Click the link "Ipsum Posts".
3. Click the link "Home" or "About". You will see there's an alert "I'm called" popping out.
4. Repeat step 1 and step 2. You will see no alert popping out.

### Expected behavior

When moving from either "Lorem Posts" or "Ipsum Posts" to any other links, the "I'm called" alert should appear.

### Actual behavior

No alert appearing when moving between "Lorem Posts" and "Ipsum Posts".

### Additional information

I'm trying to show confirmation popup when leaving route with form. However, I share the same component (let's say `FormPage`) across different route, such as `/posts/create`, `/posts/edit/:id` and `/posts/view/:id`. Edit page can be accessed from view page, and there is a custom back button in all these page that if clicked, should redirect user to previous page. 

I'm using `onBeforeRouteLeave` hook, to achieve this ,on `FormPage` component, but noticed that while moving to a whole other page trigger this hook just fine, moving from the edit to view page, which both uses `FormPage`, such as from the back button action, does not trigger the hook.

**Comment by posva** [comment]
This is expected because the route doesn't change, only the path. You need to use `onBeforeRouteUpdate()` for that.
