### ISSUE TITLE
RouterView component doesn't provide routeLocationKey

### ISSUE THREAD

**Issue by MichealPearce** [vuejs/router#1838]
### Reproduction

https://github.com/MichealPearce/vue-router-issue-123131

### Steps to reproduce the bug

Was working on a tab system with vue router. Where each tab is a different `RouterView` with a different url. In my example, I have [an array of strings](https://github.com/MichealPearce/vue-router-issue-123131/blob/main/src/components/TabView.vue#L16) which are urls [I pass to `router.resolve`](https://github.com/MichealPearce/vue-router-issue-123131/blob/main/src/components/TabView.vue#L23) which is then [passed to the `RouterView` component](https://github.com/MichealPearce/vue-router-issue-123131/blob/main/src/components/TabView.vue#LL65C4-L67C25) as a prop.

I found that the `RouterView` component does not provide the `routeLocationKey` which is what `useRoute` injects. Because of this, the result of `useRoute` is different than what the `RouterView` component is displaying and this causes issues. In my example, I have a [page that is watching the `route` object](https://github.com/MichealPearce/vue-router-issue-123131/blob/main/src/pages/about.vue#LL14C1-L16C3) and logs when it updates. 

1. open app and add three tabs.
2. navigate to one of the different pages with one of the tabs being the "about" page.
3. select a tab that isn't the "about" page tab.
4. Navigate between the "home" page and the "contact" page.
5. See that the "about" page logs that the `route` has been changed when that tab hasn't been changed.

### Expected behavior

The `route` provided as a prop to `RouterView` to be provided and used for `useRoute`

### Actual behavior

`RouterView` component does not provide `routeLocationKey` so `useRoute` is not effected by it.

### Additional information

This could be intentional but it seems like having `useRoute` return something that could be different from the route that the `RouterView` component is displaying could be an issue. At-least it was for my use case in building tabs like this.

This can also be worked around by creating a component that provides `routeLocationKey` yourself and wrapping it around the component [like so](https://github.com/MichealPearce/vue-router-issue-123131/blob/main/src/components/RouteProvider.vue).

**Comment by posva** [comment]
This behavior is indeed expected. The inner behavior of RouterView is a bit more complex than just the route so there are other implications to changing this behavior.

Note you can always provide a custom route version for a custom tab system to work but this is outside of vue-router's scope. You could technically even override vue-router useRoute()
