### ISSUE TITLE
Route name and Component name

### ISSUE THREAD

**Issue by TebyakinAlexey** [vuejs/router#1839]
### Reproduction

routing stops working if route name matches component name

### Steps to reproduce the bug

Run application.
Routing stops working if route name matches component name.

### Expected behavior

routing should work

### Actual behavior

routing not working

### Additional information

example routing config:

import Login from '.../Login.vue'
export const routes = [
  {
    name: 'Login',
    path: '/login',
    component: Login

**Comment by posva** [comment]
We can't do anything with this kind of information. We need a valid repro as specified in the new issue form. Please read it carefully and follow the instructions.
