### ISSUE TITLE
Root view contains multiple elements

### ISSUE THREAD

**Issue by TebyakinAlexey** [vuejs/router#1840]
### Reproduction

run application

### Steps to reproduce the bug

if root view contain multiple elements than router crashes

### Expected behavior

router must work

### Actual behavior

router does not work

### Additional information

example:

SomeView.vue:
<template>
  <div/> 
  <div/> 
</template>

router crash

**Comment by posva** [comment]
We can't do anything with this kind of information. We need a valid repro as specified in the new issue form. Please read it carefully and follow the instructions.
