### ISSUE TITLE
4.2.0 vue-router.d.ts BUG: $route does not exist

### ISSUE THREAD

**Issue by cturconde** [vuejs/router#1844]
### Reproduction

Property '$route' does not exist on type 'CreateComponentPublicInstance

### Steps to reproduce the bug

When compile, run or build the error appears: Property '$route' does not exist on type 'CreateComponentPublicInstance

Just on version 4.2.0 due to -> _declare module 'vue'_ on vue-router.d.ts file in node_modules/vue-router/dist/

Fix this this version with ---> **declare module '@vue/runtime-core'** 

Until that, just version 4.1.6 is usable.

### Expected behavior

Find variable $router

### Actual behavior

Can not finde variable $router

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
