### ISSUE TITLE
beforeEach guard not changing URL after user uses back button

### ISSUE THREAD

**Issue by dserranog1** [vuejs/router#1850]
### Reproduction

https://codesandbox.io/s/epic-dew-cgwffy

### Steps to reproduce the bug

1. Click on login
2. Click on logout
3. Click on the browser back button

### Expected behavior

After the router intercepts the route, the new URL should be the one I am returning on the `beforEach` callback.

### Actual behavior

The URL is staying as the one it was redirected from.

### Additional information

In my actual app, no matter how many times I hit the back button, the URL stays on the route that the router redirected from i.e. the `from.fullPath` from the `beforeEach` guard.

I am using version 4.2.1 on my app.
It seems it's the same as #916, and the [temporal fix](https://github.com/vuejs/router/issues/916#issuecomment-834189652) also works in this case. The implemented fix (#921) however, doesn't to solve my situation.

**Comment by posva** [comment]
You are being redirected to the Home page because that’s what you return in the navigation guard

**Comment by dserranog1** [comment]
> You are being redirected to the Home page because that’s what you return in the navigation guard

The component being rendered is `Home`, but the route is `/about` @posva

![Selection_082](https://github.com/vuejs/router/assets/88839679/b444b98c-65af-4c04-a7d1-881d0b9a458f)

**Comment by codePassion-dot** [comment]
I'm having the exact same problem described in this issue. I don't understand why it was closed so soon

**Comment by posva** [comment]
I opened https://github.com/vuejs/router/pull/2133 with a workaround.
