### ISSUE TITLE
Cant debug with vue/core

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/router#1856]
### Reproduction

https://github.com/hezhongfeng/core/tree/report-branch

### Steps to reproduce the bug

1. install and build vue/core
2. cd packages/vite and install
3. pnpm dev

### Expected behavior

can use vue-router to display signal page view

### Actual behavior

Noting show on #app

### Additional information

I wanted to debug the code in core while using vue-router.

**Comment by posva** [comment]
As I said in the other issue, provide a boiled down repro not a whole mono repo base on Vue core.
You can use a local build of a package with other tools like yalc
Closing as this is a question
