### ISSUE TITLE
'Dynamic Routing : Adding nested routes' not working when page is refreshed OR URL typed on address bar

### ISSUE THREAD

**Issue by renartius** [vuejs/router#1859]
### Reproduction

Is the same as https://github.com/vuejs/router/issues/1777 but with new information (page refresh)

### Steps to reproduce the bug

If the page added by addRoutes is refreshed, the page does not appear.
It only works with programmatic navigation (push)

I believe that if I can load the main component (APP) after adding the routes (which I obtained through an API request), it will work

### Expected behavior

Page loads 

### Actual behavior

page not load

### Additional information

As commented, it was reported previously, but no solution was provided

**Comment by posva** [comment]
The reason is on the other issue…
