### ISSUE TITLE
Localization in route paths

### ISSUE THREAD

**Issue by yooouuri** [vuejs/router#1861]
### What problem is this solving

We're creating a multilang website, so we have two routes, pointing to the exact same component but the path is localized:

* /klantenservice
* /customer-service

So I would define it as (auto generated from some function)

```
const routes  = [
  {
    path: '/klantenservice',
    component: CustomerService,
    name: 'customer-service__nl',
  },
  {
    path: '/customer-service',
    component: CustomerService,
    name: 'customer-service__en',
  },
]
```

Of course I can create some "helper" function to automatically add the `__en` depending on the current language.

But if you are able to overwrite the `router.push()` function or change the internal route handling, that would be great in this case.

### Proposed solution

An API to overwrite the `router.push()` functionality or route handling or something like that.

### Describe alternatives you've considered

Using a "helper" function to act as a router push, but it feels kinda off.

**Comment by posva** [comment]
AFAIK the router already has the APIs for this:

- https://vue-i18n.intlify.dev/
- https://github.com/intlify/routing
- https://github.com/nuxt-modules/i18n

BTW you can already overwrite `router.push = function customPush(...) {}`

**Comment by JsonKody** [comment]
I've used vue-i18n and for newer project I've made my own solution that is light and simpler to use.
I need to know how to implement the lang prefix in vue router as it is, not to use vue-i18n library :/
