### ISSUE TITLE
Route won't match params with periods in them when no trailing slash is present

### ISSUE THREAD

**Issue by wmelton** [vuejs/router#1876]
### Reproduction

https://github.com/wmelton/vue-router-issue

### Steps to reproduce the bug

Run the test vue app from the reproduction link. 

To see a [✅](https://emojipedia.org/check-mark-button/)**passing** example, visit: http://localhost:5173/log/log_123

To see a [🚫](https://emojipedia.org/prohibited/)**failing** example, visit: http://localhost:5173/log/log.123

However, if you add a trailing slash to the failing example, it works... E.g. http://localhost:5173/log/log.123/

### Expected behavior

http://localhost:5173/log/log.123 should not result in a 404 since the underscore version works without a trailing slash.

### Actual behavior

The app 404's when a route param with a period in it is used and there is no trailing slash.

**Comment by posva** [comment]
This is a vite issue, you be able to should find the issues in its repo by searching dot in url
