### ISSUE TITLE
Undefined add on start of each url path

### ISSUE THREAD

**Issue by RomanHrynevych** [vuejs/router#1877]
### Reproduction

Can't reproduce

### Steps to reproduce the bug

I can't reproduce bug, and also this issue is happening not on all developers devices, my friend don't have it, he uses Windows PC, i checking MacBook

### Expected behavior

Don't want to see that undefined on start of each path in my app

Attached screenshot of **to**, **from**, so on start it is navigating from **undefined** to my redirect **workspace**
<img width="429" alt="image" src="https://github.com/vuejs/router/assets/82209198/63a83b82-ec65-40a5-ab4d-29b926125860">

### Actual behavior

i see that undefined everywhere 
<img width="229" alt="image" src="https://github.com/vuejs/router/assets/82209198/cb781a0d-16e7-4617-a217-9c73b04aeb53">

<img width="264" alt="image" src="https://github.com/vuejs/router/assets/82209198/b199477a-e090-492c-95cd-f7984381c5f4">

**Comment by RomanHrynevych** [comment]
attached also router options 

<img width="765" alt="image" src="https://github.com/vuejs/router/assets/82209198/b6d9eb83-793c-43ae-8675-d530c8d54cd5">

**Comment by posva** [comment]
I can’t check without a reproduction
