### ISSUE TITLE
Doubts about the routing lifecycle hooks

### ISSUE THREAD

**Issue by Devil-Cong** [vuejs/router#1878]
### Reproduction

https://jsfiddle.net/puL79c2f/3/

### Steps to reproduce the bug

1. Click `Home` link, the consol print `beforeEach ` and `afterEach`
2. Click `Home` link again, the console print `afterEach` only

### Expected behavior

Second times click `Home` link, the console should print nothing，because nothing router change

### Actual behavior

Nothing router change，but `afterEach` hook running

**Comment by posva** [comment]
Check navigation failures on docs. That’s why afterEach triggers
