### ISSUE TITLE
POST Request turning into GET Request on reload

### ISSUE THREAD

**Issue by DKhalil** [vuejs/router#1881]
### Reproduction

https://jsfiddle.net/posva/3yq6ojLv

### Steps to reproduce the bug

Whenever a POST request is sent via a form and you try and refresh the page, the repeated request is a GET request.

The Problem is much better reproduced locally:

```html
<script src="https://unpkg.com/vue@3"></script>
<script src="https://unpkg.com/vue-router@4"></script>

<div id="app">
  <pre>url: {{ $route.fullPath }}</pre>
  <ul>
    <li>
      <router-link to="/">Home</router-link>
    </li>
  </ul>
  <router-view></router-view>
</div>

<form action="" method="post">
  <input type="text" name="test">
  <button>Submit</button>
</form>


<script>

const { createRouter, createWebHistory } = VueRouter
const { createApp } = Vue

const Home = { template: `<div>home</div>` }


const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', redirect: '/foo' },
  ],
})

const app = createApp({})
app.use(router)

window.vm = app.mount('#app')
</script>
```

Save as HTML file, open in browser, click on submit, reload page, see no POST

![image](https://github.com/vuejs/router/assets/497250/49dad2da-bca8-4b8e-8b56-f88f6ba9849d)

### Expected behavior

A POST request on reload

### Actual behavior

A GET request on reload

**Comment by posva** [comment]
This is handled by the browser. Vue router doesn’t (or even can) interfere in this behavior

**Comment by DKhalil** [comment]
@posva yeah, but this only happens when loading vue-router. Without it this behaviour doesn't happen
