### ISSUE TITLE
Arabic pages paths with ":" is not working

### ISSUE THREAD

**Issue by ahmadqwer** [vuejs/router#1888]
### Reproduction

https://stackblitz.com/edit/github-awuqxh

### Steps to reproduce the bug

1- go to the Arabic page with `:`
2- the page is not found.
3-go to the English page with `:` and it works

### Expected behavior

Any Arabic page with `:` should work.

### Actual behavior

Any page with `:` and Arabic characters is not working.

### Additional information

I am trying to add the below page to my project
`/خاص:جديد`
but the issue is that any page with a colon `:` and with Arabic characters is not working.
as you can see in the reproduction i have created multiple pages
`/profile:new`
`/خاص:جديد`
`/جديد`
and if you try to go the English page with a colon it is working fine, but when you try to go to the Arabic one its not working while going to the page without a colon is working fine.

Note that the issue at first appeared using Nuxt 3 but is seems it is also reproducible in Vue 3 

https://github.com/nuxt/nuxt/issues/21582

**Comment by posva** [comment]
Params must be alphanumerical. They can also contain _

**Comment by ahmadqwer** [comment]
> Params must be alphanumerical. They can also contain _

Thank you for your reply, But what if i want just to have a colon `:` in my path with arabic characters? not as a param

**Comment by posva** [comment]
You escape it with \

**Comment by ahmadqwer** [comment]
> You escape it with \

I have tried to escape it with \ but its not working
i have tried it like this without encoding the colon
`routes.push({
  path: '/'+encodeURI('جديد')+'\:'+encodeURI('خاص'),
  component: pageComponent,
});`
and like this with encoding the colon
`routes.push({
  path: encodeURI('/خاص\:جديد'),
  component: pageComponent,
});`

**Comment by posva** [comment]
You need to escape the \ to be a \ inside a string 🙃
