### ISSUE TITLE
`LocationQuery` has incorrect type

### ISSUE THREAD

**Issue by jonathanjameswatson** [vuejs/router#1891]
### Reproduction

https://github.com/jonathanjameswatson/vue-router-4-query-types

### Steps to reproduce the bug

1. `npm install`
2. `npm run typecheck`
3. `npm run dev`
4. Go to `/` and check for errors.
5. Go to `/?foo=bar` and check for errors.

### Expected behavior

Step 3 should show that the code does not type-check, as it includes dangerous code that should produce an error in step 4.

### Actual behavior

Step 3 shows that the code type-checks. The bug, reproduced in step 4, comes from `route.query.foo` being `undefined`, despite `route.query.foo` not being inhabited by `undefined`.

### Additional information

The type of `LocationQuery` should be changed from:

```ts
export type LocationQueryValue = string | null

export type LocationQuery = Record<
  string,
  LocationQueryValue | LocationQueryValue[]
>
```

to

```ts
export type LocationQueryValue = string | null

export type LocationQuery = Record<
  string,
  LocationQueryValue | LocationQueryValue[] | undefined
>
```

`LocationQueryRaw` is defined as follows, meaning that it probably does not need to change:

```ts
export type LocationQueryValueRaw = LocationQueryValue | number | undefined

export type LocationQueryRaw = Record<
  string | number,
  LocationQueryValueRaw | LocationQueryValueRaw[]
>
```

**Comment by posva** [comment]
As mentioned in other issues this is fine as in JS you would write !query.foo rather than query.foo === null. Or given the possibility of the query being a string, typeof x === ‘string’

I think that in future versions we might stop using a Record to introduce the possibility of query param to be undefined but right now that would technically be a breaking change

**Comment by jonathanjameswatson** [comment]
If a value can be `undefined`, then `undefined` should be in its type. The type of an expression should be the set of all values it can be. In this case, this is clearly not true. Code that type-checks should work, but this requires the types to be actually correct,

`null` being in the type is not sufficient. There is a clear semantic difference between `null` and `undefined`. This is demonstrated by `null` and `undefined` being outputted for different reasons in your code (`undefined` for the key not being in the query, `null` for the key being in the query but not being given a value).

If a type includes `null` and not `undefined`, then your code should check for `null` rather than `null` and `undefined`. This is because `undefined` being added to the type at a later date would mean that different logic could be required for handling the value. Therefore, you want the code to no longer type-check, as programmer inspection is required in order to determine whether the code handling the `null` case can also handle the `undefined` case or if a new case should be added.

This would be a breaking change, as a developer's code would no longer type-check if it did not handle the `undefined` case. This is a good thing, since this code would not be safe.
