### ISSUE TITLE
Breaking change from 4.1.5 to 4.1.6

### ISSUE THREAD

**Issue by maslunde** [vuejs/router#1897]
### Reproduction

Working: https://jsfiddle.net/hr1fwL6v/29/
Not working: https://jsfiddle.net/2j3yLme7/6/

### Steps to reproduce the bug

```
const routes = [
  {
    path: '/',
    name: 'test,
    component: Component,
    children: [
      {
        path: '/integration',
        beforeEnter: (to, from, next) => {
           // show a toast message based on how the integration went.
        },
      },
    ],
  },
];
```

### Expected behavior

The path should still be accessible 

### Actual behavior

When not providing a name nor a component to a sub-route of children, the path is completely ignored

### Additional information

Issue originated from   
4.1.6 - **matcher: avoid empty records to be reached ([756f755]**   

Discovered by test
**it('avoids records with children without a component nor name', () => {**

I broke our production environment with a patch release from 4.1.5 to 4.1.6
I believe a warning should be enough not ignoring the path

**Comment by maslunde** [comment]
I have read through the comments on https://github.com/vuejs/router/commit/756f755731284f0f1899a2f8b62cb074b6f0f842 but I will still think of this as a breaking change.

I get the part where name or component should be added to make it considered as a regular route and appear in router.getRoutes(). 

However, it has been allowed not to and now it's introduced as mandatory.

**Comment by posva** [comment]
> However, it has been allowed not to and now it's introduced as mandatory.

It's not that it was allowed, it just happened to work at runtime but as mentioned at https://github.com/vuejs/router/commit/756f755731284f0f1899a2f8b62cb074b6f0f842#commitcomment-88299357


> Interesting, thanks for sharing! That kind of route record is nonvalid: it will report an error in TS, and that's why it didn't prevent this change from happening.
> 
> Other solutions such as global navigation guards and a simple switch case inside to handle a redirection table or even the one you mentioned about a custom router link are the expected ways of doing things rather than a `beforeEnter()` guard. I recommend you migrate to one of those instead.
> 
> ```ts
> router.beforeEach(to => {
>   if (to.path === '/google') {
>     window.location.replace(...)
>   }
> })
> ```
