### ISSUE TITLE
isReady resolves before scrollBehavior

### ISSUE THREAD

**Issue by mseeley** [vuejs/router#1899]
### Reproduction

https://vue3-vue-router-demo-gtj6cd.stackblitz.io

### Steps to reproduce the bug

Load up the reproduction URL and examine at logs.

<img width="1455" alt="image" src="https://github.com/vuejs/router/assets/30019/9dfe7bad-da44-4d4d-8fb5-e25a198a24eb">

### Expected behavior

`Awaitable<T>` from `scrollBehavior` settles before `isReady()` resolves.

### Actual behavior

`isReady()` resolves _during_ `handleScroll()` and before `scrollBehavior()` is _called_.

### Additional information

The issue is here; `finalizeNavigation()` is not awaiting `handleScroll()`.
https://github.com/vuejs/router/blob/b480bd1d6ffe6a525e1869112e90a49322ecac02/packages/router/src/router.ts#L963-L965

Internally `handleScroll()` progresses through several promises:
https://github.com/vuejs/router/blob/b480bd1d6ffe6a525e1869112e90a49322ecac02/packages/router/src/router.ts#L1175-L1178

Without awaiting `handleScroll()` then `markAsReady()` is called while `handleScroll()` is awaiting `nextTick()`.

From the docs I believe that `isReady()` should be resolving after all async router specific setup and display have occurred. With the current behavior I'm unable to deterministically wait to perform DOM side effects which are based on restored scroll position.

**Comment by mseeley** [comment]
Issue confirmed by this workaround.

`isReady()` resolves early then application code awaits a generous number of microtasks. During this time my sync `scrollBehavior` settles. Then after microtasks the router has restored scroll behavior and the application can work out side effects.

```
export function useWindowScrollLock() {
  const router = useRouter()

  // These methods should be kept safe to de-reference.
  return {
    async lock(): Promise<void> {
      try {
        await router.isReady()
        // See: https://github.com/vuejs/router/issues/1899
        await flushMicrotasks()
        lock()
      } catch (error) {
        console.error(error)
      }
    },
    unlock
  }
}
```

**Comment by posva** [comment]
This is intended and necessary design: the scroll handling is not awaited in any navigations. IsReady is not about the page being displayed (mounted), in fact, it’s used sometimes before mounting. It’s about the router being ready to be used and the application to display. Out of curiosity, what are you using isReady for?
