### ISSUE TITLE
Relative redirecting bug

### ISSUE THREAD

**Issue by mmacchao** [vuejs/router#1902]
### Reproduction

https://codesandbox.io/s/serene-archimedes-5pyny6?file=/index.html

### Steps to reproduce the bug

click button "redirect to /users/123/profile"

### Expected behavior

the location should be /users/123/profile

### Actual behavior

the location is /profile

**Comment by posva** [comment]
A relative location is relative to the current location, in this case to `/`. This is why I really recommend you to always use absolute redirects in route records
