### ISSUE TITLE
add a new `onNavigationAborted` hook

### ISSUE THREAD

**Issue by huang-julien** [vuejs/router#1905]
### What problem is this solving

hi :wave:

Currently there's no hook when a navigation is being aborted by a `false` within a beforeEach.

This feature would enhance https://github.com/nuxt/nuxt/pull/21751 by avoiding to create a new nuxt hook which doesn't really make sense and should be a vue-router feature.

### Proposed solution

The proposed API would be `router.onNavigationAborted((to, from) => void)`

**Comment by posva** [comment]
This was actually already possible but maybe a bit hidden in docs
