### ISSUE TITLE
 Discarded invalid param(s) warning on child routes despite param being supplied

### ISSUE THREAD

**Issue by jamespavett** [vuejs/router#1906]
### Reproduction

jsfiddle.net/posva/3yq6ojLv  WIP

### Steps to reproduce the bug

Setup a main routes with child routes under it:

```
export default [{
    path: 'example',
    redirect: {
        name: 'ex',
    },
    component: () => import('@/Example2.vue'),
    children: [{
        name: 'example',
        path: '',
        component: () => import('./List.vue'),
    }, {
        name: 'create',
        meta: {
            childOf: 'example',
        },
        path: 'create/:id?',
        component: () => import('./Create.vue'),
    }, ]
}]
```

### Expected behavior

No error was generated and navigation works as expected.

### Actual behavior

Getting the following error, but navigation still working as expected.

`example.js?t=1688141292750:39 [Vue Router warn]: Discarded invalid param(s) "id" when navigating. See https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22 for more details.`

### Additional information

Version 4.2.2.

Just setting up the reproduction.

I am passing the path as expected, however, I am getting the above error on 4.2.2 when navigating directly to a component, or via a refresh.

**Comment by posva** [comment]
Open the issue once you have the reproduction 🙃

BTW You need to put a / at the beginning of the example path
