### ISSUE TITLE
Route is updated when using history.back() to same route.

### ISSUE THREAD

**Issue by nieyuyao** [vuejs/router#1908]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-6h4bdz?file=src%2Fviews%2FA.vue,src%2Frouter%2Findex.js

### Steps to reproduce the bug

1. Click `push` button.
2. Click `back` button.
3. Route is updated and `num` is updated.

### Expected behavior

Route should not be updated as it has not changed.

### Actual behavior

The `watch` to `route` is triggered.

### Additional information

i think it should make the route update, as it does with `router.push(...)`.

The `finalizeNavigation` method will be called at the following,
https://github.com/vuejs/router/blob/c443de4217c0fefec48f6f8bbcc5a4fc9921b5d2/packages/router/src/router.ts#L1059-L1064

but there is no check whether `toLocation` and `currentRoute.value` are equal.
https://github.com/vuejs/router/blob/c443de4217c0fefec48f6f8bbcc5a4fc9921b5d2/packages/router/src/router.ts#L962-L963

**Comment by posva** [comment]
This is the intended behavior as the route entry changed. If you want to check only the path you can watch that instead `watch(() => route.path`

**Comment by nieyuyao** [comment]
This is just an example.  I would actually say that the history operation may update the currentRoute. This can come from outside the application, so the `router` cannot be used. And the `vue router` listens for events from history，it will cause the component to be updated.


https://github.com/vuejs/router/blob/c443de4217c0fefec48f6f8bbcc5a4fc9921b5d2/packages/router/src/router.ts#L973
