### ISSUE TITLE
afterEach callback isn't invoked when stopping the previous callback

### ISSUE THREAD

**Issue by depressedX** [vuejs/router#1917]
### Reproduction

https://codepen.io/AxisZ/pen/XWyeWjM

### Steps to reproduce the bug

relevant API: `router.afterEach`

1. Click on "Go to Home"
2. Check logs
3. Click on "Go to Home" again
4. Check logs

### Expected behavior

on step 2, it should print: 
```
first callback executed
second callback executed
```

on step 4, it should print: 
```
second callback executed
```
*the first callback isn't invoked since we stop it after first invoking.*

### Actual behavior

on step 2, it prints: 
```
first callback executed
```
**the second callback should be invoked on step2 either**

on step 4, it prints: 
```
second callback executed
```

**Comment by posva** [comment]
Fixed and released
