### ISSUE TITLE
【hash history】The CDN domain name cannot be configured based on the base tag in head.

### ISSUE THREAD

**Issue by mayunhai** [vuejs/router#1918]
### Reproduction

https://codesandbox.io/s/dazzling-minsky-qmkcnn?file=/src/App.vue

### Steps to reproduce the bug

1. click on 'Home' 'About' button

### Expected behavior

The routing function is normal and is not affected by the base tag.

### Actual behavior

The web page is redirected to an unexpected CDN domain name link.

### Additional information

Same problem as this [#685](https://github.com/vuejs/router/issues/685)

We've tried to solve this problem with Creates an HTML5 history, but we've had to use hash history for other reasons on the client. We also tried to rewrite history.pushState, but because of the copy method Illegal invocation, we had to abandon the base tag and rewrite a large number of relative paths in the project, including html/js/css.

**Comment by mayunhai** [comment]
I think vue-router may fix this problem through configuration. Otherwise, vue3 upgrade experience is a little sad. The key problem is difficult to find in the local environment and can only be observed in the production environment.

**Comment by posva** [comment]
If you set the base it also affects links (independently of vue-router):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <base href="https://example.dev/sub" />
  </head>
  <body>
    <h1 id="/top">Top</h1>
    <a href="/test">/test</a>
    <a href="#/top">#top</a>
  </body>
</html>
```

Open the page in your browser and try both links, they both redirect to example.dev
