### ISSUE TITLE
onunhandledrejection error occurs if dynamically import module fail

### ISSUE THREAD

**Issue by gaokun** [vuejs/router#1929]
### Reproduction

none

### Steps to reproduce the bug

Example, we may have routes like below:  (dynamically import)
```js
  {
    path: '/page1',
    name: 'page1',
    component: () => import('./views/page1.vue')
  },
  {
    path: '/page2',
    name: 'page2',
    component: () => import('./views/page2.vue')
  }
```

after build, we got `page1.xxxxx.js`, `page2.yyyyy.js`

Steps:
1. user: stay on page1, have no access page2 (dose not load `page2.yyyyy.js`)
2. server: update page2 then rebuild, we got `page2.zzzzz.js`
3. user: access page2

then we got error like this:
> Failed to fetch dynamically imported module: https://xxxx.com/assets/page2-yyyyy.js

### Expected behavior

this error could be catched.

### Actual behavior

this error is an `onunhandledrejection` error.

we have no chance to **catch** it. I  mean **catch** it, not **handle** it.

I know I can use `router.onError` to handler it. but it is still an  `onunhandledrejection` error.

### Additional information

related code:    [triggerError](https://github.com/vuejs/router/blob/0f14b994c4e1457c33344ff54454803597b12e03/packages/router/src/router.ts#L689)

```js
    return (failure ? Promise.resolve(failure) : navigate(toLocation, from))
      .catch((error: NavigationFailure | NavigationRedirectError) =>
        isNavigationFailure(error)
          ? // navigation redirects still mark the router as ready
            isNavigationFailure(error, ErrorTypes.NAVIGATION_GUARD_REDIRECT)
            ? error
            : markAsReady(error) // also returns the error
          : // reject any unknown error
            triggerError(error, toLocation, from)
      )
```

[triggerError](https://github.com/vuejs/router/blob/0f14b994c4e1457c33344ff54454803597b12e03/packages/router/src/router.ts#L1103)

```js
  function triggerError(
    error: any,
    to: RouteLocationNormalized,
    from: RouteLocationNormalizedLoaded
  ): Promise<unknown> {
    markAsReady(error)
    const list = errorHandlers.list()
    if (list.length) {
      list.forEach(handler => handler(error, to, from))
    } else {
      if (__DEV__) {
        warn('uncaught error during route navigation:')
      }
      console.error(error)
    }
    return Promise.reject(error)
  }
```

triggerError returns a promise with `**reject**`, and dose not catch or throw it.

Two ideas: 
1. throw error to errorHandler
2. `list.forEach(handler => handler(error, to, from))`, if some handlers handle the error, then return Promise.resolve().

**Comment by posva** [comment]
`router.onError()`

**Comment by gaokun** [comment]
@posva 
Plz take a minute to read it.
As I metioned, `I know I can use router.onError to handler it. but it is still an onunhandledrejection error.`

Yes, `router.onError()` can **handler** it, but not **catch** it.

Thank you
Ken

**Comment by posva** [comment]
You are right, if the error is handled it should not propagate, like Vue does with `app.config.errorHandler`

**Comment by posva** [comment]
PS: please don't ignore the reproduction next time, that's why I overlooked it 😛

**Comment by gaokun** [comment]
@posva 
Sorry, I thought it is quite clear, too confidence with my text description.

**Comment by posva** [comment]
After further investigation (even implementing it), changing this would be a breaking change. Right now, you only see the un caught rejection if you do router.push() manually, in which case, you can catch. This is what the router link component does.
As the name indicates, onError is a hook, not an error handler. Overriding *all* router.push could break plugins expecting to catch errors, that’s why this is different from Vue: there is only one place where errors can come from

**Comment by gaokun** [comment]
In my scenario, I found the `onunhandledrejection error` from Sentry.

(After rebuild, then nav to a route which didn't enter, then it will try to load old view files)
![image](https://github.com/vuejs/router/assets/7044628/89ae5b2c-75a1-4615-91f8-d3699ce017a9)

Now, I am going to filter it with Sentry.

Thank you
Ken
