### ISSUE TITLE
Wrong routing with routes with same name but different path

### ISSUE THREAD

**Issue by MarcelFinkbeiner** [vuejs/router#1930]
### Reproduction

https://codesandbox.io/s/testing-named-vue-router-bug-forked-r7zd5p

### Steps to reproduce the bug

click on /network button is working but the /network/WIFI/NONE button is getting catched and redirected.

### Expected behavior

The optional parameter name should not cause this behavior at least not without any warning/error

### Actual behavior

The correct route is getting catched without any information why

**Comment by posva** [comment]
You have duplicated names. They must be unique

**Comment by TheDutchCoder** [comment]
> Also it is not mentioned in the docs: https://router.vuejs.org/guide/essentials/named-routes.html.

I think it is: 
<img width="705" alt="image" src="https://github.com/vuejs/router/assets/1668207/b4e19024-377f-4ba2-98f2-410da016ce01">

**Comment by MarcelFinkbeiner** [comment]
Nice thank you!
