### ISSUE TITLE
Invalid savedPosition

### ISSUE THREAD

**Issue by bazuka5801** [vuejs/router#1936]
### Reproduction

https://codesandbox.io/s/scrollbehavior-doesnt-save-scroll-position-xvg6x2?file=/src/router.js

### Steps to reproduce the bug

1. Scroll down `Home` page
2. Go to `About` page
3. Tap back button on codesandbox browser
4. In the console you can see that the `savedPosition from vueRouter` is zero and the page scrolls to the top

### Expected behavior

The `Home` page opens with the position correctly saved

### Actual behavior

The `Home` page opens with the position incorrectly saved

### Additional information

# Workaround
https://codesandbox.io/s/scrollbehavior-doesnt-save-scroll-position-workaround-9t77rl?file=/src/router.js

# Proposal
Allow user to provide an options to vueRouter:
```ts
type AdditionalOptions = {
  // invoking in 2 cases:
  // 1. to save position (beforeEach)
  // 2. to scroll page instead of window.scrollTo (scrollContainer.scrollTo)
  getScrollContainer?: (currentRoute: RouteLocationNormalized) => HTMLElement
}
```
If not defined, the current behaviour is returned to

I've read https://github.com/vuejs/router/blob/a1611b6099403cfe9539ee8d4e9308b3a6a0175c/packages/router/src/scrollBehavior.ts#L176-L191

# P.s
I hate the `window.scrollTo`, `window.scrollIntoView` methods with `behavior: 'smooth'`, it would be great if we could make smoother behaviour with custom smoothScroll function.
Suggestion:

```ts
type AdditionalOptions = {
  // scrollContainer from the previous function getScrollContainer or document.scrollingElement
  scroll(scrollContainer: HTMLElement, position: ScrollPosition): void
}
```

**Comment by posva** [comment]
This is a limitation (as you noticed) due to the fixed position. There are plans to improve but we will go through an RFC like mentioned in the comments. Right now you can either use https://github.com/antfu/vue-router-better-scroller or implement a custom solution that runs with router.afterEach()
