### ISSUE TITLE
redirect function add a [children] param at runtime

### ISSUE THREAD

**Issue by genffy** [vuejs/router#1993]
### What problem is this solving

the scenario is the nest children routers have some biz logics to filter it such as menu auth.
but now [Redirct](https://router.vuejs.org/guide/essentials/redirect-and-alias.html#Redirect) function params only have a [to](https://github.com/vuejs/router/blob/ccbdd5268175d1b222ca77d7a36d821ca4bef47e/packages/router/src/types/index.ts#L297) param.

### Proposed solution

expect the redirect function add a children param for dynamic reach it nest children routes.

**Comment by genffy** [comment]
```javascript
redirect: ({ matched }) => {
  if (matched && matched.length > 0) {
    if (matched[0].children && matched[0].children.length > 0) {
      return matched[0].children[0]
    }
  }
 // error page
  return 'NoFind'
}
```

**Comment by posva** [comment]
BTW: You can probably only return the name if there is one, it's safer than returning the record as otherwise it would fallback to checking the `path` and if it contains params it will end up redirecting to something like `/path/:id`

```ts
redirect: ({ matched }) => {
  if (matched && matched.length > 0) {
    if (matched[0].children && matched[0].children.length > 0) {
      return { name: matched[0].children[0].name }
    }
  }
 // error page
  return 'NoFind'
}
```
