### ISSUE TITLE
useRoute params reactivity problem when redirecting to a different route using the same component

### ISSUE THREAD

**Issue by rafalkrawiec** [vuejs/router#2005]
### Reproduction

https://codesandbox.io/s/great-glitter-337zsf

### Steps to reproduce the bug

1. Click on the "Create" link.
2. A create page with the form will appear, fill in the name and click "Create" button.
3. A new resource is created in the store and redirect happens to edit page.

### Expected behavior

When redirect happens, `params` from `useRoute` should change, trigger a watcher and re-render the component.

### Actual behavior

History state is replaced and URL is changed as it should. But `params` from `useRoute` are not updated, and do not trigger re-render.

### Additional information

This happens only when you navigate to the route which uses the same component. The only workaround I found is passing `$route.path` as a key on `router-view` to force re-render that way. However, this is not a great solution, since in the actual project that I'm working on, there are some nested routes inside, and navigating between those also triggers a parent `router-view` with a key to re-render.

**Comment by posva** [comment]
You cannot destructure the route object as it's a reactive object, you loose reactivity. Do `const route = useRoute()` instead and access `route.params` (https://vuejs.org/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive)
