### ISSUE TITLE
Unable to get the hash from the url

### ISSUE THREAD

**Issue by thoriqadillah** [vuejs/router#2017]
### Reproduction

https://codesandbox.io/s/compassionate-ptolemy-ts3ppt?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce the bug

1. Add hash on the url bar in the sandbox like `#hello=world`
2. Look at the console

### Expected behavior

Vue `route.hash` is supposed to be matched with `window.location.hash`

### Actual behavior

Vue `route.hash` is not matched with `window.location.hash`

**Comment by thoriqadillah** [comment]
While this is like a minor bug, this same a case while this is not intended behavior
For example, when we utilize google oauth, it usually redirect us to the a path in our app with hash url that contains access token. But the `vue route` would return empty string, so we need to parse that hash with `new URLSearchParams` or something, and then turn it into query and then push route with `router.push({ path: somePath, query: someQuery })` 

But, another problem will occur. While the url seems to be absence from the hash, but if we once again `console.log(window.location.hash)`, it would not return empty string

This can leads into some unintended behavior

**Comment by posva** [comment]
See https://router.vuejs.org/guide/migration/#All-navigations-are-now-always-asynchronous. The initial route can be read once the router is ready.
