### ISSUE TITLE
When top and el are specified in scrollBehavior, the offset scrolls in different directions.

### ISSUE THREAD

**Issue by yoshi-pi** [vuejs/router#2027]
### Reproduction

https://jsfiddle.net/yoshipy/dhnvscf9/11/

### Steps to reproduce the bug

Check the position of Hello

### Expected behavior

It should scroll 10px above the element #hello because the code is

```
scrollBehavior() {
    return {
      top: -10,
      el: '#hello'
    }
  }
``` 

### Actual behavior

It scrolls 10px below the element #hello.

**Comment by posva** [comment]
when only `top` is specified only positives values make sense, when an element is specified, it becomes a relative position, so the meaning is a bit different. It can seen as an offset of _space in pixels_ needed between the top of the window and the element itself
