### ISSUE TITLE
The value of the top property in the scrollBehavior documentation should be corrected.

### ISSUE THREAD

**Issue by yoshi-pi** [vuejs/router#2029]
### Reproduction

https://router.vuejs.org/guide/advanced/scroll-behavior.html

### Steps to reproduce the bug

1. Scroll down to the following code:
```js
const router = createRouter({
  scrollBehavior(to, from, savedPosition) {
    // always scroll 10px above the element #main
    return {
      // could also be
      // el: document.getElementById('main'),
      el: '#main',
      top: -10,
    }
  },
})
```
2. Check the value of the top property

### Expected behavior

The top property should be 10, considering #2027.

### Actual behavior

The top property is -10.

**Comment by posva** [comment]
Don’t open duplicates please. The behavior won’t be changed as it would break everyone’s code and there is no reason to
