### ISSUE TITLE
problem in watch query of route

### ISSUE THREAD

**Issue by mohamadkhalili** [vuejs/router#2143]
### Reproduction

https://codesandbox.io/p/sandbox/lively-breeze-xy5573?file=%2Fsrc%2FApp.vue

### Steps to reproduce the bug

1- click on "names query 1"
2- check logs
3- click on "names query 2"
4- check logs

### Expected behavior

I expected that no log would be displayed after clicking on "names query 2".

### Actual behavior

In fact, it seems that the entire query element is watched, not the names element itself

**Comment by posva** [comment]
Vue does some optimizations in watchers to avoid rerunning with the same value. In your case you have an array, so they are always different: `[] !== []`. Using a string or a computed of a string could help you achieve what you want.
