### ISSUE TITLE
When update the page show message warning when it use  vue router dynamically

### ISSUE THREAD

**Issue by matteo6b** [vuejs/router#2164]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-xflg3u?file=src%2Frouter.ts

### Steps to reproduce the bug

When you stay in dynamically route created and update the page wIth F5 

### Expected behavior

You wouldn't have any warning errors.

### Actual behavior

<img width="359" alt="image" src="https://github.com/vuejs/router/assets/14913444/d51a7c64-97fd-4247-9c21-49c81953c308">

**Comment by posva** [comment]
When reloading the router requires you to add the routes again, so it’s normal it can’t find the location
