### ISSUE TITLE
Inconsistent trailing slash behaviour with  multiple optional parameters

### ISSUE THREAD

**Issue by panstromek** [vuejs/router#2190]
### Reproduction

https://jsfiddle.net/7sg5pry1/

### Steps to reproduce the bug

Try route like this:

`'/page/:first(a)?:second(b)?'`

(clicking the button in the reporduction link)

### Expected behavior

It matches:

`/page`

Text "should be visible" is visible in  repro

### Actual behavior

Doesn't match `/page`

Text "should be visible"  is not visible in  repro

### Additional information

This is inconsistent with the behaviour with only a single optional parameter:

`'/page/:first(a)?'` matches `/page`

[Documentation](https://router.vuejs.org/guide/essentials/route-matching-syntax.html#Sensitive-and-strict-route-options) doesn't explicitly mention this case, but implies should that trailing slash is removed in both cases

**Comment by posva** [comment]
By having 2 parameters, the parser expects the path to have at least one character. It only makes it fully optional if it's **only** an optional param. So you can group both params into a single one or create an alias without the params. I'm curious to see what the real route is

**Comment by panstromek** [comment]
The real route is something like this: `'/articles/:slug([\\w-]+-)?:article_id(\\d+)'`. The idea is to have optional slug for SEO and append id to it, so it should match

`/articles/99`
but also
`/articles/new-vue-version-released-99`

**Comment by panstromek** [comment]
I realized this example doesn't have optional id, sorry. That one is something like:

`'users/:userId/videos/:slug([\\w-]+-)?:video_id(\\d+)?'`

which shows a list of videos in swipe screen, and optionally starts at the specific one based on Id

**Comment by posva** [comment]
I see. Thanks for sharing! Using an alias is indeed the correct solution

**Comment by panstromek** [comment]
Ok, it would be useful to mention this in the docs, though. I broke a production for a few minutes, it's pretty unexpected behaviour. I'll submit a PR when I have some time to look into it
