### ISSUE TITLE
RouterLink doesn't change URL 

### ISSUE THREAD

**Issue by nguyentrunghieu15** [vuejs/router#2191]
### Reproduction

https://github.com/nguyentrunghieu15/web-beehome-pj

### Steps to reproduce the bug

1. Access to path "/"
2. Click on Login
3. Go to path "/login"

### Expected behavior

Url will change to "/login"
![image](https://github.com/vuejs/router/assets/78260236/771c6556-fdfe-40a6-bc63-395f8894a27a)

### Actual behavior

URL don't change 
 
![image](https://github.com/vuejs/router/assets/78260236/72dcf55d-d5b5-45f8-9df9-e74f50b0b6cc)

**Comment by nguyentrunghieu15** [comment]
I fixed this

`
const router = createRouter({
    history: createWebHistory(import.meta.env.BASE_URL),
    routes
})
`

**Comment by posva** [comment]
Please, next time consider using the [Discord server](https://chat.vuejs.org/), Discussions (if enabled in this repository), or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
