### ISSUE TITLE
router.push with alias not changing original URL

### ISSUE THREAD

**Issue by alghifarifikri** [vuejs/router#2194]
### Reproduction

https://jsfiddle.net/h3gdzkaf/3/

### Steps to reproduce the bug

Add the following to your router:

`{ path: '/bar', alias: '/bar/alias', component: Bar }`

### Expected behavior

when I'm access `'/bar/alias'` from `'/bar'`, URL should be change

### Actual behavior

original URL not change, always `'/bar'`

**Comment by posva** [comment]
This is expected, it's considered a duplicated navigation and it's skipped.
