### ISSUE TITLE
Introduce `elementTargetClass` option (alternative to `:target`)

### ISSUE THREAD

**Issue by AlttiRi** [vuejs/router#2231]
### What problem is this solving

While it supports scrolling to a hash:
```js
export const router = createRouter({
    history: createWebHashHistory(), // createWebHistory
    routes,
    scrollBehavior(to, from, savedPosition) {
        if (to.hash) {
            return { el: to.hash };
        }
    }
});
```
Setting the hash with History API do not affect on styling the element with  `:target` selector.

### Proposed solution

Add a new `createRouter`s option similar to
- https://router.vuejs.org/api/interfaces/RouterOptions.html#linkActiveClass
- https://router.vuejs.org/api/interfaces/RouterOptions.html#linkExactActiveClass

For example:
```js
export const router = createRouter({
    /* ... */
    elementTargetClass: "router-target-element"
});

```

**Comment by posva** [comment]
And what does this option do?

**Comment by AlttiRi** [comment]
Adds the class (`"router-target-element"` from the example above) to the element with the id the same as the URL's hash.
So, it can be used as an alternative to `:target` CSS selector which does not work with `vue-router`.

```css
:target, .router-target-element {
  font-weight: bold;
}
```

For example, the route `/main#1` will add the `router-target-element` class to the element with id `1`.

**Comment by posva** [comment]
I see, so it's specific to the web hash history and what you mentioned on #2230. It can be solved by creating that custom history you proposed, which seems more appropriate than introducing a new option that only applies to a specific history mode.

**Comment by AlttiRi** [comment]
> it's specific to the web hash history

No, this applicable to both `createWebHistory` and `createWebHashHistory`.
With `createWebHistory` mode the `:target` CSS selector does not work too.

**Comment by posva** [comment]
Thanks for pointing out #2076 , I forgot about it being a spec limitation. You should follow https://github.com/w3c/csswg-drafts/issues/6942 for a proper implementation of this.

You can implement the feature in many ways. The most reusable one would be a custom [Router Link](https://router.vuejs.org/guide/advanced/extending-router-link.html#Extending-RouterLink) by checking the current route and the this custom link resolved route's hash
