### ISSUE TITLE
Docs: Close button (to close the ad banner) is hidden

### ISSUE THREAD

**Issue by rohit2sharma95** [vuejs/router#2238]
### Reproduction

https://router.vuejs.org/

### Steps to reproduce the bug

1. Go to: https://router.vuejs.org/
2. Change your screen resolution to:- 1427 pixels wide (My device's is 1427 pixels wide X 806 pixels high)

### Expected behavior

The close button inside the ad banner should be visible

![image](https://github.com/vuejs/router/assets/26922866/c14288f0-5027-4c6a-8683-033dc66aa67b)

### Actual behavior

The close button is hidden under the **Early Access** button

![image](https://github.com/vuejs/router/assets/26922866/8f1c8c21-6beb-4384-b0ff-77bd21d89dc3)

### Additional information

Because of this user can not remove the banner :slightly_smiling_face:

**Comment by posva** [comment]
Thanks, I reported the issue to VueSchool
