### ISSUE TITLE
Router has modified my params

### ISSUE THREAD

**Issue by Sherlock-black** [vuejs/router#2253]
### Reproduction

?periodStartTime=2023-10-31T16:00:00.000+00:00&periodEndTime=2023-11-30T15:59:59.000+00:00

### Steps to reproduce the bug

router.push('/xxx?periodStartTime=2023-10-31T16:00:00.000+00:00&periodEndTime=2023-11-30T15:59:59.000+00:00')

> 

### Expected behavior

Target page get this:
route.query // { periodStartTime: 2023-10-31T16:00:00.000+00:00, periodEndTime: 2023-11-30T15:59:59.000+00:00 }

### Actual behavior

Target page get this:
route.query // { periodStartTime: 2023-10-31T16:00:00.000 00:00, periodEndTime: 2023-11-30T15:59:59.000 00:00 }

### Additional information

but `new Date('2023-10-31T16:00:00.000 00:00'); // Invalid Date`
so i need origin queryParams

**Comment by posva** [comment]
See #561
