### ISSUE TITLE
Getting syntax errors while using Vite with vue3/router4

### ISSUE THREAD

**Issue by omkar-kanekar1-tfs** [vuejs/router#2256]
### Reproduction

Details on code

### Steps to reproduce the bug

```
<router-view v-slot="{ Component }">
    <component
      :is="Component"
      class="container"
      ref="componentRef"
    />
  </router-view>
```

This is my router code.

Getting below error:
**[plugin:vite:vue] v-slot can only be used on components or <template> tags.**

Tried to rewrite syntax:
```
<router-view>
  <template v-slot="{ Component }">
    <component
      :is="Component"
      class="container"
      ref="componentRef"
    />
  </template>
</router-view>
```

Getting different error:
**Codegen node is missing for element/if/for node. Apply appropriate transforms first.**

### Expected behavior

As per error, if v-slot is not allowed on <router-link>, there should be alternate approach which should work without errors.

### Actual behavior

Getting error: [plugin:vite:vue] v-slot can only be used on components or <template> tags.

**Comment by posva** [comment]
This doesn’t seem to come from the router but from the vite plugin.
BTW follow the issue guidelines next times please
