### ISSUE TITLE
await doesn't work for router.go() but does for router.push()?

### ISSUE THREAD

**Issue by gureckis** [vuejs/router#2261]
### Reproduction

it is a documentation issue

### Steps to reproduce the bug

```
await router.push({ name: view })
```

works as expected based on the docs.

```
await router.go(-1)
```

does not (also generates Typescript warning). 

The docs on [programmatic navigation](https://router.vuejs.org/guide/essentials/navigation.html) and ["Waiting for the results of a Navigation"](https://router.vuejs.org/guide/advanced/navigation-failures.html#Waiting-for-the-result-of-a-Navigation) don't really make this difference clear.  Is is possible for both to be await-able?

### Expected behavior

Both router.push() and router.go() would work with await.

### Actual behavior

Only router.push() can be awaited.

**Comment by posva** [comment]
Unfortunately this is a technical limitation of the history api
