### ISSUE TITLE
docs(zh): fix the order of useRouter() and useRoute() in packages/docs/zh/guide/index.md

### ISSUE THREAD

**Issue by yaoshaohua** [vuejs/router#2277]
### Reproduction

https://github.com/yaoshaohua/router/tree/fix/useRouter-and-useRoute

### Steps to reproduce the bug

![Snipaste_2024-06-20_16-55-29](https://github.com/vuejs/router/assets/23162054/9a10db8b-1b5f-4951-a455-edca8479b6da)

### Expected behavior

你现在不一定要完全理解这段代码，关键是要知道可以通过 useRouter() 和 useRoute() 来访问路由器实例和当前路由

### Actual behavior

你现在不一定要完全理解这段代码，关键是要知道可以通过 useRoute() 和 useRouter() 来访问路由器实例和当前路由

**Comment by posva** [comment]
Just with the PR it’s enough 🙂
