### ISSUE TITLE
vue3.4.31 cannot retrieve the methods exposed by defineExpose using beforeRouteEnter

### ISSUE THREAD

**Issue by xiongzh120** [vuejs/router#2288]
### Vue version

3.4.31

### Link to minimal reproduction

https://play.vuejs.org/#eNp9UctOwzAQ/JWVL02qKAjBqWor8YgEHAAVjpaqkG5CSmJbthOCovw7a6cpPaCebO/Mjmdne3ajVNw2yBZsaTJdKgsGbaPWXJS1ktpCDxpzGCDXsoYZUWdc7DAvBb4oW0phgp4LAJHWuIDZfD6fRe79gbnUuJGNxURY1MHWygi2TiUCgZ0NwfdRJz2CoK1DWK2nGkBbxwXa+9SmQQhjcQjdOXDhLhn9bOFAgRWk5kdkQNyDiMNlhXEli4CzB6wqyRn1UfvoPumUNBj0Rw2nurwYQ6DxWcSsIZW8LOK9kYIS8uY4y2Stygr1YX7OFpNtzlL65/vJ16xu0Efhez4x+/qnvjedq3H2qtGgbpGzI2ZTTd5GOHl7pphOwFrumorYZ8ANUgKN8zjSbhuxI9snPO/20e+5FMW7STqLwkxDOaM+cc/njHZ/d2b0P7tX8fW0KUpx26J2mhQgAfHVJRt+AaEXzYo=

### Steps to reproduce

```js
<script setup lang="ts">
import { ref, reactive, ComponentPublicInstance } from 'vue'

interface IInstance extends ComponentPublicInstance {
  getData(): void
}

defineOptions({
  name: '***',
  beforeRouteEnter(_to, _from, next) {
    next((vm) => {
      const instance = vm as IInstance
      instance.getData() // 刷新列表数据（不缓存）
    })
  }
})


const getData = async () => {
     console.log("getData")
}

defineExpose({ getData })
</script>
```

### What is expected?

instance.getData() can be called

### What is actually happening?

instance.getData is not a function，3.3.x can be called

**Comment by posva** [comment]
Duplicate of #701
