### ISSUE TITLE
Route meta properties not available on application mount

### ISSUE THREAD

**Issue by Cadabyr** [vuejs/router#2311]
### Reproduction

https://play.vuejs.org/#eNqlVluP0zgU/itnA1JT7SQpA+Ih26lmdsWKXYmLAMEDQcJNTlsziR1spy0q/e8c27mVKfOCRlXtc/nOdy4+00NQMS7iLzpIA17VUhk4QK6QGbypazjCSskKJtsGJ5loDZRsDKpWEyf+OqitX6djdR1730z0qCF9ppkAiBuNoXf390o2woSTB+Q2mQYXQetO3OZ/RBFolSfka0UQRYtMzA1WdUmodAaYF3wLvLjKrF8WOBlJBdu2R7r4aFHJxS0YSaYJGT6XFc7bPJxqAd/v8WBLEpHbjf0+7zdPhqgdwpbjbtGbu5tjnRBtm0sySoauOle8NnTu20LVemOdx12J2ur/NbLbMZNvTlpH2kzg3ukLXLGmJDsbXLAKU5hQUScX9q7RNHU49UqAXArd9huu+vjh1OF1BrLEuJTr8PO/Nt5biwAPD84prtCwWOHXhivUN43ZHD8Pzo5n2BWaol4tfKy7bo6csxK4e89KZ9uSPM/jgyvCw4O392G97bEHOwCvKiw41TwFo2iqOt1AUlE+SsDh6PyPmbCHedJ3h6bUt+DsG3qBlVTfnnNt6OuiFboiqnNdtEFbBDuT72lG+qfUCdr31D02O4Mndr1keHhDFzW18aNN5AA1MxtqfTIhWpLABAqT9mEvwPYgJbtxG1JYsVLbAfSFGlDcmziF6on8CstX3EF9+omnIp7jYoWu1xtfx/RcccOpY+SzpOORNsqdmffY1LJxMe128e304w8lE2t650a7HTLq9Z2Fs7l0u8MizRO6nLxiCnPSi9+L00OdDeSnIapYTWMoBYVyBctaBUWg8vuBzoJh4Kw4CzbG1DpNkkbUt+uYOpgMFtdP4sfxjFaUNiNpjLqKlkrutJv7LGifTRZck1FS4NZIWeqI1fxXIe4YXj+Nn8aPkpIvE0JPuChw77C7d0dpGk0zsuLrn5K0Q8dLVK9qw2mGTpJlZSl3/zuZnbeeaL7B/PaM/Ivee8qvaU5RbXGUnGFqjbT5rfrZ25e4p3OvrGTRlGR9j/IN0pJqLEdv9ncjCqI9snNs/3M942L9Tj/bGxS6S8oSddVw9q6R/9yT+kD3cfxkVEVtvpWo41zbhUX/p+h90m8A77eUqkCVwmW9ByLLC3gwm83c7qsIjotoKY2RVQqPZvXeyWtWFES2l1CUTBAsLIDBn/RxwK13iStaDWPLzeU48gA/EMjzfEQghRn9XbYIwfEHCEvz9g==

### Steps to reproduce the bug

When the application is loaded check the console. The route meta is initially undefined and later captured by the watch

### Expected behavior

The route meta should be available on mounting of the application

### Actual behavior

The route meta is not available immediately on application mount

**Comment by posva** [comment]
This is expected because the initial navigation is asynchronous. Use router.isReady() if you need to wait for it to be ready
