### ISSUE TITLE
Router link type error v4.4.2

### ISSUE THREAD

**Issue by cyhnkckali** [vuejs/router#2322]
### Reproduction

https://stackblitz.com/~/github.com/cyhnkckali/vue-router-stackblitz

### Steps to reproduce the bug

***Type 'yarn build' in terminal and see the result

![image](https://github.com/user-attachments/assets/bb142e18-abf5-430d-8d6d-01c7ae302b89)

![image](https://github.com/user-attachments/assets/2794ab82-f6ad-4e54-a51c-233688bf9a66)

![image](https://github.com/user-attachments/assets/ba80ce78-0ef3-4215-a223-aa3133bef197)

### Expected behavior

To be able to get a build without a type error

### Actual behavior

There's nothing wrong with the enhancer mode. But it gives the current error when building.

The interesting thing is that with this version I observed that the props of my components do not appear in snippets

### Additional information

The interesting thing is that with this version I observed that the props of my components do not appear in snippets

**Comment by posva** [comment]
You are just missing the required `to` prop, that's the error you are seeing

**Comment by cyhnkckali** [comment]
Thank you @posva  

So what is the cause of the following effec?

"The interesting thing is that with this version I observed that the props of my components do not appear in snippets"
