### ISSUE TITLE
onComplete and onAbort function callbacks for router.replace do not work any longer

### ISSUE THREAD

**Issue by DangerousDetlef** [vuejs/router#2329]
### Reproduction

https://play.vuejs.org/#eNqNVVuP0zgU/ismrNRU28adgnjIZqphWbSzq11AgOCB8JAmp22oY1u2M1NU9b9zfMmlwwygmTbxuXznOzf3GDVFzZMvOkqjupFCGXIkpYLCwHMpyYlslGjI5KaFSc6DgRKtARU0CfXHQW39Ol0hZeJ9c96jxviZ5pyQpNUQe3d/bkTLTTx5jG6TaTSLgjtyyww0kqH/yhpmu4vVNTAmbLBHGcWjE0v3wBdtlODb1YtWKeCBMZGF2aUZDTpyPJLfnCLZtIy9QSU5nRwM9TgZL246wLeO5X813xMjLvOI5tHqb4Hv5Fo0kNFB/6BHsUZJ7/bcnr7zy2gXM7N9Ocf6UMMtocEuqDPaFwbr5Wt5bzf/h0aor9e1NviYBaHHHXd53nez76dN0IXumtoJQme7ttuEzux6yTACguvQDU0uySebytH3hUzoBGkJBOPYsnQIe5qdm7k6ntsOsa3x5zuhFIYa5xsfLeDOlyK9rz7x1MX0RPH1hOOZczi4RCvYFC3rsLHq43rYUdWlqqWxffIkBH+BVBngCF6SeEouV6RgoHDQ/Qx/FIpVjybTP+4J4qg2YHai0qk/IS/AjpeAfnuNeEFKiMGcEj/TKglGcVewaWJ2wGMff6AUT21c6+3r3KP/JUBzY2P8cojZCLdHtQ/8wn9cva4yeLiz0MtVV0Zc56UXrltjBCdXJavLPa7QOG9cpHAktzWurk0uo97jh95DXnchCrVtG5ynEcz5ep0N9NBposG0krCCbzGMsdR+mmwPFbI9D+RXat4UEndZcAzlGpAHBUboZyGPhq214jzaGSN1SmnL5X6b4JbQweLqafIkWdAKx3wkTUA387USt9pdHnkUJiGPrtCIVnBjhGB6Xsj6oRDfGV49S54lF5TVa4rotOYVHBx2Nw+YptG4IJt6eydJu9g1LshraWpcoLNkC1yY23+dzKgWeqLlDsr9PfIv+uApv1GA2d3AKDmDDQe8ka365btXcMD3XtmIqmVo/QPlW9CCtZajN/uz5RXSHtk5tv+4ntV8+16/PBjgukvKEnXVcPaukXZ7Hkp9oPskeTqqojZfGeik1PbWx5+PGbG/Dd5vLVQFKiVLeSBItq7I48Vi4VazQbiaz9cCR71JycVCHpxcFlWFZHsJRsk5whK8tcjv+PFXkvdmsMHrd2y5W44jD/ADgbIsRwRSssC/ZUCITt8AIAfmgg==

### Steps to reproduce the bug

1. call `router.replace(location, onComplete, onAbort)` whereas onComplete and onAbort a valid functions
2. neither onComplete nor onAbort a called correctly

(See HomeView.vue in Vuejs Playground)

### Expected behavior

onComplete and onAbort a called as callbacks to` router.replace` when passed as 2nd and 3rd arguments respectively

### Actual behavior

Both callbacks are no longer called. This was the case in Vue2 and it's still in the documentation of router Vue3.  
https://v3.router.vuejs.org/api/#router-replace

The` then().catch()` approach still works, though.

### Additional information

![image (4)](https://github.com/user-attachments/assets/1cc94014-1fd4-411c-9d9c-3971e699642c)

The replace() method does not have arguments for the callbacks any longer. If this is intentional, it should probably just be removed from the documentation and added as a step for migration from Vue2 to Vue3.

**Comment by skirtles-code** [comment]
The docs at `v3.router.vuejs.org` are for Vue Router 3, which is for Vue 2. With Vue 3 you'd be using Vue Router 4.

These parameters don't seem to be mentioned in the API docs for Vue Router 4: <https://router.vuejs.org/api/interfaces/Router.html#replace>. The guide to handling navigation failures also advocates the promise-based approach, <https://router.vuejs.org/guide/advanced/navigation-failures.html>.

From checking the latest Vue Router code, I don't think these parameters are supported in Vue Router 4.

It probably should be added to the migration guide.

**Comment by DangerousDetlef** [comment]
Oh my bad, sorry, I probably got my documentations mixed up. I was actually checking the URL beforehand and saw the "v3" and thought "Vue3, okay, that's the right docs."

We're doing a migration currently so things tend to get mixed up if you're careful. Again, my bad, sorry. But you're right, this should be added to the migration guide because I looked there and found nothing.

**Comment by posva** [comment]
PR to the docs welcome!

**Comment by DangerousDetlef** [comment]
PR here: https://github.com/vuejs/router/pull/2330
I hope this is fine :)
