### ISSUE TITLE
global components types are not supported after migration from v4.4.0 to v4.4.1

### ISSUE THREAD

**Issue by kamilGawron** [vuejs/router#2336]
### Reproduction

no reproduction link

### Steps to reproduce the bug

1. I have file `components.d.ts` with my global components types
2.  My components has theirs type:
<img width="804" alt="image" src="https://github.com/user-attachments/assets/c3ac1bef-b72d-43a4-b43e-7dcf7e295803">
3. After update to v4.4.1 components types are missing (without any other changes). Type is `any`
<img width="269" alt="image" src="https://github.com/user-attachments/assets/554508df-cbfe-4a49-b496-e5f0b3df4ca4">

### Expected behavior

support global component types from `components.d.ts`

### Actual behavior

global component types from `components.d.ts` are not supported from v4.4.1

### Additional information

node version 20.16.0

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏
