### ISSUE TITLE
Default nested route component rendering is different between using `to={name}` and `to="/path"`

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/router#2340]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-gkuhtc?file=src%2Fmain.js

### Steps to reproduce the bug

just click "my foo(by router name)" and "my foo(by router path)", the two links refer to the same route.

### Expected behavior

I think both links refer to the same route.

Both links should show the consistent rendering result.

### Actual behavior

cliking  "my foo(by router path)" works well, `MyBar` is rendered.

But "my foo(by router name)" did not render the default component `MyBar` nested under `MyFoo`.

### Additional information

I am not sure it is a bug or is designed like this.

**Comment by lovetingyuan** [comment]
route with `path: ""` should be default view and always be rendered, right?

**Comment by posva** [comment]
This is expected behavior. Put the name on the child instead for what you want
