### ISSUE TITLE
Allow url rewrites

### ISSUE THREAD

**Issue by dbzx10299** [vuejs/router#2349]
### What problem is this solving

With A/B testing we often need to rewrite to a different url while keeping the browser url the same.

### Proposed solution

NItro has a feature called [in-server fetch](https://nitro.unjs.io/guide/fetch#in-server-fetch), and Netlify and Nextjs both have url rewrites that allow this behavior.

If I have two pages in nuxt, `/foo` and `/bar`, there may be times I want to send a request for `/foo` and show the contents of `/bar`. This is an oversimplified example but there are valid use cases for this especially for ab testing or maybe showing a completely mobile product template rather than a desktop product template. Imaging detecting the user agent and fetching either the mobile version or desktop version of a page, while showing the same url in the browser.

Netlify has an excellent article on [split testing](https://www.netlify.com/blog/how-to-split-traffic-a-b-test-page-layouts-same-url/) as well as Vercel's article on [split testing](https://vercel.com/blog/ab-testing-with-nextjs-and-vercel).

If I implement this with nitro and nuxt, or if I use netlify the results are the same, I navigate to `/foo` and `/bar` gets sent up as shown in the network tab, but **then** vue router takes over and updates the url. That is what this whole feature is about, just allowing vue router in these situations to leave the browser url alone.

**Comment by posva** [comment]
This has to be defined by the user depending on their approach. For example, you can define an alias (for simple cases) or you can adapt the routing client side based on a header or any other hint sent by the server to adapt the route definitions

**Comment by dbzx10299** [comment]
Could you please give a very simple example of what you mean by adapting the router client side by using a header? I‘ve been trying to get this to work for a while now

**Comment by dbzx10299** [comment]
Got it. Thanks!
