### ISSUE TITLE
Cannot use groups in path param's custom regex

### ISSUE THREAD

**Issue by Voltra** [vuejs/router#2354]
### Reproduction

https://codesandbox.io/p/sandbox/dank-rgb-9yzhzl

### Steps to reproduce the bug

**With repro:** nothing

**Without repro:**
1. Create a route with the following pattern: `/:path(([a-z]|%2[Ff])+)`
2. Visit the following URI `/a%2Ftest`

### Expected behavior

For `route.params.path === "a%2Ftest"` to be true

### Actual behavior

An error is thrown

```
Invalid custom RegExp for param "path" (([a-z]|%2[Ff]): unterminated parenthetical
```

### Additional information

I've made this example as minimal as possible to make it easier to deal with. If it fails with a simple regex like this, it'll likely fail with more complex ones as well.

I've encountered this issue at work within a Nuxt 3 app with custom routing and tracked it down to a vue-router problem (I originally thought it came from path-to-regexp).

**Comment by posva** [comment]
You can, you need to escape the inner ): `((…\))`
