### ISSUE TITLE
route.params.id is always string | string[] even when repeatable params not used

### ISSUE THREAD

**Issue by jemdiggity** [vuejs/router#2360]
### Reproduction

https://play.vuejs.org/#eNqNVG1P2zAQ/itemNRWa+NSEB+yUMEQGpv2gmDal2Uf3MRtDYlt2U4pqvrfd7bzVigwoZLk7rm75+45exMUhPHwTgdRwAoplEEblCpKDD2XEm3RXIkC9VYl7SW8AShRGqoab4i9oYXY2NpHpAx9fMKbzH34DRKOUFhq2vfh/rsQJTf93gGE9QbBMKjCgV9saCFziJ9aYLw8nF7RPBe22LsYw6czS/eAF22U4IvpRakU5cZzRpKYZRTjyoc2G/TeOcJ5mefX4ETbrUuDfZ6Yk1Wd8Max/Mb4PTLiNAlwEkw/C3hHV6KgMW79L0aQGViasHP79SwuxnXN2Gqzm+s3ow8IV7jKHeNmMDAvP8vQ7FH0Oy2Eerxi2sBjWBl93q7So0bNRk/boCtdi1obKmVr2W1DO7jG0qwAXTtoKriuRFHodIdLf2PbW3qa0T7u/cHQQly0jtAfP6KNVxf1cA+aE0CJg/BRS37rorpAluGIZf8Nd/LtotuWPfwv/N/CJoMS3RnZ9dWpYtIgTU0pUU74AjbCaNiGzsmC0+CGsE+Pj3B+2qnB0Gpwf9C4isdboxhfRAhWHJ6A8vstiSKFDlkGUNh/RwUKw8eTUzWZ1rzhTE2erdeOoG909UadJtXeQn4ko4JIuJ0Eh1JuLZLKARUi5CzW1k7JmpNgaYzUEcYll/eLEOTCLeLsODwKxziDVepYQ6qL0UyJBw3vd5C9Ej8JzgCEM7oyQuR6RCR7qcQz4NlJeBIe4pzNMGTHjGd07XLb1HDNbKFNo0G4OVs8adJuGMup+ikNA2F3miVw6T18dTajStoQTZc0vd9jv9NrT/laUehuRTvNGaIWFG4k6768/UHX8N44C5GVOaBfcd5QLfLScvSwTyXPgHYH59h+cZrBPv7Sl2tDua6bskTdNBzeCXnxSust3aPwuDNFbR5zqsNU21sPrs8hsnejj5sJlVEVoYlcIyDLMnQwHo/hGCAAqQXjo5kwRhQROhzLtbNLkmXuEFUWqJJwSIumiKAP8HOJq+iczuEe6CKXk27lNn1LIE3TDoEIjeFvUmUItv8ACeGP2g==

### Steps to reproduce the bug

With a route like `{ path: '/id/:id', component: HomeView },`

```typescript
<script setup lang="ts">
import { useRoute } from 'vue-router';
const route = useRoute();
const myString: string = route.params.id; // id still wants to be string | string[]
</script>
```

There's a type error for myString even through I'm not using a repeatable param.

### Expected behavior

I'd expect `route.params.id` to be a string type.

### Actual behavior

`route.params.id` is a string | string[] type.

**Comment by posva** [comment]
This is expected. You can type them with casts as needed or use https://uvr.esm.is/
