### ISSUE TITLE
When child route path is "" , route.matched not meet expectations

### ISSUE THREAD

**Issue by chenxiaoleizi** [vuejs/router#2366]
### Reproduction

https://codesandbox.io/p/sandbox/nested-views-vue-router-4-examples-forked-66dmz9

### Steps to reproduce the bug

1. Nested routes
2. Set child route path ""
3. Console the `route.matched`
[Live example](https://codesandbox.io/p/sandbox/nested-views-vue-router-4-examples-forked-66dmz9)

### Expected behavior

The `route.matched` second route path should be "".

### Actual behavior

The `route.matched` second route path is "users".

### Additional information

![sandbox](https://github.com/user-attachments/assets/d041324e-33fd-4457-b446-5648c3cf00f4)

**Comment by posva** [comment]
matched contain normalized route records. It’s normal for it to be different.
