### ISSUE TITLE
Make `params` required in route location types if a typed route has required params to prevent runtime errors

### ISSUE THREAD

**Issue by Anoesj** [vuejs/router#2372]
### Reproduction

https://stackblitz.com/edit/github-woay8w-tedisk?file=composables%2FuseSomeRouteComposable.ts

### Steps to reproduce the bug

- Open or start a project that uses the typed router
- Call `router.resolve()` / `router().push()` / `router().replace()` etcetera with `{ name: 'any-route-that-requires-params' }` and omit the `params` object.
- TypeScript does not raise an error.

### Expected behavior

TypeScript raises an error, just like it does when providing `params` but as an empty object, or an object with other properties than the actual required params.

### Actual behavior

TypeScript does not show any errors when omitting the `params` object, when the typed route has required route params. In the runtime, this does result in an error though.

### Additional information
Developers use TypeScript to prevent runtime errors. If we fix this, we help preventing runtime errors.

**Comment by posva** [comment]
This is already tracked in unplugin-vue-router

**Comment by Anoesj** [comment]
@posva Could you link the corresponding issue? Is it this one? https://github.com/posva/unplugin-vue-router/issues/285

**Comment by posva** [comment]
Duplicate of https://github.com/posva/unplugin-vue-router/issues/285
