### ISSUE TITLE
vue devtools v7

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/router#2378]
### What problem is this solving

Is there any plans to migrate to devtools v7?

So far `@vue/devtools-api` is already using v7 as latest version and `https://devtools.vuejs.org/` is pointing to v7 now, and it has a good backward compatability.

### Proposed solution

Bump `@vue/devtools-api` to v7

**Comment by posva** [comment]
If everything works in old devtools and new ones, sure, go ahead and submit a PR 😄

**Comment by posva** [comment]
We will have to wait for this: https://github.com/orgs/vuejs/projects/19/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=84772275

**Comment by wChenonly** [comment]
> We will have to wait for this: [github.com/orgs/vuejs/projects/19/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=84772275](https://github.com/orgs/vuejs/projects/19/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=84772275)我们将等待这个：github.com/orgs/vuejs/projects/19/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=84772275

Does this mean it still needs to be compatible with the chrome plugin? Haven't upgraded @vue/devtools-api yet which would result in packaging duplicate dependencies
