### ISSUE TITLE
When using a Transition on RouterView, Component Templates cannot have multiple root nodes

### ISSUE THREAD

**Issue by modanq** [vuejs/router#2395]
### Reproduction

https://jsfiddle.net/modanq/0Lnasdhz

### Steps to reproduce the bug

Click on Home, then Foo, then Bar
Then try to click back on Foo or Home

### Expected behavior

The fade transition occurs when navigating to or from Bar route/component.

### Actual behavior

No fade in transition going to Bar and then no transitions after going to Bar. This is because there are multiple root nodes in the Bar template (e.g., header and section).

### Additional information

If you remove the <section>baz</section> or <header>bar<header> from the Bar template file then it works.

**Comment by posva** [comment]
Yes, this is a Vue transition limitation
