### ISSUE TITLE
Ability to pass a custom function for computeScrollPosition

### ISSUE THREAD

**Issue by preetmishra** [vuejs/router#2402]
### What problem is this solving

Due to the way our HTML layout is set up, the scrollbar appears on an element several levels deeper rather than on the window itself, breaking the intended functionality. The scroll position is never restored because of the incorrect values in the `savedPosition` property.

```ts
export const computeScrollPosition = (): _ScrollPositionNormalized => ({
  left: window.scrollX,
  top: window.scrollY,
})
```

### Proposed solution

We’d like the option to pass a custom function that calculates the top value based on another element's `scrollTop` in the HTML. We're open to other workarounds and are happy to submit a PR with the proposed solution as well.

**Comment by posva** [comment]
Closing in favor of #2403 which was in the board but not visible in issues
