### ISSUE TITLE
Support `router.push` without page navigation but update the route (shallow routing)

### ISSUE THREAD

**Issue by martinszeltins** [vuejs/router#2411]
### What problem is this solving

Currently, when using `router.push`, it reloads all components on the page. This behavior resets the component state, which may not always be desirable.

I can use `window.history.pushState({}, '', '/shipment/123')` which will update the URL without navigating **BUT** it will not update the `router` object - vue-router will still think that I am on previous page.

For example, if I have a "Create Shipment" page with a form to fill out. When I press "Save", I want the URL to change from `/shipment` to `/shipment/:uuid`, but I don't want to navigate anywhere, otherwise the form will be reset, I don't really need a navigation, only update the URL and route.

`/shipment` and `/shipment/:uuid`

Both routes point to the same page and component. When url is `/shipment` you get a new form and with `/shipment/:uuid` you get filled out form. If I use `router.push('/shipment/:uuid')`, the form will be reset because all components are reloaded. But I just want the URL to change because if the user refreshes the page, it should open the saved shipment not a new shipment. I have needed this feature several times already.

Here is a reproduction where you can see the problem:
https://github.com/martinszeltins/vue-router-update-url-only

When I press "Save Shipment" - it performs a navigation to `/123`. But I don't want a navigation. I only want the URL to update to `/123`

### Proposed solution

It seems like I am looking for something like Next.js `shallow routing` but Next.js supports only updating query not params so it is not as good - https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing

This feature request proposes adding an optional parameter to the router.push function to allow developers to choose whether or not to reload the components on the page or to keep the page alive. This will handle the scenarios where only the URL update is required without impacting the component lifecycle.

Introduce an option to the router.push function, such as:

```ts
router.push('/shipment/123', { keepAlive: true })

// or silent
router.push('/shipment/123', { silent: true })

// or shallow
router.push('/shipment/123', { shallow: true })
```

This would do 2 things:
1. It will update the URL to `/shipment/123`
2. It will update the `route` object so `route.params.id` will be `123`

But it will NOT trigger a real navigation - that is important.

**Comment by posva** [comment]
> Currently, when using router.push, it reloads all components on the page. This behavior resets the component state, which may not always be desirable.

This is because you have a `key` attribute, otherwise, Vue will reuse the component. You can achieve the behavior you want by removing or adapting the `key`.

> But I just want the URL to change because if the user refreshes the page, it should open the saved shipment not a new shipment. I have needed this feature several times already.

There is already a feature in Vue Router to achieve this: the [`route` prop](https://router.vuejs.org/api/interfaces/RouterViewProps.html#route-). It's poorly documented, so it's normal if you haven't seen it. It's what allows to have modals with a different URL and you can find an example [here](https://github.com/vuejs/router/tree/main/packages/router/e2e/modal). You should be able to use that example to build your own feature. [I can also help out understanding it or building it](https://cal.com/posva/consultancy).

> But it will NOT trigger a real navigation - that is important.

It would be interesting to know why you think that's important. From Vue Router perspective, it's **crucial** to **always trigger navigations**. Otherwise, navigation guards are not run and one cannot hook into the navigation, a major deal breaker for extensibility. In other words, _shallow routing_ is just a workaround that ends up creating problems and should be avoided at all cost in routing.

**Comment by martinszeltins** [comment]
> It would be interesting to know why you think that's important. From Vue Router perspective, it's **crucial** to **always trigger navigations**. Otherwise, navigation guards are not run and one cannot hook into the navigation, a major deal breaker for extensibility. In other words, _shallow routing_ is just a workaround that ends up creating problems and should be avoided at all cost in routing.

Because sometimes, I am super sure that I don't want or care about navigation guards or lifecycles. The only goal is to update the URL so that if the user reloads the page, they will land on this specific URL.

**Comment by martinszeltins** [comment]
> This is because you have a `key` attribute, otherwise, Vue will reuse the component. You can achieve the behavior you want by removing or adapting the `key`.

What key? Where do I have a key?

**Comment by posva** [comment]
> Because sometimes, I am super sure that I don't want or care about navigation guards or lifecycles. The only goal is to update the URL so that if the user reloads the page, they will land on this specific URL.

FYI Component lifecycles are disconnected from the navigation. Navigation guards can be added by plugins, you we are never sure that the goal is to update just the URL. Navigation guards can always skip if they want to. I'm confident the modal demo will prove helpful for your use case 🙂

I updated my comment!

**Comment by gabrielstuff** [comment]
This would have been very helpful. I’m looking at the modal example right now. Nonetheless, I see many cases where we want the route to change without triggering onMounted or adding a full history entry. For an SPA it's common that we want the `url` to reflect the `UI state` : 
 
- tabs
- modals
- filters or sorting list
- steps forms
- dynamic dashboards

Is the undocumented key "route" the go to solution for this cases ? 

https://github.com/vuejs/router/blob/main/packages/router/e2e/modal/index.ts#L191

Thanks a lot !

**Comment by martinszeltins** [comment]
@gabrielstuff I basically agree with @posva that ignoring lifecycle events could potentially lead to problems in the future. But at the same time it is very tempting to want the route to change without performing a navigation. It's a tricky situation for sure.

My use case was that I had a single page with optional `id` parameter. So at first, it is a new form, then user clicks on "Save" and the form gets saved and I needed to append the `id` to my route. The only way to do that is to navigate to that route (even though it is the same page).

I either 1) performed navigation which caused data to be re-loaded or 2) I put the data into Pinia store and after navigation grabbed the data from there.

I feel like if you know what you are doing, you should still have the option to simply update the route without performing a navigation. (maybe with a warning).
