### ISSUE TITLE
希望能增加页面通信能力

### ISSUE THREAD

**Issue by elarbor** [vuejs/router#2420]
比如进入详情页，操作完，返回列表页需要更新。没操作就不需要更新列表。
如同uniapp的[EventChannel](https://uniapp.dcloud.net.cn/api/router.html#event-channel)能力一样

![动画](https://github.com/user-attachments/assets/7fa10a4c-5c3d-47c4-9b79-768ebff65d3f)

https://uniapp.dcloud.net.cn/api/router.html#navigateto

**Comment by posva** [comment]
Use the discussions to ask questions.
