### ISSUE TITLE
Add route with priority

### ISSUE THREAD

**Issue by davidmeirlevy** [vuejs/router#2422]
### What problem is this solving

my routes list looks like:
```
const routes = [
{path: '/', name: 'mainWithSomeGuard', children: [...]},
]
```

In my app, some of the routes are dynamically injected at runtime.
so i get a list of routes from the backend and add them: 
`router.addRoute('mainWithSomeGuard', { ...routeData })`

now i got a new behavior that i want to add routes to the root list, and not as children of `mainWithSomeGuard`, because those routes should be "unguarded".
when i add them, they are being added to the bottom of the routes array, so when the router works, so i cannot reach the unguarded route.

i can fix it by dynamically remove all routes, add the new dynamic routes and then inject the "regular routes" as before, but i thought it would be nicer to have an ability to "unshift" a route instead of "push", to force the priority.

If you think it's a good idea, too, I can try to fix it myself and contribute it.

Thanks.

### Proposed solution

something like:
````
router.addRoute({ ..., unshift: true })
// or:
router.addRoute({ ..., beforeRoute: anotherRouteNameOrPath })
// or:
router.unshiftRoute({ ... })
```

### Describe alternatives you've considered

_No response_

**Comment by posva** [comment]
routes are already ordered correctly. If you have redundant routes with the same score eg /:a-:b/ and /:a_:b will both match /a-_b, you will indeed need to remove and add but you should t have routes with the same score in the first place

In other words, the priority is not based in the order of the routes

**Comment by davidmeirlevy** [comment]
@posva i'll give a more concrete example.

let's say this are my routes:
```
const routes = [
  {  path: '/', 
     name: 'mainWithSomeGuard', 
     children: [ { path: ':dynamicParam' }  ]
  },
 {
   path: 'static-route-path', ...
  }
]
```
No one can access the ' static-route-path' because the inner child is inside the 'main'.
when I change the order, no one can access the main route and everything below.

you're right that is not a conventional type of app. :)

I can find a workaround that will work, but if there's something I can contribute to make it more slick - I would like to be a part of it.
