### ISSUE TITLE
Provide a way to disable warnings for MATCHER_NOT_FOUND when testing 

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/router#358]
When adding tests to a component using the router, one might need to provide a mock router. I currently use:

```typescript
const mockRouter = createRouter({ history: createWebHistory(), routes: [] });
describe('Navbar.vue', () => {
  test('should ...', () => {
    const navbar = mount(Navbar, {
      global: {
        plugins: [mockRouter],
        stubs: {
          RouterLink: RouterLinkStub
        }
      }
    });
    // ...
  });
});
```

It works perfectly, but the router emits a warning:
```
console.warn node_modules/vue-router/dist/vue-router.cjs.js:225
    [Vue Router warn]: No match found for location with path "/"
```

As most tests are using the same code, the warning is emitted a lot and pollutes the test output.
Until VTU or the router itself provides built-in support for testing (if ever, see https://github.com/vuejs/vue-test-utils-next/issues/152 for curious readers), do you think we could guard this warning with a setting to hide it? I can open a PR if you provide some guidance (and think this is useful of course).

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/router/issues/359
