### ISSUE TITLE
 No match found for location with path

### ISSUE THREAD

**Issue by anncwb** [vuejs/router#471]
### Version
4.0.0-beta.10

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-router-next](https://new-issue.vuejs.org/?repo=vuejs/vue-router-next)

### Steps to reproduce
```
router.beforeEach(async (to) => {
    for (let index = 0; index < routes.length; index  ) {
      const route = routes[index];
      await router.addRoute(RootRoute.name!, route);
    }

    return true;
  });
```

### What is expected?
Jump after addRoute

### What is actually happening?
Before the jump occurred with addRoute, after I added the route dynamically, the page was blank.

**Comment by anncwb** [comment]
I dynamically add routing in the routing guard does not take effect

**Comment by posva** [comment]
you need to reroute again

**Comment by asasugar** [comment]
You need to addRoute before the app is not mounted, you can refer to https://github.com/vuejs/router/issues/643
