### ISSUE TITLE
number of router.getRoutes() and routes'number of createRouter  params  are inconsistent

### ISSUE THREAD

**Issue by luo-geng** [vuejs/router#480]
### Version
4.0.0-beta.11

### Reproduction link
[https://github.com/Luooooooo/vue-router-next_test.git](https://github.com/Luooooooo/vue-router-next_test.git)

### Steps to reproduce
point the button .and router not match
![image](https://user-images.githubusercontent.com/29565303/93754698-b72e8680-fc34-11ea-961f-21dcf9dc6d65.png)

### What is expected?
can goto my page

### What is actually happening?
No match found for location with path "/main/index"

**Comment by posva** [comment]
When reporting a bug, please provide a boiled down reproduction with no extra dependencies. I tried reproducing it https://jsfiddle.net/gvwcjdy5/ but it seems to be working. Can you provide a boiled down repro so I can take a look?

**Comment by Luooooooo** [comment]
> When reporting a bug, please provide a boiled down reproduction with no extra dependencies. I tried reproducing it https://jsfiddle.net/gvwcjdy5/ but it seems to be working. Can you provide a boiled down repro so I can take a look?

ok，i just leave a UI lib。

**Comment by posva** [comment]
it's not running, and remove the ui libs, please

**Comment by Luooooooo** [comment]
> it's not running, and remove the ui libs, please

i try to same routes，it works ok(get 5 routes)。but in @vue/cli (node env)。i get 4 routes。emmm,i should have more try
![image](https://user-images.githubusercontent.com/29565303/93759898-a6ced980-fc3d-11ea-92fe-df1d36ed9269.png)

**Comment by Luooooooo** [comment]
i found  this  problem at  the  redirect of routes ,refers to it's absolute path and reactive path

**Comment by Luooooooo** [comment]
Property `name` can not be repeated

**Comment by posva** [comment]
No, they are unique, if repeated, they will override an existing route. This is intentional
