### ISSUE TITLE
Warning message for routes added with addRoutes

### ISSUE THREAD

**Issue by anncwb** [vuejs/router#521]
### Version
4.0.0-beta.13

### Steps to reproduce
When I use addRoutes to dynamically add routes. [Vue Router warn]: No match found for location with path ”xxx” warning will appear. This warning appears before addRoutes. But does not affect the use

### What is expected?
Remove the warning because I have added it using dynamic routing

### What is actually happening?
Warning

**Comment by posva** [comment]
Please open a new issue with a boiled down reproduction using the jsfiddle link provided on the issue helper.

**Comment by anncwb** [comment]
This problem only occurs locally. I wrote a GitHub repo

## Reproduction link
https://github.com/anncwb/vue-router-next-warn-repo

## Steps to reproduce

1.  Clone the repo (https://github.com/anncwb/vue-router-next-warn-repo)
2.  `yarn install`
3. `yarn run dev`
4. go to `http://localhost:3000/layout/pageA`
5. Open the Google console
6. refresh page
7. appear ` [Vue Router warn]: No match found for location with path "/layout/pageA"`

The page is accessible, but this warning appears. Can it be deleted
@posva

**Comment by posva** [comment]
I see what you mean now. If you are trying to create some kind of declarative routing, there are a few things that differ in terms of options (like using `end: false`) and that will be shown in the docs once they are created.

The warning is still helping a lot of people with typos and mistakes, so it's better to keep it.

**Comment by juukee** [comment]
What if I need to cancel this reminder? An urgent need
