### ISSUE TITLE
The addRoute method does not work

### ISSUE THREAD

**Issue by yunlongduan** [vuejs/router#546]
### Version
4.0.0-beta.13

### Reproduction link
[https://codesandbox.io/s/sleepy-yonath-cn9hv?file=/src/router.js](https://codesandbox.io/s/sleepy-yonath-cn9hv?file=/src/router.js)

### Steps to reproduce
Correct routing rules. Use addRoute to add dynamic routing prompt "No Match Found for Location with Path".

### What is expected?
Dynamically added routes can be accessed normally

### What is actually happening?
Dynamically added routes cannot be accessed properly

---
It is invalid to dynamically add routing access according to the rules of the link above

**Comment by posva** [comment]
Check the console: you should omit the `next` parameter. You should also avoid re adding the routes on each navigation

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
