### ISSUE TITLE
Documentation using modules

### ISSUE THREAD

**Issue by posva** [vuejs/router#829]
Right now the starting guide (https:/router.vuejs.org/guide/) still uses a vanilla index.html approach. I think that it was easier back when vue-router started but now it isn't anymore and that maybe that page should be updated using .vue components and pointing to vue CLI and vite. It should maybe also point to Vue docs explaining Vue files.

What are your thoughts on this?

Do you have any other ideas on how to restructure this section of the docs?

**Comment by Stanley-SJTU** [comment]
https://www.vuemastery.com/blog/vue-router-a-tutorial-for-vue-3/
Found an example about how to use router in Vite.

**Comment by ionous** [comment]
starting a new vue3 + vite project, one thing that confused me was how to import the router in order to use the code from the [getting started page](https://next.router.vuejs.org/guide/).  ( `import * as VueRouter from 'vue-router` seems to do the trick. )

the previous version's [installation page](https://router.vuejs.org/installation.html ) had an example import statement, and that was a nice help.

**Comment by daniel-farina** [comment]
This was really painful, not having the imports needed for the examples on the router was quite confusing.

**Comment by thedamon** [comment]
There have been several PRs to fix this rather obvious fault in the docs.. what do we need to do to get one in?

https://github.com/vuejs/router/pull/1951
https://github.com/vuejs/router/pull/1769
https://github.com/vuejs/router/pull/1323

**Comment by posva** [comment]
@thedamon Most of them were actually incorrectly importing the router. It was better not to spread bad practices. Currently I need to focus on other stuff before getting back to the documentation, so feedback on difficult parts is welcome: https://github.com/vuejs/router/discussions/2068
BTW, https://github.com/vuejs/router/pull/1323 is the one that was the closest to what the page should look like but the author closed it probably because It's been 2 years

**Comment by skirtles-code** [comment]
The examples have been updated by #2174.

I think this issue can be closed.
