### ISSUE TITLE
路由页面提示我找不到 文件/user 等……

### ISSUE THREAD

**Issue by yang867381349** [vuejs/router#887]
### Version
4.0.6

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-router-next](https://new-issue.vuejs.org/?repo=vuejs/vue-router-next)

### Steps to reproduce
{
    "code": "200",
    "data": [
        {
            "alwaysShow": true,
            "children": [
                {
                    "alwaysShow": false,
                    "children": [],
                    "component": "system/user/index",
                    "hidden": false,
                    "meta": {
                        "icon": "user",
                        "noCache": false,
                        "title": "用户管理"
                    },
                    "name": "User",
                    "path": "user",
                    "redirect": ""
                }
            ],
            "component": "Layout",
            "hidden": false,
            "meta": {
                "icon": "system",
                "noCache": false,
                "title": "系统管理"
            },
            "name": "System",
            "path": "/system",
            "redirect": "noRedirect"
        }
    ]
}

response.data.data.forEach((items) => {
       if (!router.hasRoute(items.name)) {
             router.addRoute(items)  //添加后页面获取不到动态内容
             router.options.routes.push(items) //只能用这个方式获取动态内容
        }
})

vue-router.esm-bundler.js?6c02:71 [Vue Router warn]: No match found for location with path "user"

### What is expected?
这个问题我无法通过文档获取有关处理？

### What is actually happening?
有一个比较好的解决方案

---
希望能够及时解决。

**Comment by edison1105** [comment]
"path": "user"
应该是
"path": "/user",

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
