### ISSUE TITLE
No match found for location with path "/index"

### ISSUE THREAD

**Issue by AIKE-Dereks** [vuejs/router#896]
### Version
4.0.6

### Reproduction link
[https://new-issue.vuejs.org/](https://new-issue.vuejs.org/)

### Steps to reproduce
import { createRouter, createWebHistory, createWebHashHistory, RouteRecordRaw } from "vue-router";
import NotFound from "../views/NotFound.vue";
import Login from "../views/login/login.vue";
import Test from "../views/test/test.vue";
// 静态路由
const routes: Array<RouteRecordRaw> = [
    { path: '/', redirect: '/index', meta: { menuShow: false, } },
    { path: "/login", name: "Login", component: Login, meta: { menuShow: false, } },
    { path: "/404", name: "NotFound", component: NotFound, meta: { menuShow: false, } },
];
const router = createRouter({
    history: createWebHashHistory(),
    routes: routes,
})
router.beforeEach(async (to, from, next) => {

    router.addRoute({ path: "/test", name: "Test", component: Test })

    next()
})
export default router;

### What is expected?
router能够正常访问

### What is actually happening?
动态路由router.addRoute无效，无法动态添加router，无法访问

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by AIKE-Dereks** [comment]
Maybe I replied a little essay question，I updated the question，addRouter() is no effective,So,That's the way I wrote it. Any questions?
