### ISSUE TITLE
dynamic addrouter have  [Vue Router warn]: No match found for location with path "XXXXXXXX"

### ISSUE THREAD

**Issue by ybf970928** [vuejs/router#900]
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/vue3-admin-element-gc8fq](https://codesandbox.io/s/vue3-admin-element-gc8fq)

### Steps to reproduce
Refresh dynamic addrouter have warn,
I don't know if I wrote it wrong

### What is expected?
no warn

### What is actually happening?
have warn

**Comment by ybf19970928** [comment]
<img width="1005" alt="WechatIMG31" src="https://user-images.githubusercontent.com/63764959/115645126-63af2300-a352-11eb-9f81-1497275a34fe.png">

**Comment by edison1105** [comment]
你的 demo 太复杂了，能提供一个最小的可以复现的 demo 吗?
Your repro is too complicated. Can you provide a minimal demo?

**Comment by ybf19970928** [comment]
> 你的demo太复杂了，能提供一个最小的可以复现的demo吗？
> 您的复制太复杂。您可以提供一个最小的演示吗？

emm~, i do not  konw how to do a minimal demo, but I think the problem should be here 
<img width="641" alt="WeChatb47f001cf61ce2b606c5c029fdd6f360" src="https://user-images.githubusercontent.com/63764959/115650043-14b9bb80-a35b-11eb-8764-deeca0e6171c.png">

**Comment by PenAndPapers** [comment]
I'm also encountering this issue, after I reload the page it redirects me to the 404 page.

**Comment by PenAndPapers** [comment]
Use RouteRecordRaw as type instead of any btw.

```
asyncRoutes.forEach((route: RouteRecordRaw) => {
          const routeName: any = route.name;
          if (!router.hasRoute(routeName)) {
            router.addRoute(route);
          }
        });
```

**Comment by posva** [comment]
@ybf19970928 

you should either put a `/` at the beginning of the path (`/userChildName`) of the route definition of userChildName or use the full path including its parent `/userInfoName/userChildName`

```js
{ 
                path: '/userInfoName',
                name: '用户姓名',
                meta: { icon: 'el-icon-info' },
                component: () => import('../views/userInfoName.vue'),
                children: [
                    {
                        path: '/userChildName',
                        name: '用户孩子的姓名',
                        meta: { icon: 'el-icon-s-custom' },
                        component: () => import('../views/userChildName.vue')
                    }
                ]
            }
```

**Comment by xiaoqiangz** [comment]
我也遇到这个问题了，动态路由添加后刷新页面会出现该警告。 请问解决了吗？

**Comment by ybf970928** [comment]
警告不算错误, 不用解决😆😆

xiaoqiangz ***@***.***> 于2023年4月7日周五 15:50写道：
