### ISSUE TITLE
No match found for location with path "xxx"

### ISSUE THREAD

**Issue by pany-ang** [vuejs/router#903]
### Version
4.0.6

### Reproduction link
[https://github.com/v3-projects/v3-admin](https://github.com/v3-projects/v3-admin)

### Steps to reproduce
在 router.beforeEach 中使用 router.addRoute(route)动态添加路由，然后进入该路由所在的页面，并使用浏览器的刷新按钮。

### What is expected?
不会出现 No match found for location with path "xxx"

### What is actually happening?
出现了 No match found for location with path "xxx"，但是页面并没有任何异常

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

You should also read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro before opening an issue, thanks.

**Comment by cjq02** [comment]
how to hide the warning message

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/router/issues/359
