### ISSUE TITLE
router.replace({name: 'xyz'}) throws if no match, even if default route is available

### ISSUE THREAD

**Issue by saurabhgupta050890** [vuejs/router#967]
### Version
4.0.6

### Reproduction link
[https://codepen.io/saurabhgupta050890/pen/jOBmrrr](https://codepen.io/saurabhgupta050890/pen/jOBmrrr)

### Steps to reproduce
Do a programmatic navigation via router.replace({name: 'xyz'}) to a route that does not exists 

### What is expected?
Should redirect to a default route 

### What is actually happening?
an error is thrown

**Comment by PeterAlfredLee** [comment]
Hi, @saurabhgupta050890  

try this:
```js
router.replace('/xyz')
```
or this:
```js
router.replace({ path: '/xyz' })
```
That error won't throw.

Also, you should add a `route` config for `'/xyz'`,  for example:
```js
{ path: '/xyz', component: About },
```
otherwise you can't match any route.

**Comment by saurabhgupta050890** [comment]
Yeah  ..  its working fine this way .. But in our app we use mostly named routes for programmatic navigation. There is also a catchAll route so any non matching route will redirect to a default route.  What  I was expecting that this behavior should be consistent in both path and name. 

There should be way to handle non matching named routes or they should redirect to catchAll path

**Comment by PeterAlfredLee** [comment]
@saurabhgupta050890 
You may need to read the [doc#catch-all-404-not-found-route](https://next.router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route) again.
Correct me if I'm wrong, there is no kind of setting can catch all `named route`, we can only catch all not matched path.

If you try to use a `named route` like `router.replace({name: "xyz"})`, make sure this route config exist.

**Comment by GGwujun** [comment]
First, you should define named route, you can push/replace to a named route.
```javasceipt
{
    path: '/user/:username',
    name: 'user',
    component: User
}
```
or you can define a parameter with a custom regex,[details see](https://next.router.vuejs.org/guide/migration/index.html#removed-star-or-catch-all-routes)
```javascript
// https://next.router.vuejs.org/guide/migration/index.html#removed-star-or-catch-all-routes
const routes = [
  // pathMatch is the name of the param, e.g., going to /not/found yields
  // { params: { pathMatch: ['not', 'found'] }}
  // this is thanks to the last *, meaning repeated params and it is necessary if you
  // plan on directly navigating to the not-found route using its name
  { path: '/:pathMatch(.*)*', name: 'not-found', component: NotFound },
  // if you omit the last `*`, the `/` character in params will be encoded when resolving or pushing
  { path: '/:pathMatch(.*)', name: 'bad-not-found', component: NotFound },
]
```

**Comment by saurabhgupta050890** [comment]
@PeterAlfredLee Sorry If I was not clear but I meant for the case of no route match. 

`router.replace({path: "/xyz"})` will successfully redirect to a path defined in `/pathMatch(.*)*` if there is no match and also it won't throw. It just shows a warning even if `/pathMatch(.*)*` is not present. But this is not the case for `router.replace({name: 'xyz'})`

I believe there is no way to replicate the behavior of `/pathMatch(.*)*` for named routes. 

My expectations were that both of them should be consistent. 

One workaround I can think of is to wrap `router.replace({name: 'xyz'})` in a try catch and redirect to an existing route in catch block but that might not be an ideal solution.

**Comment by posva** [comment]
This is expected for named routes so you can find typos in your app
